import { STORYARC_SCHEMA_VERSION } from "../constants";
import { validateStoryArcContentPackage } from "./schema";

export const STORYARC_FOUNDATION_FIXTURE = {
  schemaVersion: STORYARC_SCHEMA_VERSION,
  packageId: "storyarc-phase-a-school-gate",
  appSlug: "storyarc",
  releaseTarget: "phase-a-foundation",
  curriculum: {
    sourceKey: "indonesia-phase-ef-descriptive-gap",
    sourceTitle: "StoryArc Phase E/F Descriptive Mapping",
    sourceAuthority: "UNVERIFIED_PROJECT_MAPPING",
    sourceVerificationNote: "Academic lead must supply verified CP identifiers before curriculum-alignment claims.",
    versionKey: "phase-a-v1",
    versionTitle: "Phase A foundation mapping",
  },
  competencies: [
    {
      competencyKey: "cpa-e-interact",
      title: "Familiar spoken interaction",
      description: "Introduce yourself and sustain a short first-school interaction.",
    },
  ],
  objectives: [
    {
      objectiveKey: "obj-g10-01",
      competencyKey: "cpa-e-interact",
      title: "Introduce yourself and respond naturally in a new-school context",
      primarySkill: "SPEAKING",
    },
  ],
  assets: [
    {
      assetId: "scene-school-gate-procedural-v1",
      revision: 1,
      type: "PROCEDURAL_SCENE",
      purpose: "Original layered School Gate scene",
      sourceType: "original-human",
      sourceReference: "lib/storyarc/game/create-school-gate-game.ts",
      authorOrGenerator: "Nexus StoryArc implementation",
      license: "NEXUS-PROPRIETARY",
      commercialUseAllowed: true,
      derivativeUseAllowed: true,
      attributionRequired: false,
      rightsOwner: "Nexus Talenta Indonesia Academy",
      approvalStatus: "TEMPORARY_APPROVED",
      storageLocation: "procedural://storyarc/school-gate/v1",
      contentHash: "procedural-school-gate-v1",
      mimeType: "application/x-phaser-procedural-scene",
      byteSize: 0,
      temporary: true,
    },
    {
      assetId: "char-hana-procedural-v1",
      revision: 1,
      type: "PROCEDURAL_CHARACTER",
      purpose: "Original temporary Hana character presentation",
      sourceType: "original-human",
      sourceReference: "lib/storyarc/game/create-school-gate-game.ts",
      authorOrGenerator: "Nexus StoryArc implementation",
      license: "NEXUS-PROPRIETARY",
      commercialUseAllowed: true,
      derivativeUseAllowed: true,
      attributionRequired: false,
      rightsOwner: "Nexus Talenta Indonesia Academy",
      approvalStatus: "TEMPORARY_APPROVED",
      storageLocation: "procedural://storyarc/hana/v1",
      contentHash: "procedural-hana-v1",
      mimeType: "application/x-phaser-procedural-character",
      byteSize: 0,
      temporary: true,
    },
    {
      assetId: "fx-petals-procedural-v1",
      revision: 1,
      type: "PROCEDURAL_PARTICLE",
      purpose: "Original low-cost petal particles",
      sourceType: "original-human",
      sourceReference: "lib/storyarc/game/create-school-gate-game.ts",
      authorOrGenerator: "Nexus StoryArc implementation",
      license: "NEXUS-PROPRIETARY",
      commercialUseAllowed: true,
      derivativeUseAllowed: true,
      attributionRequired: false,
      rightsOwner: "Nexus Talenta Indonesia Academy",
      approvalStatus: "TEMPORARY_APPROVED",
      storageLocation: "procedural://storyarc/petals/v1",
      contentHash: "procedural-petals-v1",
      mimeType: "application/x-phaser-procedural-particles",
      byteSize: 0,
      temporary: true,
    },
  ],
  items: [
    {
      stableId: "sm-g10-01",
      revision: 1,
      kind: "LEARNING_ITEM",
      grade: "GRADE_10",
      track: "STORY_MODE",
      phase: "PHASE_E",
      title: "The Gate",
      primarySkill: "SPEAKING",
      supportingSkills: ["LISTENING", "VOCABULARY"],
      objectiveKeys: ["obj-g10-01"],
      content: {
        runtimeGeneration: false,
        instructionLanguage: "id",
        targetLanguage: "en",
        arcId: "arc-first-bell",
        episodeId: "sm-g10-01",
        lessonBlocks: [],
        scene: {
          sceneId: "scene-school-gate",
          locationId: "loc-gate",
          arcId: "arc-first-bell",
          episodeId: "sm-g10-01",
          assetIds: [
            "scene-school-gate-procedural-v1",
            "char-hana-procedural-v1",
            "fx-petals-procedural-v1",
          ],
          entryNodeId: "hana-welcome",
          dialogueNodes: [
            {
              id: "hana-welcome",
              speakerId: "char-hana",
              text: "Hey, you look new. First day at Cakrawala?",
              expressionState: "warm",
              choices: [
                {
                  id: "intro-natural",
                  text: "Yeah, it is. I'm still getting used to everything, but I'm excited to be here.",
                  dimension: "natural",
                  classification: "LEARNING_PRACTICE",
                  nextNodeId: "hana-reaction-natural",
                  actionType: "choose-natural-introduction",
                  feedback: {
                    lenses: ["NATURALNESS", "SOCIAL_COMMUNICATION"],
                    message: "This sounds open and natural, and it gives Hana an easy detail to continue with.",
                    modelUtterance: "I'm still getting used to everything, but I'm excited to be here.",
                  },
                },
                {
                  id: "intro-formal",
                  text: "Yes. I am pleased to make your acquaintance on this first school day.",
                  dimension: "overly-formal",
                  classification: "LEARNING_PRACTICE",
                  nextNodeId: "hana-reaction-formal",
                  actionType: "choose-formal-introduction",
                  feedback: {
                    lenses: ["CONTEXT", "NATURALNESS"],
                    message: "The grammar works, but the register is too formal for a classmate at the gate.",
                    modelUtterance: "Yeah, it's my first day. Nice to meet you.",
                  },
                },
                {
                  id: "intro-vague",
                  text: "Maybe. I don't know. It's just a school, I guess.",
                  dimension: "vague",
                  classification: "LEARNING_PRACTICE",
                  nextNodeId: "hana-reaction-vague",
                  actionType: "choose-vague-introduction",
                  feedback: {
                    lenses: ["SOCIAL_COMMUNICATION"],
                    message: "Hana can understand you, but the vague response gives her little to build on.",
                    modelUtterance: "Yeah, it's my first day. I'm a little nervous, actually.",
                  },
                },
              ],
              terminal: false,
            },
            {
              id: "hana-reaction-natural",
              speakerId: "char-hana",
              text: "You'll get used to it. Come on—I'll show you where everyone gathers.",
              expressionState: "warm",
              terminal: true,
              choices: [],
            },
            {
              id: "hana-reaction-formal",
              speakerId: "char-hana",
              text: "Wow, very official! You can relax with me. I'm Hana.",
              expressionState: "surprised",
              terminal: true,
              choices: [],
            },
            {
              id: "hana-reaction-vague",
              speakerId: "char-hana",
              text: "Fair enough. Let's start with names, then. I'm Hana.",
              expressionState: "concerned",
              terminal: true,
              choices: [],
            },
          ],
          hotspots: [
            { id: "hotspot-bridge-club-sign", label: "Inspect the old club notice", actionType: "inspect-school-sign" },
            { id: "hotspot-school-gate", label: "Enter the campus", actionType: "enter-school" },
          ],
        },
        vocabulary: [],
        expressions: [
          {
            entryId: "exp-getting-used-to-it",
            expression: "getting used to it",
            meaningId: "mulai-terbiasa",
            register: "neutral",
            sourceIntentKey: "intent-natural-new-school-response",
            recallHookId: "recall-getting-used-to-it",
          },
        ],
        recallHooks: [
          {
            hookId: "recall-getting-used-to-it",
            sourceEntryId: "exp-getting-used-to-it",
            objectiveKey: "obj-g10-01",
            intendedEvidenceClass: "RECALL_EVIDENCE",
          },
        ],
        recallReferences: [],
      },
      sourceMetadata: {
        sourceType: "human-authored",
        authorOrOperator: "Nexus StoryArc Phase A",
      },
    },
  ],
} as const;

const report = validateStoryArcContentPackage(STORYARC_FOUNDATION_FIXTURE);
if (!report.valid || !report.package) {
  throw new Error(`Invalid built-in StoryArc foundation fixture: ${JSON.stringify(report.errors)}`);
}

export const STORYARC_FOUNDATION_PACKAGE = report.package;
