ALTER TABLE "StoryArcAssignmentProgress"
ADD COLUMN "score" DOUBLE PRECISION,
ADD COLUMN "maxScore" DOUBLE PRECISION,
ADD COLUMN "scorePercent" DOUBLE PRECISION,
ADD COLUMN "scoreSource" TEXT,
ADD COLUMN "scoredAt" TIMESTAMP(3);
