import type { ArabicLesson } from "../types";

export const level2Lessons: ArabicLesson[] = [
  {
    id: "L2M3L1",
    appSlug: "arabic",
    level: "L2_DAILY",
    levelTitle: "Daily Life in Saudi",
    moduleId: "M3",
    moduleTitle: "Daily Routine",
    lessonTitle: "Rutinitas Pagi",
    order: 5,
    scenario: "Pagi hari di asrama atau kamar kerja, kamu perlu komunikasi singkat: bangun, sarapan, siap-siap kerja.",
    targetSkill: "daily",
    arabicType: "mixed",
    explanationId:
      "Banyak kata kerja pagi pakai pola sederhana: أقوم (saya bangun), آكل (saya makan), أذهب (saya pergi). Saudi sering memakai versi pendek أبغى + kata kerja.",
    saudiNote: "أبغى (abghaa) adalah cara Saudi paling umum bilang 'saya mau' — pakai ini lebih natural daripada أريد (uriidu) di percakapan harian.",
    vocabulary: [
      { arabic: "صباح", transliteration: "Shabaah", meaningId: "Pagi", type: "fusha" },
      { arabic: "أقوم من النوم", transliteration: "Aquumu min an-nawm", meaningId: "Saya bangun tidur", type: "fusha" },
      { arabic: "فطور", transliteration: "Fathuur", meaningId: "Sarapan", type: "fusha" },
      { arabic: "أبغى فطور", transliteration: "Abghaa fathuur", meaningId: "Saya mau sarapan (Saudi)", type: "saudi" },
      { arabic: "قهوة", transliteration: "Qahwah", meaningId: "Kopi", type: "fusha" },
      { arabic: "شاي", transliteration: "Syaay", meaningId: "Teh", type: "fusha" },
      { arabic: "أذهب إلى العمل", transliteration: "Adzhabu ilaa al-‘amal", meaningId: "Saya pergi ke kerja", type: "fusha" },
      { arabic: "متأخر", transliteration: "Muta’akkhir", meaningId: "Terlambat", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Teman", arabic: "صباح الخير، فطرت؟", transliteration: "Shabaah al-khair, fatharta?", meaningId: "Selamat pagi, sudah sarapan?", type: "fusha" },
      { speaker: "Kamu", arabic: "صباح النور، لا، أبغى قهوة.", transliteration: "Shabaah an-nuur, laa, abghaa qahwah.", meaningId: "Selamat pagi juga, belum, saya mau kopi.", type: "mixed" },
      { speaker: "Teman", arabic: "يلا، نذهب إلى العمل.", transliteration: "Yalla, nadzhabu ilaa al-‘amal.", meaningId: "Ayo, kita pergi kerja.", type: "mixed" },
    ],
    practicePrompts: [
      "Tulis 3 kegiatan paginu dalam Bahasa Arab.",
      "Ucapkan 'Saya mau kopi' dengan versi Saudi (أبغى قهوة).",
      "Latih kalimat 'saya pergi kerja' dengan pola أذهب إلى.",
    ],
    quiz: [
      {
        id: "L2M3L1Q1",
        lessonId: "L2M3L1",
        questionType: "saudi_expression",
        promptId: "Versi Saudi dari 'Saya mau kopi' adalah?",
        options: ["أبغى قهوة", "أريد قهوة", "هذه قهوة", "قهوة لي"],
        correctAnswer: "أبغى قهوة",
        explanationId: "Versi Saudi: أبغى + apa yang diinginkan. Lebih natural di percakapan sehari-hari.",
        difficulty: "easy",
      },
      {
        id: "L2M3L1Q2",
        lessonId: "L2M3L1",
        questionType: "meaning",
        promptId: "Apa arti فطور?",
        arabicText: "فطور",
        transliteration: "Fathuur",
        options: ["Sarapan", "Makan siang", "Makan malam", "Kopi"],
        correctAnswer: "Sarapan",
        explanationId: "فطور adalah makanan pagi/sarapan.",
        difficulty: "easy",
      },
      {
        id: "L2M3L1Q3",
        lessonId: "L2M3L1",
        questionType: "situation",
        promptId: "Temanmu mengajak يلا، نذهب إلى العمل. Artinya apa?",
        arabicText: "يلا، نذهب إلى العمل",
        options: ["Ayo, kita pergi kerja", "Saya pulang dari kerja", "Saya tidak mau kerja", "Hari ini libur"],
        correctAnswer: "Ayo, kita pergi kerja",
        explanationId: "يلا (yalla) = ayo, نذهب = kita pergi, إلى العمل = ke kerja.",
        difficulty: "easy",
      },
      {
        id: "L2M3L1Q4",
        lessonId: "L2M3L1",
        questionType: "meaning",
        promptId: "Kata متأخر artinya?",
        arabicText: "متأخر",
        transliteration: "Muta’akkhir",
        options: ["Terlambat", "Cepat", "Pagi", "Lelah"],
        correctAnswer: "Terlambat",
        explanationId: "متأخر = terlambat. Kata yang penting saat kamu butuh minta maaf di kerja.",
        difficulty: "medium",
      },
      {
        id: "L2M3L1Q5",
        lessonId: "L2M3L1",
        questionType: "vocabulary",
        promptId: "شاي artinya?",
        arabicText: "شاي",
        transliteration: "Syaay",
        options: ["Teh", "Kopi", "Air", "Susu"],
        correctAnswer: "Teh",
        explanationId: "شاي = teh. Minuman favorit di Saudi.",
        difficulty: "easy",
      },
      {
        id: "L2M3L1Q6",
        lessonId: "L2M3L1",
        questionType: "situation",
        promptId: "Kamu mau bilang 'Saya pergi ke kerja'. Mana yang paling tepat?",
        options: ["أذهب إلى العمل", "أذهب إلى البيت", "أبغى عمل", "ذهبت أمس"],
        correctAnswer: "أذهب إلى العمل",
        explanationId: "أذهب = saya pergi; إلى العمل = ke kerja.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "L2M4L1",
    appSlug: "arabic",
    level: "L2_DAILY",
    levelTitle: "Daily Life in Saudi",
    moduleId: "M4",
    moduleTitle: "Food & Restaurant",
    lessonTitle: "Pesan Makanan di Restoran",
    order: 6,
    scenario: "Di restoran lokal atau food court. Kamu lapar dan perlu pesan makanan + minuman dengan jelas.",
    targetSkill: "daily",
    arabicType: "mixed",
    explanationId:
      "Pesan dengan pola أبغى (Saudi) atau أريد (Fusha) + makanan. Tanya harga dengan كم السعر؟. Restoran Saudi paham bahasa Arab campuran Inggris.",
    saudiNote: "Kebanyakan staf restoran ramah pada pekerja Indonesia. Mereka sering bantu kalau kamu kesulitan, asal kamu sopan dan jelas.",
    vocabulary: [
      { arabic: "أبغى رز", transliteration: "Abghaa ruzz", meaningId: "Saya mau nasi (Saudi)", type: "saudi" },
      { arabic: "أبغى دجاج", transliteration: "Abghaa dajaaj", meaningId: "Saya mau ayam (Saudi)", type: "saudi" },
      { arabic: "ماء", transliteration: "Maa’", meaningId: "Air", type: "fusha" },
      { arabic: "أبغى ماء", transliteration: "Abghaa maa’", meaningId: "Saya mau air (Saudi)", type: "saudi" },
      { arabic: "كم السعر؟", transliteration: "Kam as-si‘r?", meaningId: "Berapa harganya?", type: "fusha" },
      { arabic: "حار", transliteration: "Haarr", meaningId: "Pedas", type: "fusha" },
      { arabic: "غير حار", transliteration: "Ghair haarr", meaningId: "Tidak pedas", type: "fusha" },
      { arabic: "تكفي", transliteration: "Takfii", meaningId: "Cukup (Saudi, sering dipakai)", type: "saudi" },
      { arabic: "الفاتورة من فضلك", transliteration: "Al-faatuurah min fadhlik", meaningId: "Bon/struk tolong", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Pelayan", arabic: "أهلاً، تفضل، إيش تبغى؟", transliteration: "Ahlan, tafaddhal, eesh tabghaa?", meaningId: "Halo, silakan, kamu mau apa?", type: "saudi" },
      { speaker: "Kamu", arabic: "أبغى رز ودجاج وماء.", transliteration: "Abghaa ruzz wa dajaaj wa maa’.", meaningId: "Saya mau nasi, ayam, dan air.", type: "saudi" },
      { speaker: "Pelayan", arabic: "حار أو غير حار؟", transliteration: "Haarr aw ghair haarr?", meaningId: "Pedas atau tidak pedas?", type: "fusha" },
      { speaker: "Kamu", arabic: "غير حار من فضلك.", transliteration: "Ghair haarr min fadhlik.", meaningId: "Tidak pedas, tolong.", type: "fusha" },
      { speaker: "Pelayan", arabic: "تمام.", transliteration: "Tamaam.", meaningId: "Oke, baik.", type: "saudi" },
    ],
    practicePrompts: [
      "Latih order: 'Saya mau nasi, ayam, air' dalam versi Saudi.",
      "Tulis 3 cara tanya harga.",
      "Buat 1 kalimat lengkap meminta makanan tidak pedas.",
    ],
    quiz: [
      {
        id: "L2M4L1Q1",
        lessonId: "L2M4L1",
        questionType: "saudi_expression",
        promptId: "Bagaimana cara Saudi yang paling natural bilang 'Saya mau air'?",
        options: ["أبغى ماء", "هذه ماء", "ماء أنا", "أحب ماء"],
        correctAnswer: "أبغى ماء",
        explanationId: "Versi Saudi: أبغى + ماء.",
        difficulty: "easy",
      },
      {
        id: "L2M4L1Q2",
        lessonId: "L2M4L1",
        questionType: "meaning",
        promptId: "Pelayan bertanya إيش تبغى؟. Apa artinya?",
        arabicText: "إيش تبغى؟",
        transliteration: "Eesh tabghaa?",
        options: ["Kamu mau apa?", "Berapa harganya?", "Kamu dari mana?", "Apa nama kamu?"],
        correctAnswer: "Kamu mau apa?",
        explanationId: "إيش = apa (Saudi), تبغى = kamu mau. Pertanyaan paling umum dari pelayan Saudi.",
        difficulty: "easy",
      },
      {
        id: "L2M4L1Q3",
        lessonId: "L2M4L1",
        questionType: "situation",
        promptId: "Kamu tidak tahan pedas. Apa yang kamu bilang ke pelayan?",
        options: ["غير حار من فضلك", "أبغى حار", "أحب حار", "كم السعر"],
        correctAnswer: "غير حار من فضلك",
        explanationId: "غير حار = tidak pedas; من فضلك = tolong/silakan.",
        difficulty: "medium",
      },
      {
        id: "L2M4L1Q4",
        lessonId: "L2M4L1",
        questionType: "meaning",
        promptId: "كم السعر؟ artinya?",
        arabicText: "كم السعر؟",
        transliteration: "Kam as-si‘r?",
        options: ["Berapa harganya?", "Di mana toiletnya?", "Saya mau pesan", "Berapa banyak?"],
        correctAnswer: "Berapa harganya?",
        explanationId: "كم = berapa; السعر = harga.",
        difficulty: "easy",
      },
      {
        id: "L2M4L1Q5",
        lessonId: "L2M4L1",
        questionType: "situation",
        promptId: "Setelah selesai makan, kamu mau minta struk. Mana yang paling tepat?",
        options: ["الفاتورة من فضلك", "تفضل", "أبغى رز", "غير حار"],
        correctAnswer: "الفاتورة من فضلك",
        explanationId: "الفاتورة = struk/bon; من فضلك = tolong.",
        difficulty: "medium",
      },
      {
        id: "L2M4L1Q6",
        lessonId: "L2M4L1",
        questionType: "saudi_expression",
        promptId: "Pelayan bilang تمام setelah kamu pesan. Apa maksudnya?",
        arabicText: "تمام",
        transliteration: "Tamaam",
        options: ["Oke / baik", "Tidak ada", "Tunggu", "Maaf"],
        correctAnswer: "Oke / baik",
        explanationId: "تمام = konfirmasi 'oke/baik', sangat sering dipakai di Saudi.",
        difficulty: "easy",
      },
    ],
  },
  {
    id: "L2M5L1",
    appSlug: "arabic",
    level: "L2_DAILY",
    levelTitle: "Daily Life in Saudi",
    moduleId: "M5",
    moduleTitle: "Shopping & Market",
    lessonTitle: "Belanja di Toko atau Pasar",
    order: 7,
    scenario: "Di supermarket atau pasar tradisional. Kamu mau beli kebutuhan harian dan perlu tanya harga, ukuran, kuantitas.",
    targetSkill: "daily",
    arabicType: "mixed",
    explanationId:
      "Untuk belanja: tanya harga dengan كم؟, kuantitas dengan كم واحد؟, dan bayar dengan كم المجموع؟. Saudi suka tawar-menawar di pasar tradisional, tidak di supermarket.",
    saudiNote: "Di pasar tradisional, tawar-menawar adalah hal normal. Tapi di supermarket modern seperti Panda atau Lulu, harga fix.",
    vocabulary: [
      { arabic: "كم هذا؟", transliteration: "Kam haadzaa?", meaningId: "Berapa ini?", type: "fusha" },
      { arabic: "بكم؟", transliteration: "Bikam?", meaningId: "Berapa harganya? (Saudi pendek)", type: "saudi" },
      { arabic: "غالي", transliteration: "Ghaalii", meaningId: "Mahal", type: "fusha" },
      { arabic: "رخيص", transliteration: "Rakhiish", meaningId: "Murah", type: "fusha" },
      { arabic: "كبير", transliteration: "Kabiir", meaningId: "Besar", type: "fusha" },
      { arabic: "صغير", transliteration: "Saghiir", meaningId: "Kecil", type: "fusha" },
      { arabic: "أعطني", transliteration: "A‘thinii", meaningId: "Berikan saya", type: "fusha" },
      { arabic: "كاش", transliteration: "Kaash", meaningId: "Tunai", type: "saudi" },
      { arabic: "شبكة", transliteration: "Syabakah", meaningId: "Kartu / EDC (Saudi)", type: "saudi" },
    ],
    dialogue: [
      { speaker: "Pedagang", arabic: "تفضل، إيش تبغى؟", transliteration: "Tafaddhal, eesh tabghaa?", meaningId: "Silakan, kamu mau apa?", type: "saudi" },
      { speaker: "Kamu", arabic: "أبغى تمر. بكم الكيلو؟", transliteration: "Abghaa tamar. Bikam al-kiilu?", meaningId: "Saya mau kurma. Berapa harga kilonya?", type: "mixed" },
      { speaker: "Pedagang", arabic: "خمسين ريال.", transliteration: "Khamsiin riyaal.", meaningId: "50 riyal.", type: "fusha" },
      { speaker: "Kamu", arabic: "غالي. أربعين؟", transliteration: "Ghaalii. Arba‘iin?", meaningId: "Mahal. 40?", type: "fusha" },
      { speaker: "Pedagang", arabic: "خلاص، أربعين.", transliteration: "Khalaas, arba‘iin.", meaningId: "Oke, 40.", type: "saudi" },
    ],
    practicePrompts: [
      "Latih bertanya harga dengan 2 versi: كم هذا؟ dan بكم؟",
      "Buat 3 kalimat lengkap: pesan barang, tanya harga, tawar.",
      "Praktek bayar: 'pakai kartu' (شبكة) atau 'tunai' (كاش).",
    ],
    quiz: [
      {
        id: "L2M5L1Q1",
        lessonId: "L2M5L1",
        questionType: "vocabulary",
        promptId: "Versi Saudi pendek untuk 'berapa harganya' adalah?",
        options: ["بكم", "كيف حالك", "ما هذا", "أين"],
        correctAnswer: "بكم",
        explanationId: "بكم = berapa, dipakai sangat sering di pasar Saudi.",
        difficulty: "easy",
      },
      {
        id: "L2M5L1Q2",
        lessonId: "L2M5L1",
        questionType: "meaning",
        promptId: "غالي artinya?",
        arabicText: "غالي",
        transliteration: "Ghaalii",
        options: ["Mahal", "Murah", "Besar", "Kecil"],
        correctAnswer: "Mahal",
        explanationId: "غالي = mahal. Kebalikan dari رخيص.",
        difficulty: "easy",
      },
      {
        id: "L2M5L1Q3",
        lessonId: "L2M5L1",
        questionType: "saudi_expression",
        promptId: "Saat pedagang setuju menurunkan harga, dia bilang خلاص. Apa artinya?",
        arabicText: "خلاص",
        transliteration: "Khalaas",
        options: ["Oke / selesai / setuju", "Tidak", "Lebih mahal", "Saya tidak punya"],
        correctAnswer: "Oke / selesai / setuju",
        explanationId: "خلاص salah satu kata paling sering di Saudi: oke/setuju/selesai.",
        difficulty: "medium",
      },
      {
        id: "L2M5L1Q4",
        lessonId: "L2M5L1",
        questionType: "situation",
        promptId: "Kamu mau bayar dengan kartu. Mana yang paling natural?",
        options: ["شبكة", "كاش", "تمر", "رز"],
        correctAnswer: "شبكة",
        explanationId: "شبكة (syabakah) = EDC/kartu, kata khas Saudi.",
        difficulty: "medium",
      },
      {
        id: "L2M5L1Q5",
        lessonId: "L2M5L1",
        questionType: "vocabulary",
        promptId: "Mana yang berarti 'kecil'?",
        options: ["صغير", "كبير", "غالي", "رخيص"],
        correctAnswer: "صغير",
        explanationId: "صغير = kecil; كبير = besar.",
        difficulty: "easy",
      },
      {
        id: "L2M5L1Q6",
        lessonId: "L2M5L1",
        questionType: "meaning",
        promptId: "أعطني artinya?",
        arabicText: "أعطني",
        transliteration: "A‘thinii",
        options: ["Berikan saya", "Tunjukkan saya", "Tolong saya", "Tunggu saya"],
        correctAnswer: "Berikan saya",
        explanationId: "أعطني dipakai untuk minta barang/uang.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "L2M6L1",
    appSlug: "arabic",
    level: "L2_DAILY",
    levelTitle: "Daily Life in Saudi",
    moduleId: "M6",
    moduleTitle: "Transportation & Direction",
    lessonTitle: "Naik Taksi dan Tanya Arah",
    order: 8,
    scenario: "Kamu di luar hotel atau stasiun, mau naik taksi (atau Uber/Careem) ke tujuan. Perlu kasih alamat dan minta supir berhenti.",
    targetSkill: "travel",
    arabicType: "mixed",
    explanationId:
      "Pola pakai 'ke + tempat' dengan إلى. Tanya arah dengan فين/أين. Minta berhenti dengan قف هنا (qif hunaa). Saudi sering pakai Uber/Careem app — pakai bahasa Inggris pun bisa.",
    saudiNote: "فين adalah versi Saudi dari أين (di mana). Hampir semua sopir Saudi paham bahasa Inggris dasar, tapi sopir dari negara lain mungkin hanya bisa Arab.",
    vocabulary: [
      { arabic: "إلى الفندق", transliteration: "Ilaa al-funduq", meaningId: "Ke hotel", type: "fusha" },
      { arabic: "إلى الحرم", transliteration: "Ilaa al-haram", meaningId: "Ke Masjid Haram", type: "fusha" },
      { arabic: "فين؟", transliteration: "Feen?", meaningId: "Di mana? (Saudi)", type: "saudi" },
      { arabic: "أين؟", transliteration: "Aina?", meaningId: "Di mana? (Fusha)", type: "fusha" },
      { arabic: "قف هنا", transliteration: "Qif hunaa", meaningId: "Berhenti di sini", type: "fusha" },
      { arabic: "على اليمين", transliteration: "‘ala al-yamiin", meaningId: "Di kanan", type: "fusha" },
      { arabic: "على اليسار", transliteration: "‘ala al-yasaar", meaningId: "Di kiri", type: "fusha" },
      { arabic: "على طول", transliteration: "‘alaa thuul", meaningId: "Lurus terus (Saudi)", type: "saudi" },
      { arabic: "بعيد", transliteration: "Ba‘iid", meaningId: "Jauh", type: "fusha" },
      { arabic: "قريب", transliteration: "Qariib", meaningId: "Dekat", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Sopir", arabic: "فين تبغى؟", transliteration: "Feen tabghaa?", meaningId: "Mau ke mana?", type: "saudi" },
      { speaker: "Kamu", arabic: "إلى فندق هيلتون من فضلك.", transliteration: "Ilaa funduq Hilton min fadhlik.", meaningId: "Ke Hotel Hilton tolong.", type: "fusha" },
      { speaker: "Sopir", arabic: "تمام، على طول.", transliteration: "Tamaam, ‘alaa thuul.", meaningId: "Oke, lurus terus.", type: "saudi" },
      { speaker: "Kamu", arabic: "قف هنا من فضلك.", transliteration: "Qif hunaa min fadhlik.", meaningId: "Tolong berhenti di sini.", type: "fusha" },
    ],
    practicePrompts: [
      "Tulis 3 tujuan favorit: hotel, masjid, tempat kerja.",
      "Latih kalimat 'tolong berhenti di sini' sampai natural.",
      "Praktek tanya arah dengan فين dan أين.",
    ],
    quiz: [
      {
        id: "L2M6L1Q1",
        lessonId: "L2M6L1",
        questionType: "saudi_expression",
        promptId: "Versi Saudi untuk 'di mana' adalah?",
        options: ["فين", "أين", "إلى", "كم"],
        correctAnswer: "فين",
        explanationId: "فين (feen) adalah cara Saudi yang paling sering dipakai untuk 'di mana'.",
        difficulty: "easy",
      },
      {
        id: "L2M6L1Q2",
        lessonId: "L2M6L1",
        questionType: "situation",
        promptId: "Kamu mau minta sopir berhenti di tempat sekarang. Apa yang kamu katakan?",
        options: ["قف هنا من فضلك", "إلى الفندق", "على اليمين", "بعيد"],
        correctAnswer: "قف هنا من فضلك",
        explanationId: "قف هنا = berhenti di sini; من فضلك = tolong.",
        difficulty: "easy",
      },
      {
        id: "L2M6L1Q3",
        lessonId: "L2M6L1",
        questionType: "meaning",
        promptId: "Sopir bilang على طول. Artinya apa?",
        arabicText: "على طول",
        transliteration: "‘alaa thuul",
        options: ["Lurus terus", "Belok kiri", "Belok kanan", "Putar balik"],
        correctAnswer: "Lurus terus",
        explanationId: "على طول adalah cara Saudi untuk 'lurus terus'.",
        difficulty: "medium",
      },
      {
        id: "L2M6L1Q4",
        lessonId: "L2M6L1",
        questionType: "vocabulary",
        promptId: "على اليمين artinya?",
        arabicText: "على اليمين",
        options: ["Di kanan", "Di kiri", "Lurus", "Belakang"],
        correctAnswer: "Di kanan",
        explanationId: "اليمين = kanan; اليسار = kiri.",
        difficulty: "easy",
      },
      {
        id: "L2M6L1Q5",
        lessonId: "L2M6L1",
        questionType: "vocabulary",
        promptId: "Mana arti dari قريب?",
        arabicText: "قريب",
        transliteration: "Qariib",
        options: ["Dekat", "Jauh", "Kiri", "Cepat"],
        correctAnswer: "Dekat",
        explanationId: "قريب = dekat; lawannya بعيد (jauh).",
        difficulty: "easy",
      },
      {
        id: "L2M6L1Q6",
        lessonId: "L2M6L1",
        questionType: "situation",
        promptId: "Sopir tanya فين تبغى؟. Jawaban yang benar untuk 'ke hotel'?",
        arabicText: "فين تبغى؟",
        options: ["إلى الفندق", "أنا متأخر", "كم السعر", "غير حار"],
        correctAnswer: "إلى الفندق",
        explanationId: "إلى = ke; الفندق = hotel.",
        difficulty: "medium",
      },
    ],
  },
];
