import type { ArabicLesson } from "../types";

export const level3Lessons: ArabicLesson[] = [
  {
    id: "L3M7L1",
    appSlug: "arabic",
    level: "L3_WORK",
    levelTitle: "Work Arabic for Saudi",
    moduleId: "M7",
    moduleTitle: "Workplace Introduction",
    lessonTitle: "Perkenalan di Tempat Kerja",
    order: 9,
    scenario: "Hari pertama kerja. Atasan dan kolega ingin tahu siapa kamu, dari mana, dan kerjamu apa.",
    targetSkill: "work",
    arabicType: "fusha",
    explanationId:
      "Perkenalan kerja butuh sopan, pakai Fusha lebih aman daripada Saudi casual. Kamu sebut nama, asal, dan posisi (مهنة/وظيفة). Kalau atasan ngomong, panggil dia يا أستاذ untuk pria atau يا أستاذة untuk perempuan.",
    saudiNote: "Panggilan أستاذ (ustaadz) artinya 'tuan' atau 'pak guru', dipakai sangat formal untuk hormat ke atasan/rekan senior.",
    vocabulary: [
      { arabic: "أنا موظف جديد", transliteration: "Anaa muwazhzhaf jadiid", meaningId: "Saya karyawan baru (laki)", type: "fusha" },
      { arabic: "أنا موظفة جديدة", transliteration: "Anaa muwazhzhafah jadiidah", meaningId: "Saya karyawan baru (perempuan)", type: "fusha" },
      { arabic: "وظيفتي", transliteration: "Wazhiifatii", meaningId: "Pekerjaan saya", type: "fusha" },
      { arabic: "المدير", transliteration: "Al-mudiir", meaningId: "Manajer", type: "fusha" },
      { arabic: "زميل", transliteration: "Zamiil", meaningId: "Kolega (laki)", type: "fusha" },
      { arabic: "زميلة", transliteration: "Zamiilah", meaningId: "Kolega (perempuan)", type: "fusha" },
      { arabic: "يا أستاذ", transliteration: "Yaa ustaadz", meaningId: "Pak (sopan, untuk laki-laki)", type: "fusha" },
      { arabic: "يا أستاذة", transliteration: "Yaa ustaadzah", meaningId: "Bu (sopan, untuk perempuan)", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Atasan", arabic: "أهلاً، أنت موظف جديد؟", transliteration: "Ahlan, anta muwazhzhaf jadiid?", meaningId: "Halo, kamu karyawan baru?", type: "fusha" },
      { speaker: "Kamu", arabic: "نعم يا أستاذ، اسمي بُدي من إندونيسيا.", transliteration: "Na‘am yaa ustaadz, ismii Budi min Induuniisiyaa.", meaningId: "Ya pak, nama saya Budi dari Indonesia.", type: "fusha" },
      { speaker: "Atasan", arabic: "تشرفنا. وظيفتك كمشغل آلة.", transliteration: "Tasyarrafnaa. Wazhiifatuk ka-musyaghghil aalah.", meaningId: "Senang berkenalan. Pekerjaanmu sebagai operator mesin.", type: "fusha" },
      { speaker: "Kamu", arabic: "حاضر، شكراً.", transliteration: "Haadhir, syukran.", meaningId: "Siap, terima kasih.", type: "fusha" },
    ],
    practicePrompts: [
      "Tulis 3 kalimat perkenalan kerja: nama, asal, posisi.",
      "Latih panggilan sopan: يا أستاذ atau يا أستاذة.",
      "Buat respons singkat saat atasan menjelaskan tugas: 'حاضر' (siap).",
    ],
    quiz: [
      {
        id: "L3M7L1Q1",
        lessonId: "L3M7L1",
        questionType: "work_instruction",
        promptId: "Bagaimana cara hormat memanggil atasan laki-laki?",
        options: ["يا أستاذ", "يا أخت", "يا صديق", "يا أبي"],
        correctAnswer: "يا أستاذ",
        explanationId: "يا أستاذ adalah panggilan hormat standar untuk pria di tempat kerja.",
        difficulty: "easy",
      },
      {
        id: "L3M7L1Q2",
        lessonId: "L3M7L1",
        questionType: "situation",
        promptId: "Atasan menjelaskan tugas baru. Respons singkat sopan yang paling tepat?",
        options: ["حاضر", "لا أفهم", "أنا متأخر", "كم السعر"],
        correctAnswer: "حاضر",
        explanationId: "حاضر = 'siap', cara sopan menyetujui instruksi.",
        difficulty: "medium",
      },
      {
        id: "L3M7L1Q3",
        lessonId: "L3M7L1",
        questionType: "meaning",
        promptId: "Apa arti المدير?",
        arabicText: "المدير",
        transliteration: "Al-mudiir",
        options: ["Manajer", "Kolega", "Pelanggan", "Karyawan baru"],
        correctAnswer: "Manajer",
        explanationId: "المدير = manajer/direktur.",
        difficulty: "easy",
      },
      {
        id: "L3M7L1Q4",
        lessonId: "L3M7L1",
        questionType: "vocabulary",
        promptId: "زميل artinya?",
        arabicText: "زميل",
        transliteration: "Zamiil",
        options: ["Kolega laki-laki", "Atasan", "Tamu", "Saudara"],
        correctAnswer: "Kolega laki-laki",
        explanationId: "زميل = kolega laki; زميلة = kolega perempuan.",
        difficulty: "easy",
      },
      {
        id: "L3M7L1Q5",
        lessonId: "L3M7L1",
        questionType: "work_instruction",
        promptId: "Saat memperkenalkan diri sebagai karyawan baru perempuan, mana yang tepat?",
        options: ["أنا موظفة جديدة", "أنا موظف جديد", "أنا مدير", "أنا أستاذ"],
        correctAnswer: "أنا موظفة جديدة",
        explanationId: "Untuk perempuan: موظفة جديدة (akhiran ة).",
        difficulty: "medium",
      },
      {
        id: "L3M7L1Q6",
        lessonId: "L3M7L1",
        questionType: "meaning",
        promptId: "وظيفتي artinya?",
        arabicText: "وظيفتي",
        transliteration: "Wazhiifatii",
        options: ["Pekerjaan saya", "Nama saya", "Tempat saya", "Hari saya"],
        correctAnswer: "Pekerjaan saya",
        explanationId: "وظيفة = pekerjaan; -ي = saya. وظيفتي = pekerjaan saya.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "L3M8L1",
    appSlug: "arabic",
    level: "L3_WORK",
    levelTitle: "Work Arabic for Saudi",
    moduleId: "M8",
    moduleTitle: "Understanding Work Instructions",
    lessonTitle: "Instruksi Kerja Dasar",
    order: 10,
    scenario: "Atasan atau kepala shift memberi instruksi. Kamu harus mengerti perintah pendek seperti datang, pergi, tunggu, bersihkan, buka, tutup.",
    targetSkill: "work",
    arabicType: "fusha",
    explanationId:
      "Kata perintah Arab pendek dan langsung. Hafalkan minimal 10 kata kerja perintah ini, mereka 80% instruksi kerja sehari-hari.",
    saudiNote: "Kalau atasan ngomong cepat dan kamu belum paham, jangan diam — bilang لم أفهم (saya belum paham) supaya dia ulangi.",
    vocabulary: [
      { arabic: "تعال", transliteration: "Ta‘aal", meaningId: "Datang ke sini", type: "fusha" },
      { arabic: "اذهب", transliteration: "Idzhab", meaningId: "Pergi", type: "fusha" },
      { arabic: "انتظر", transliteration: "Intazhir", meaningId: "Tunggu", type: "fusha" },
      { arabic: "افتح", transliteration: "Iftah", meaningId: "Buka", type: "fusha" },
      { arabic: "أغلق", transliteration: "Aghliq", meaningId: "Tutup", type: "fusha" },
      { arabic: "نظف", transliteration: "Nazhzhif", meaningId: "Bersihkan", type: "fusha" },
      { arabic: "لا تدخل", transliteration: "Laa tadkhul", meaningId: "Jangan masuk", type: "fusha" },
      { arabic: "لا تلمس", transliteration: "Laa talmas", meaningId: "Jangan sentuh", type: "fusha" },
      { arabic: "فهمت", transliteration: "Fahimt", meaningId: "Saya mengerti", type: "fusha" },
      { arabic: "لم أفهم", transliteration: "Lam afham", meaningId: "Saya belum mengerti", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Atasan", arabic: "تعال هنا، نظف هذه الغرفة.", transliteration: "Ta‘aal hunaa, nazhzhif haadzihil ghurfah.", meaningId: "Ke sini, bersihkan ruangan ini.", type: "fusha" },
      { speaker: "Kamu", arabic: "حاضر، فهمت.", transliteration: "Haadhir, fahimt.", meaningId: "Siap, saya mengerti.", type: "fusha" },
      { speaker: "Atasan", arabic: "بعدها، أغلق الباب.", transliteration: "Ba‘dahaa, aghliq al-baab.", meaningId: "Setelah itu, tutup pintunya.", type: "fusha" },
      { speaker: "Kamu", arabic: "تمام.", transliteration: "Tamaam.", meaningId: "Oke.", type: "saudi" },
    ],
    practicePrompts: [
      "Hafal 10 kata perintah ini, sebut sambil bayangkan situasi nyata.",
      "Latih dua respons: فهمت dan لم أفهم.",
      "Buat 3 kalimat: 'tunggu di sini', 'buka pintu', 'bersihkan meja'.",
    ],
    quiz: [
      {
        id: "L3M8L1Q1",
        lessonId: "L3M8L1",
        questionType: "work_instruction",
        promptId: "Jika supervisor berkata نظف هذه الغرفة, apa yang harus kamu lakukan?",
        arabicText: "نظف هذه الغرفة",
        transliteration: "Nazhzhif haadzihil ghurfah",
        options: ["Bersihkan ruangan ini", "Tutup pintu", "Buka jendela", "Pergi dari sini"],
        correctAnswer: "Bersihkan ruangan ini",
        explanationId: "نظف = bersihkan; هذه الغرفة = ruangan ini.",
        difficulty: "medium",
      },
      {
        id: "L3M8L1Q2",
        lessonId: "L3M8L1",
        questionType: "work_instruction",
        promptId: "Atasan bilang لا تدخل. Artinya?",
        arabicText: "لا تدخل",
        transliteration: "Laa tadkhul",
        options: ["Jangan masuk", "Masuk sekarang", "Tunggu di luar", "Tutup pintu"],
        correctAnswer: "Jangan masuk",
        explanationId: "لا = jangan; تدخل = masuk.",
        difficulty: "easy",
      },
      {
        id: "L3M8L1Q3",
        lessonId: "L3M8L1",
        questionType: "situation",
        promptId: "Kamu tidak paham yang dikatakan atasan. Apa yang paling tepat kamu bilang?",
        options: ["لم أفهم", "فهمت", "حاضر", "تمام"],
        correctAnswer: "لم أفهم",
        explanationId: "لم أفهم = saya belum paham, dipakai sopan untuk minta diulang.",
        difficulty: "medium",
      },
      {
        id: "L3M8L1Q4",
        lessonId: "L3M8L1",
        questionType: "vocabulary",
        promptId: "افتح artinya?",
        arabicText: "افتح",
        transliteration: "Iftah",
        options: ["Buka", "Tutup", "Tunggu", "Bersihkan"],
        correctAnswer: "Buka",
        explanationId: "افتح = buka. Kebalikan dari أغلق (tutup).",
        difficulty: "easy",
      },
      {
        id: "L3M8L1Q5",
        lessonId: "L3M8L1",
        questionType: "work_instruction",
        promptId: "Atasan bilang انتظر. Apa artinya?",
        arabicText: "انتظر",
        transliteration: "Intazhir",
        options: ["Tunggu", "Datang", "Pergi", "Lihat"],
        correctAnswer: "Tunggu",
        explanationId: "انتظر = tunggu. Sering muncul: انتظر هنا (tunggu di sini).",
        difficulty: "easy",
      },
      {
        id: "L3M8L1Q6",
        lessonId: "L3M8L1",
        questionType: "situation",
        promptId: "Kamu paham instruksi atasan. Respons pendek paling tepat?",
        options: ["فهمت", "لم أفهم", "كم السعر", "أنا متأخر"],
        correctAnswer: "فهمت",
        explanationId: "فهمت = saya mengerti.",
        difficulty: "easy",
      },
    ],
  },
  {
    id: "L3M9L1",
    appSlug: "arabic",
    level: "L3_WORK",
    levelTitle: "Work Arabic for Saudi",
    moduleId: "M9",
    moduleTitle: "Asking Help & Reporting Problem",
    lessonTitle: "Minta Bantuan dan Lapor Masalah",
    order: 11,
    scenario: "Kamu butuh bantuan: ada alat rusak, kamu sakit, atau kamu terlambat. Wajib bisa komunikasi singkat dan sopan.",
    targetSkill: "work",
    arabicType: "fusha",
    explanationId:
      "Untuk minta bantuan: ساعدني (sa‘idnii). Lapor masalah: pakai pola هذا + masalah. Untuk minta maaf: آسف (laki) / آسفة (perempuan).",
    saudiNote: "Kejujuran sangat dihargai di Saudi. Lebih baik lapor sakit dengan jelas daripada kerja setengah hati.",
    vocabulary: [
      { arabic: "ساعدني", transliteration: "Saa‘idnii", meaningId: "Tolong saya", type: "fusha" },
      { arabic: "أحتاج مساعدة", transliteration: "Ahtaaju musaa‘adah", meaningId: "Saya butuh bantuan", type: "fusha" },
      { arabic: "الآلة معطلة", transliteration: "Al-aalah mu‘atthalah", meaningId: "Mesinnya rusak", type: "fusha" },
      { arabic: "أنا مريض", transliteration: "Anaa mariidh", meaningId: "Saya sakit (laki)", type: "fusha" },
      { arabic: "أنا مريضة", transliteration: "Anaa mariidhah", meaningId: "Saya sakit (perempuan)", type: "fusha" },
      { arabic: "آسف على التأخير", transliteration: "Aasif ‘alaa at-ta’khiir", meaningId: "Maaf atas keterlambatan (laki)", type: "fusha" },
      { arabic: "آسفة على التأخير", transliteration: "Aasifah ‘alaa at-ta’khiir", meaningId: "Maaf atas keterlambatan (perempuan)", type: "fusha" },
      { arabic: "لا يعمل", transliteration: "Laa ya‘mal", meaningId: "Tidak berfungsi", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Kamu", arabic: "يا أستاذ، الآلة معطلة.", transliteration: "Yaa ustaadz, al-aalah mu‘atthalah.", meaningId: "Pak, mesinnya rusak.", type: "fusha" },
      { speaker: "Atasan", arabic: "إيش المشكلة؟", transliteration: "Eesh al-musykilah?", meaningId: "Apa masalahnya?", type: "saudi" },
      { speaker: "Kamu", arabic: "لا تعمل. أحتاج مساعدة.", transliteration: "Laa ta‘mal. Ahtaaju musaa‘adah.", meaningId: "Tidak berfungsi. Saya butuh bantuan.", type: "fusha" },
      { speaker: "Atasan", arabic: "تمام، انتظر، سأرسل الفني.", transliteration: "Tamaam, intazhir, sa-ursil al-fannii.", meaningId: "Oke, tunggu, saya kirim teknisi.", type: "fusha" },
    ],
    practicePrompts: [
      "Tulis 3 versi minta bantuan singkat di tempat kerja.",
      "Latih kalimat 'maaf saya terlambat' versi laki dan perempuan.",
      "Buat skenario: 'mesin rusak' → lapor → tunggu teknisi.",
    ],
    quiz: [
      {
        id: "L3M9L1Q1",
        lessonId: "L3M9L1",
        questionType: "situation",
        promptId: "Mesinmu rusak. Bagaimana melapor singkat dan jelas?",
        options: ["الآلة معطلة", "أنا متأخر", "كم السعر", "أبغى قهوة"],
        correctAnswer: "الآلة معطلة",
        explanationId: "الآلة = mesin; معطلة = rusak/tidak berfungsi.",
        difficulty: "medium",
      },
      {
        id: "L3M9L1Q2",
        lessonId: "L3M9L1",
        questionType: "situation",
        promptId: "Kamu sakit dan tidak bisa kerja. Bagaimana bilang ke atasan (laki-laki)?",
        options: ["أنا مريض", "أنا مريضة", "أنا متأخر", "أنا موظف جديد"],
        correctAnswer: "أنا مريض",
        explanationId: "Untuk laki-laki: أنا مريض. Perempuan: أنا مريضة.",
        difficulty: "easy",
      },
      {
        id: "L3M9L1Q3",
        lessonId: "L3M9L1",
        questionType: "meaning",
        promptId: "أحتاج مساعدة artinya?",
        arabicText: "أحتاج مساعدة",
        transliteration: "Ahtaaju musaa‘adah",
        options: ["Saya butuh bantuan", "Saya sakit", "Saya mengerti", "Saya pergi"],
        correctAnswer: "Saya butuh bantuan",
        explanationId: "أحتاج = saya butuh; مساعدة = bantuan.",
        difficulty: "easy",
      },
      {
        id: "L3M9L1Q4",
        lessonId: "L3M9L1",
        questionType: "situation",
        promptId: "Kamu terlambat 30 menit (laki-laki). Permintaan maaf yang paling tepat?",
        options: ["آسف على التأخير", "تشرفنا", "كم السعر", "حاضر"],
        correctAnswer: "آسف على التأخير",
        explanationId: "آسف على التأخير = maaf atas keterlambatan.",
        difficulty: "medium",
      },
      {
        id: "L3M9L1Q5",
        lessonId: "L3M9L1",
        questionType: "meaning",
        promptId: "Atasan tanya إيش المشكلة؟. Artinya?",
        arabicText: "إيش المشكلة؟",
        transliteration: "Eesh al-musykilah?",
        options: ["Apa masalahnya?", "Apa namamu?", "Berapa harga?", "Di mana kamu?"],
        correctAnswer: "Apa masalahnya?",
        explanationId: "إيش = apa (Saudi); المشكلة = masalah.",
        difficulty: "medium",
      },
      {
        id: "L3M9L1Q6",
        lessonId: "L3M9L1",
        questionType: "vocabulary",
        promptId: "Mana arti dari لا يعمل?",
        arabicText: "لا يعمل",
        transliteration: "Laa ya‘mal",
        options: ["Tidak berfungsi", "Sedang bekerja", "Selesai kerja", "Mau kerja"],
        correctAnswer: "Tidak berfungsi",
        explanationId: "لا يعمل dipakai untuk alat/sistem yang mati atau rusak.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "L3M10L1",
    appSlug: "arabic",
    level: "L3_WORK",
    levelTitle: "Work Arabic for Saudi",
    moduleId: "M10",
    moduleTitle: "Work Safety & Rules",
    lessonTitle: "Keselamatan dan Aturan Kerja",
    order: 12,
    scenario: "Di pabrik, dapur, atau lokasi konstruksi. Kamu perlu mengerti tanda bahaya, alat pengaman, dan aturan dasar safety.",
    targetSkill: "work",
    arabicType: "fusha",
    explanationId:
      "Tanda peringatan biasanya pakai kata خطر (bahaya) atau ممنوع (dilarang). Alat pengaman: خوذة (helm), قفازات (sarung tangan), حذاء أمان (sepatu safety).",
    saudiNote: "Aturan keselamatan kerja di Saudi sangat ketat untuk pekerja asing. Patuhi semua tanda, jangan abaikan.",
    vocabulary: [
      { arabic: "خطر", transliteration: "Khathar", meaningId: "Bahaya", type: "fusha" },
      { arabic: "ممنوع", transliteration: "Mamnuu‘", meaningId: "Dilarang", type: "fusha" },
      { arabic: "خوذة", transliteration: "Khuudzah", meaningId: "Helm", type: "fusha" },
      { arabic: "قفازات", transliteration: "Quffaazaat", meaningId: "Sarung tangan", type: "fusha" },
      { arabic: "حذاء أمان", transliteration: "Hidzaa’ amaan", meaningId: "Sepatu safety", type: "fusha" },
      { arabic: "نظارة أمان", transliteration: "Nazhzhaarat amaan", meaningId: "Kacamata safety", type: "fusha" },
      { arabic: "حادث", transliteration: "Haadits", meaningId: "Kecelakaan", type: "fusha" },
      { arabic: "إسعاف", transliteration: "Is‘aaf", meaningId: "Ambulans / pertolongan", type: "fusha" },
      { arabic: "ممنوع التدخين", transliteration: "Mamnuu‘ at-tadkhiin", meaningId: "Dilarang merokok", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Supervisor", arabic: "البس الخوذة، ممنوع بدونها.", transliteration: "Albas al-khuudzah, mamnuu‘ biduunihaa.", meaningId: "Pakai helm, dilarang tanpa helm.", type: "fusha" },
      { speaker: "Kamu", arabic: "حاضر، فهمت.", transliteration: "Haadhir, fahimt.", meaningId: "Siap, mengerti.", type: "fusha" },
      { speaker: "Supervisor", arabic: "هذه المنطقة خطر، لا تدخل.", transliteration: "Haadzihi al-manthaqah khathar, laa tadkhul.", meaningId: "Area ini bahaya, jangan masuk.", type: "fusha" },
    ],
    practicePrompts: [
      "Hafal 5 alat keselamatan: خوذة، قفازات، حذاء أمان، نظارة أمان.",
      "Tulis 2 tanda peringatan yang sering muncul di lokasi kerja.",
      "Latih kalimat: 'saya pakai helm' dan 'di sini bahaya, jangan masuk'.",
    ],
    quiz: [
      {
        id: "L3M10L1Q1",
        lessonId: "L3M10L1",
        questionType: "work_instruction",
        promptId: "Tanda خطر di lokasi kerja artinya?",
        arabicText: "خطر",
        transliteration: "Khathar",
        options: ["Bahaya", "Buka", "Pintu masuk", "Bersihkan"],
        correctAnswer: "Bahaya",
        explanationId: "خطر = bahaya. Jangan masuk atau dekati area ini tanpa izin.",
        difficulty: "easy",
      },
      {
        id: "L3M10L1Q2",
        lessonId: "L3M10L1",
        questionType: "vocabulary",
        promptId: "خوذة artinya?",
        arabicText: "خوذة",
        transliteration: "Khuudzah",
        options: ["Helm", "Sarung tangan", "Kacamata", "Sepatu"],
        correctAnswer: "Helm",
        explanationId: "خوذة = helm safety. Wajib di area konstruksi.",
        difficulty: "easy",
      },
      {
        id: "L3M10L1Q3",
        lessonId: "L3M10L1",
        questionType: "work_instruction",
        promptId: "Tanda ممنوع التدخين artinya?",
        arabicText: "ممنوع التدخين",
        transliteration: "Mamnuu‘ at-tadkhiin",
        options: ["Dilarang merokok", "Dilarang masuk", "Dilarang foto", "Dilarang bicara"],
        correctAnswer: "Dilarang merokok",
        explanationId: "ممنوع = dilarang; التدخين = merokok.",
        difficulty: "easy",
      },
      {
        id: "L3M10L1Q4",
        lessonId: "L3M10L1",
        questionType: "situation",
        promptId: "Ada kecelakaan kerja. Kamu mau minta ambulans. Kata kunci yang harus kamu sebut?",
        options: ["إسعاف", "خوذة", "تمر", "قهوة"],
        correctAnswer: "إسعاف",
        explanationId: "إسعاف = ambulans / pertolongan pertama.",
        difficulty: "medium",
      },
      {
        id: "L3M10L1Q5",
        lessonId: "L3M10L1",
        questionType: "vocabulary",
        promptId: "قفازات artinya?",
        arabicText: "قفازات",
        transliteration: "Quffaazaat",
        options: ["Sarung tangan", "Sepatu", "Topi", "Masker"],
        correctAnswer: "Sarung tangan",
        explanationId: "قفازات = sarung tangan safety.",
        difficulty: "medium",
      },
      {
        id: "L3M10L1Q6",
        lessonId: "L3M10L1",
        questionType: "work_instruction",
        promptId: "Supervisor bilang البس الخوذة. Apa yang harus kamu lakukan?",
        arabicText: "البس الخوذة",
        transliteration: "Albas al-khuudzah",
        options: ["Pakai helm", "Lepas helm", "Bersihkan helm", "Beli helm"],
        correctAnswer: "Pakai helm",
        explanationId: "البس = pakai; الخوذة = helm.",
        difficulty: "medium",
      },
    ],
  },
];
