import type { ArabicLesson } from "../types";

export const level4Lessons: ArabicLesson[] = [
  {
    id: "L4M11L1",
    appSlug: "arabic",
    level: "L4_UMRAH",
    levelTitle: "Umrah Arabic",
    moduleId: "M11",
    moduleTitle: "Airport & Immigration",
    lessonTitle: "Bandara dan Imigrasi",
    order: 13,
    scenario: "Kamu baru sampai di Jeddah atau Madinah. Petugas imigrasi memeriksa paspor, visa, dan barang. Kamu wajib paham pertanyaan dasar.",
    targetSkill: "umrah",
    arabicType: "fusha",
    explanationId:
      "Imigrasi pakai bahasa formal. Pertanyaan umum: tujuan, durasi, alamat tujuan. Selalu siapkan dokumen di tangan dan respons singkat.",
    saudiNote: "Petugas imigrasi Saudi cukup tegas tapi membantu kalau kamu menjawab dengan tenang dan jelas. Senyum sopan membantu.",
    vocabulary: [
      { arabic: "جواز السفر", transliteration: "Jawaaz as-safar", meaningId: "Paspor", type: "fusha" },
      { arabic: "تأشيرة", transliteration: "Ta’syiirah", meaningId: "Visa", type: "fusha" },
      { arabic: "عمرة", transliteration: "‘Umrah", meaningId: "Umrah", type: "fusha" },
      { arabic: "حقيبة", transliteration: "Haqiibah", meaningId: "Tas / koper", type: "fusha" },
      { arabic: "الحقائب", transliteration: "Al-haqaa’ib", meaningId: "Bagasi", type: "fusha" },
      { arabic: "بوابة", transliteration: "Bawwaabah", meaningId: "Gate / pintu", type: "fusha" },
      { arabic: "أين البوابة؟", transliteration: "Aina al-bawwaabah?", meaningId: "Di mana gate?", type: "fusha" },
      { arabic: "للعمرة", transliteration: "Lil-‘umrah", meaningId: "Untuk umrah", type: "fusha" },
      { arabic: "أسبوع", transliteration: "Usbuu‘", meaningId: "Seminggu", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Petugas", arabic: "جواز السفر من فضلك.", transliteration: "Jawaaz as-safar min fadhlik.", meaningId: "Paspor tolong.", type: "fusha" },
      { speaker: "Kamu", arabic: "تفضل.", transliteration: "Tafaddhal.", meaningId: "Silakan.", type: "fusha" },
      { speaker: "Petugas", arabic: "ما الغرض من الزيارة؟", transliteration: "Maa al-gharadhu mina az-ziyaarah?", meaningId: "Apa tujuan kunjungan?", type: "fusha" },
      { speaker: "Kamu", arabic: "للعمرة، أسبوعاً.", transliteration: "Lil-‘umrah, usbuu‘an.", meaningId: "Untuk umrah, seminggu.", type: "fusha" },
      { speaker: "Petugas", arabic: "أهلاً وسهلاً، تفضل.", transliteration: "Ahlan wa sahlan, tafaddhal.", meaningId: "Selamat datang, silakan.", type: "fusha" },
    ],
    practicePrompts: [
      "Latih jawaban 'untuk umrah seminggu' (للعمرة أسبوعاً).",
      "Hafal 5 kata bandara: paspor, visa, gate, bagasi, koper.",
      "Tulis 2 tanya dasar di bandara: 'di mana gate' dan 'di mana bagasi'.",
    ],
    quiz: [
      {
        id: "L4M11L1Q1",
        lessonId: "L4M11L1",
        questionType: "umrah",
        promptId: "Petugas imigrasi minta جواز السفر. Apa artinya?",
        arabicText: "جواز السفر",
        transliteration: "Jawaaz as-safar",
        options: ["Paspor", "Visa", "Tiket", "Tas"],
        correctAnswer: "Paspor",
        explanationId: "جواز السفر = paspor.",
        difficulty: "easy",
      },
      {
        id: "L4M11L1Q2",
        lessonId: "L4M11L1",
        questionType: "situation",
        promptId: "Petugas tanya ما الغرض من الزيارة؟. Untuk jamaah umrah, jawaban yang paling tepat?",
        options: ["للعمرة", "للعمل", "للسياحة", "للدراسة"],
        correctAnswer: "للعمرة",
        explanationId: "للعمرة = untuk umrah.",
        difficulty: "medium",
      },
      {
        id: "L4M11L1Q3",
        lessonId: "L4M11L1",
        questionType: "vocabulary",
        promptId: "Mana arti dari تأشيرة?",
        arabicText: "تأشيرة",
        transliteration: "Ta’syiirah",
        options: ["Visa", "Paspor", "Tiket", "Bagasi"],
        correctAnswer: "Visa",
        explanationId: "تأشيرة = visa.",
        difficulty: "easy",
      },
      {
        id: "L4M11L1Q4",
        lessonId: "L4M11L1",
        questionType: "umrah",
        promptId: "Kamu mau tanya 'di mana gate?'. Mana yang paling tepat?",
        options: ["أين البوابة؟", "كم السعر؟", "ما اسمك؟", "ساعدني"],
        correctAnswer: "أين البوابة؟",
        explanationId: "أين = di mana; البوابة = gate.",
        difficulty: "easy",
      },
      {
        id: "L4M11L1Q5",
        lessonId: "L4M11L1",
        questionType: "vocabulary",
        promptId: "الحقائب artinya?",
        arabicText: "الحقائب",
        transliteration: "Al-haqaa’ib",
        options: ["Bagasi", "Paspor", "Gate", "Tiket"],
        correctAnswer: "Bagasi",
        explanationId: "الحقائب = bagasi (jamak dari haqiibah).",
        difficulty: "medium",
      },
      {
        id: "L4M11L1Q6",
        lessonId: "L4M11L1",
        questionType: "situation",
        promptId: "Petugas akhirnya mempersilakan kamu lewat dengan kata أهلاً وسهلاً. Artinya?",
        arabicText: "أهلاً وسهلاً",
        options: ["Selamat datang", "Tunggu", "Tolak", "Cek lagi"],
        correctAnswer: "Selamat datang",
        explanationId: "أهلاً وسهلاً adalah sapaan selamat datang.",
        difficulty: "easy",
      },
    ],
  },
  {
    id: "L4M12L1",
    appSlug: "arabic",
    level: "L4_UMRAH",
    levelTitle: "Umrah Arabic",
    moduleId: "M12",
    moduleTitle: "Hotel & Accommodation",
    lessonTitle: "Check-in di Hotel",
    order: 14,
    scenario: "Tiba di hotel dekat Masjidil Haram atau Masjid Nabawi. Kamu perlu check-in, minta kunci, dan tanya fasilitas.",
    targetSkill: "umrah",
    arabicType: "mixed",
    explanationId:
      "Resepsionis hotel umumnya paham bahasa Inggris dasar dan Arab formal. Pakai pola عندي حجز untuk 'saya ada reservasi'. Minta kunci dengan مفتاح من فضلك.",
    saudiNote: "Banyak hotel di Mekah dan Madinah memiliki staf Indonesia/Asia, terutama saat musim umrah. Tapi tetap belajar Arab dasarnya supaya mandiri.",
    vocabulary: [
      { arabic: "فندق", transliteration: "Funduq", meaningId: "Hotel", type: "fusha" },
      { arabic: "غرفة", transliteration: "Ghurfah", meaningId: "Kamar", type: "fusha" },
      { arabic: "عندي حجز", transliteration: "‘Indii hajz", meaningId: "Saya ada reservasi", type: "fusha" },
      { arabic: "مفتاح", transliteration: "Miftaah", meaningId: "Kunci", type: "fusha" },
      { arabic: "مفتاح الغرفة", transliteration: "Miftaah al-ghurfah", meaningId: "Kunci kamar", type: "fusha" },
      { arabic: "واي فاي", transliteration: "Waay-faay", meaningId: "WiFi", type: "mixed" },
      { arabic: "كلمة المرور", transliteration: "Kalimat al-muruur", meaningId: "Password", type: "fusha" },
      { arabic: "تنظيف", transliteration: "Tanzhiif", meaningId: "Pembersihan / housekeeping", type: "fusha" },
      { arabic: "الإفطار", transliteration: "Al-ifthaar", meaningId: "Sarapan", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Resepsionis", arabic: "أهلاً، كيف أساعدك؟", transliteration: "Ahlan, kaifa usaa‘iduk?", meaningId: "Halo, bagaimana saya bantu?", type: "fusha" },
      { speaker: "Kamu", arabic: "السلام عليكم، عندي حجز باسم بُدي.", transliteration: "Assalamu ‘alaikum, ‘indii hajz bismi Budi.", meaningId: "Assalamu’alaikum, saya ada reservasi atas nama Budi.", type: "fusha" },
      { speaker: "Resepsionis", arabic: "تمام، الغرفة 305. هذا المفتاح.", transliteration: "Tamaam, al-ghurfah 305. Haadzaa al-miftaah.", meaningId: "Oke, kamar 305. Ini kuncinya.", type: "mixed" },
      { speaker: "Kamu", arabic: "شكراً. كلمة مرور الواي فاي؟", transliteration: "Syukran. Kalimat muruur al-waay-faay?", meaningId: "Terima kasih. Password WiFi?", type: "mixed" },
    ],
    practicePrompts: [
      "Latih kalimat 'saya ada reservasi atas nama X'.",
      "Tulis 3 fasilitas hotel yang biasa kamu butuh: WiFi, sarapan, kunci.",
      "Buat 1 kalimat tanya password WiFi.",
    ],
    quiz: [
      {
        id: "L4M12L1Q1",
        lessonId: "L4M12L1",
        questionType: "umrah",
        promptId: "Bagaimana bilang 'Saya ada reservasi'?",
        options: ["عندي حجز", "أنا متأخر", "كم السعر", "أبغى قهوة"],
        correctAnswer: "عندي حجز",
        explanationId: "عندي = saya punya; حجز = reservasi.",
        difficulty: "medium",
      },
      {
        id: "L4M12L1Q2",
        lessonId: "L4M12L1",
        questionType: "vocabulary",
        promptId: "مفتاح artinya?",
        arabicText: "مفتاح",
        transliteration: "Miftaah",
        options: ["Kunci", "Pintu", "Jendela", "Lampu"],
        correctAnswer: "Kunci",
        explanationId: "مفتاح = kunci. مفتاح الغرفة = kunci kamar.",
        difficulty: "easy",
      },
      {
        id: "L4M12L1Q3",
        lessonId: "L4M12L1",
        questionType: "situation",
        promptId: "Kamu mau tanya password WiFi. Mana yang paling tepat?",
        options: ["كلمة مرور الواي فاي؟", "كم السعر؟", "أين الغرفة؟", "أنا متأخر"],
        correctAnswer: "كلمة مرور الواي فاي؟",
        explanationId: "كلمة المرور = password; الواي فاي = WiFi.",
        difficulty: "medium",
      },
      {
        id: "L4M12L1Q4",
        lessonId: "L4M12L1",
        questionType: "vocabulary",
        promptId: "الإفطار dalam konteks hotel artinya?",
        arabicText: "الإفطار",
        transliteration: "Al-ifthaar",
        options: ["Sarapan", "Makan malam", "Snack", "Kopi"],
        correctAnswer: "Sarapan",
        explanationId: "الإفطار = sarapan (juga dipakai untuk buka puasa).",
        difficulty: "medium",
      },
      {
        id: "L4M12L1Q5",
        lessonId: "L4M12L1",
        questionType: "situation",
        promptId: "Kamu mau minta room cleaning. Kata kuncinya?",
        options: ["تنظيف", "إفطار", "مفتاح", "حجز"],
        correctAnswer: "تنظيف",
        explanationId: "تنظيف = pembersihan / housekeeping.",
        difficulty: "medium",
      },
      {
        id: "L4M12L1Q6",
        lessonId: "L4M12L1",
        questionType: "meaning",
        promptId: "Resepsionis tanya كيف أساعدك؟. Apa artinya?",
        arabicText: "كيف أساعدك؟",
        transliteration: "Kaifa usaa‘iduk?",
        options: ["Bagaimana saya bisa bantu?", "Berapa harga?", "Siapa kamu?", "Di mana kamarmu?"],
        correctAnswer: "Bagaimana saya bisa bantu?",
        explanationId: "Ungkapan standar dari staf hotel/customer service.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "L4M13L1",
    appSlug: "arabic",
    level: "L4_UMRAH",
    levelTitle: "Umrah Arabic",
    moduleId: "M13",
    moduleTitle: "Masjidil Haram & Masjid Nabawi",
    lessonTitle: "Di Masjidil Haram dan Masjid Nabawi",
    order: 15,
    scenario: "Kamu di Masjidil Haram (Mekah) atau Masjid Nabawi (Madinah). Perlu tanya pintu masuk, tempat wudhu, dan area tawaf/sa'i.",
    targetSkill: "umrah",
    arabicType: "fusha",
    explanationId:
      "Masjid besar punya banyak pintu (باب) dengan nama raja: باب الملك فهد, باب الملك عبدالعزيز, dsb. Tempat wudhu = مكان الوضوء. Area tawaf = صحن الكعبة atau المطاف.",
    saudiNote: "Petugas masjid (asykar) biasanya bisa bahasa Arab dasar dan Inggris dasar. Mereka sangat membantu jamaah lansia atau yang tersesat.",
    vocabulary: [
      { arabic: "باب", transliteration: "Baab", meaningId: "Pintu / gate", type: "fusha" },
      { arabic: "باب الملك فهد", transliteration: "Baab al-malik Fahd", meaningId: "Pintu King Fahd", type: "fusha" },
      { arabic: "مكان الوضوء", transliteration: "Makaan al-wudhuu’", meaningId: "Tempat wudhu", type: "fusha" },
      { arabic: "دورة المياه", transliteration: "Dawrat al-miyaah", meaningId: "Toilet", type: "fusha" },
      { arabic: "الطواف", transliteration: "Ath-thawaaf", meaningId: "Tawaf", type: "fusha" },
      { arabic: "السعي", transliteration: "As-sa‘yi", meaningId: "Sa'i", type: "fusha" },
      { arabic: "الصلاة", transliteration: "Ash-shalaah", meaningId: "Shalat", type: "fusha" },
      { arabic: "زمزم", transliteration: "Zamzam", meaningId: "Air zamzam", type: "fusha" },
      { arabic: "الروضة", transliteration: "Ar-rawdhah", meaningId: "Raudhah (di Masjid Nabawi)", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Kamu", arabic: "أين مكان الوضوء، لو سمحت؟", transliteration: "Aina makaan al-wudhuu’, law samaht?", meaningId: "Di mana tempat wudhu, permisi?", type: "fusha" },
      { speaker: "Petugas", arabic: "تحت، انزل من هذا السلم.", transliteration: "Tahta, inzil min haadzas-sullam.", meaningId: "Di bawah, turun dari tangga ini.", type: "fusha" },
      { speaker: "Kamu", arabic: "شكراً. وأين باب الملك فهد؟", transliteration: "Syukran. Wa aina baab al-malik Fahd?", meaningId: "Terima kasih. Dan di mana pintu King Fahd?", type: "fusha" },
      { speaker: "Petugas", arabic: "على اليسار، خمسين متر.", transliteration: "‘ala al-yasaar, khamsiin mitr.", meaningId: "Di kiri, 50 meter.", type: "fusha" },
    ],
    practicePrompts: [
      "Hafal nama 2 pintu masjid terkenal: باب الملك فهد, باب الملك عبدالعزيز.",
      "Latih kalimat 'di mana tempat wudhu?' dan 'di mana toilet?'.",
      "Buat 3 kalimat tanya lokasi: tawaf, sa'i, zamzam.",
    ],
    quiz: [
      {
        id: "L4M13L1Q1",
        lessonId: "L4M13L1",
        questionType: "umrah",
        promptId: "Bagaimana tanya 'Di mana tempat wudhu?'",
        options: ["أين مكان الوضوء؟", "أين الباب؟", "كم السعر؟", "ما اسمك؟"],
        correctAnswer: "أين مكان الوضوء؟",
        explanationId: "أين = di mana; مكان الوضوء = tempat wudhu.",
        difficulty: "easy",
      },
      {
        id: "L4M13L1Q2",
        lessonId: "L4M13L1",
        questionType: "vocabulary",
        promptId: "دورة المياه artinya?",
        arabicText: "دورة المياه",
        transliteration: "Dawrat al-miyaah",
        options: ["Toilet", "Kamar mandi besar", "Air zamzam", "Tempat wudhu"],
        correctAnswer: "Toilet",
        explanationId: "دورة المياه = toilet (cara umum di Saudi).",
        difficulty: "medium",
      },
      {
        id: "L4M13L1Q3",
        lessonId: "L4M13L1",
        questionType: "umrah",
        promptId: "Kamu tanya 'Di mana pintu King Fahd?'. Mana yang paling tepat?",
        options: ["أين باب الملك فهد؟", "أين الفندق؟", "ما اسمك؟", "كم السعر؟"],
        correctAnswer: "أين باب الملك فهد؟",
        explanationId: "أين = di mana; باب = pintu; الملك فهد = King Fahd.",
        difficulty: "medium",
      },
      {
        id: "L4M13L1Q4",
        lessonId: "L4M13L1",
        questionType: "vocabulary",
        promptId: "الطواف artinya?",
        arabicText: "الطواف",
        transliteration: "Ath-thawaaf",
        options: ["Tawaf (mengelilingi Ka'bah)", "Sa'i", "Shalat", "Wudhu"],
        correctAnswer: "Tawaf (mengelilingi Ka'bah)",
        explanationId: "الطواف = mengelilingi Ka'bah 7 kali.",
        difficulty: "easy",
      },
      {
        id: "L4M13L1Q5",
        lessonId: "L4M13L1",
        questionType: "vocabulary",
        promptId: "Mana arti dari السعي?",
        arabicText: "السعي",
        transliteration: "As-sa‘yi",
        options: ["Sa'i antara Shafa dan Marwah", "Tawaf", "Wudhu", "Doa"],
        correctAnswer: "Sa'i antara Shafa dan Marwah",
        explanationId: "السعي = berjalan 7 kali antara Shafa dan Marwah.",
        difficulty: "medium",
      },
      {
        id: "L4M13L1Q6",
        lessonId: "L4M13L1",
        questionType: "situation",
        promptId: "Petugas bilang على اليسار خمسين متر. Apa artinya?",
        arabicText: "على اليسار، خمسين متر",
        options: ["Di kiri, 50 meter", "Di kanan, 50 meter", "Lurus, 50 meter", "Di belakang, 50 meter"],
        correctAnswer: "Di kiri, 50 meter",
        explanationId: "على اليسار = di kiri; خمسين متر = 50 meter.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "L4M14L1",
    appSlug: "arabic",
    level: "L4_UMRAH",
    levelTitle: "Umrah Arabic",
    moduleId: "M14",
    moduleTitle: "Health & Emergency During Umrah",
    lessonTitle: "Sakit, Tersesat, dan Darurat",
    order: 16,
    scenario: "Kamu tersesat di area haram yang luas, atau sakit kelelahan setelah tawaf, atau hilang barang. Kamu butuh komunikasi cepat dan jelas.",
    targetSkill: "umrah",
    arabicType: "fusha",
    explanationId:
      "Frasa darurat: أنا ضائع (saya tersesat), أنا تعبان (saya kelelahan), أحتاج دكتور (saya butuh dokter). Polisi/petugas: شرطة atau أمن.",
    saudiNote: "Layanan kesehatan untuk jamaah umrah/haji gratis di klinik darurat sekitar Masjidil Haram dan Masjid Nabawi. Selalu bawa kartu jamaah.",
    vocabulary: [
      { arabic: "أنا ضائع", transliteration: "Anaa dhaa’i‘", meaningId: "Saya tersesat (laki)", type: "fusha" },
      { arabic: "أنا ضائعة", transliteration: "Anaa dhaa’i‘ah", meaningId: "Saya tersesat (perempuan)", type: "fusha" },
      { arabic: "أنا تعبان", transliteration: "Anaa ta‘baan", meaningId: "Saya kelelahan (laki)", type: "fusha" },
      { arabic: "أحتاج دكتور", transliteration: "Ahtaaju duktuur", meaningId: "Saya butuh dokter", type: "mixed" },
      { arabic: "مستشفى", transliteration: "Mustasyfa", meaningId: "Rumah sakit", type: "fusha" },
      { arabic: "صيدلية", transliteration: "Shaydaliyyah", meaningId: "Apotek", type: "fusha" },
      { arabic: "شرطة", transliteration: "Syurthah", meaningId: "Polisi", type: "fusha" },
      { arabic: "أمن", transliteration: "Amn", meaningId: "Keamanan / petugas", type: "fusha" },
      { arabic: "فقدت هاتفي", transliteration: "Faqadtu haatifii", meaningId: "Saya kehilangan HP", type: "fusha" },
      { arabic: "صداع", transliteration: "Shudaa‘", meaningId: "Sakit kepala", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Kamu", arabic: "أنا ضائع، أين فندق الأنوار؟", transliteration: "Anaa dhaa’i‘, aina funduq al-anwaar?", meaningId: "Saya tersesat, di mana Hotel Al-Anwar?", type: "fusha" },
      { speaker: "Petugas", arabic: "تعال معي. أنت متعب؟", transliteration: "Ta‘aal ma‘ii. Anta muta‘ab?", meaningId: "Ikut saya. Kamu lelah?", type: "fusha" },
      { speaker: "Kamu", arabic: "نعم، تعبان جداً، عندي صداع.", transliteration: "Na‘am, ta‘baan jiddan, ‘indii shudaa‘.", meaningId: "Ya, sangat lelah, saya sakit kepala.", type: "fusha" },
      { speaker: "Petugas", arabic: "هناك صيدلية قريبة، تعال.", transliteration: "Hunaaka shaydaliyyah qariibah, ta‘aal.", meaningId: "Ada apotek dekat, ikut.", type: "fusha" },
    ],
    practicePrompts: [
      "Latih kalimat 'saya tersesat' versi laki dan perempuan.",
      "Hafal kata penting darurat: شرطة، أمن، مستشفى، صيدلية، دكتور.",
      "Buat 1 kalimat: 'saya kehilangan HP' (فقدت هاتفي).",
    ],
    quiz: [
      {
        id: "L4M14L1Q1",
        lessonId: "L4M14L1",
        questionType: "umrah",
        promptId: "Kamu (laki-laki) tersesat. Apa yang paling tepat kamu bilang?",
        options: ["أنا ضائع", "أنا ضائعة", "أنا متأخر", "أنا تعبان"],
        correctAnswer: "أنا ضائع",
        explanationId: "Untuk laki-laki: أنا ضائع. Perempuan: أنا ضائعة.",
        difficulty: "easy",
      },
      {
        id: "L4M14L1Q2",
        lessonId: "L4M14L1",
        questionType: "situation",
        promptId: "Kamu butuh obat. Mana yang paling tepat?",
        options: ["أين الصيدلية؟", "أين الحرم؟", "أين الفندق؟", "أين البوابة؟"],
        correctAnswer: "أين الصيدلية؟",
        explanationId: "صيدلية = apotek.",
        difficulty: "medium",
      },
      {
        id: "L4M14L1Q3",
        lessonId: "L4M14L1",
        questionType: "vocabulary",
        promptId: "Apa arti شرطة?",
        arabicText: "شرطة",
        transliteration: "Syurthah",
        options: ["Polisi", "Tentara", "Dokter", "Petugas masjid"],
        correctAnswer: "Polisi",
        explanationId: "شرطة = polisi. Juga sering disebut أمن untuk petugas keamanan umum.",
        difficulty: "easy",
      },
      {
        id: "L4M14L1Q4",
        lessonId: "L4M14L1",
        questionType: "situation",
        promptId: "Kamu sakit kepala parah dan butuh dokter. Frasa paling tepat?",
        options: ["أحتاج دكتور", "أبغى قهوة", "كم السعر؟", "أنا متأخر"],
        correctAnswer: "أحتاج دكتور",
        explanationId: "أحتاج = saya butuh; دكتور = dokter.",
        difficulty: "easy",
      },
      {
        id: "L4M14L1Q5",
        lessonId: "L4M14L1",
        questionType: "vocabulary",
        promptId: "صداع artinya?",
        arabicText: "صداع",
        transliteration: "Shudaa‘",
        options: ["Sakit kepala", "Sakit perut", "Demam", "Pusing"],
        correctAnswer: "Sakit kepala",
        explanationId: "صداع = sakit kepala.",
        difficulty: "medium",
      },
      {
        id: "L4M14L1Q6",
        lessonId: "L4M14L1",
        questionType: "situation",
        promptId: "Kamu kehilangan HP. Mana yang paling jelas dilaporkan?",
        options: ["فقدت هاتفي", "أبغى هاتف", "هاتفي جديد", "هذا هاتف"],
        correctAnswer: "فقدت هاتفي",
        explanationId: "فقدت = saya kehilangan; هاتفي = HP saya.",
        difficulty: "medium",
      },
    ],
  },
];
