import type { ArabicLesson } from "../types";

export const level6Lessons: ArabicLesson[] = [
  {
    id: "L6M17L1",
    appSlug: "arabic",
    level: "L6_DIALECT",
    levelTitle: "Practical Saudi Dialect",
    moduleId: "M17",
    moduleTitle: "Common Saudi Expressions",
    lessonTitle: "Ungkapan Saudi Paling Sering",
    order: 19,
    scenario: "Kamu sering dengar orang Saudi bilang إيش، وش، أبغى، خلاص، يلا، طيب. Kamu butuh paham artinya supaya bisa ikut alur percakapan harian.",
    targetSkill: "dialect",
    arabicType: "saudi",
    explanationId:
      "Saudi dialect (اللهجة السعودية) berbeda dari Fusha. Kata-kata pendek ini muncul setiap kalimat di kehidupan harian. Hafalkan dan pakai sehari-hari.",
    saudiNote: "Banyak ungkapan Saudi berasal dari bahasa Arab Najd (Saudi Tengah). Kalau kamu pakai ungkapan ini, orang Saudi langsung merasa lebih akrab.",
    vocabulary: [
      { arabic: "إيش", transliteration: "Eesh", meaningId: "Apa? (Saudi)", type: "saudi" },
      { arabic: "وش", transliteration: "Wish", meaningId: "Apa? (versi lebih pendek)", type: "saudi" },
      { arabic: "أبغى", transliteration: "Abghaa", meaningId: "Saya mau", type: "saudi" },
      { arabic: "ما أبغى", transliteration: "Maa abghaa", meaningId: "Saya tidak mau", type: "saudi" },
      { arabic: "خلاص", transliteration: "Khalaas", meaningId: "Selesai / oke / cukup", type: "saudi" },
      { arabic: "يلا", transliteration: "Yalla", meaningId: "Ayo", type: "saudi" },
      { arabic: "طيب", transliteration: "Thayyib", meaningId: "Oke / baik", type: "saudi" },
      { arabic: "فين", transliteration: "Feen", meaningId: "Di mana?", type: "saudi" },
      { arabic: "كيفك؟", transliteration: "Kaifak?", meaningId: "Apa kabar? (laki)", type: "saudi" },
      { arabic: "كيفك؟", transliteration: "Kaifik?", meaningId: "Apa kabar? (perempuan)", type: "saudi" },
    ],
    dialogue: [
      { speaker: "Teman Saudi", arabic: "هلا، كيفك؟", transliteration: "Halaa, kaifak?", meaningId: "Hai, apa kabar?", type: "saudi" },
      { speaker: "Kamu", arabic: "تمام، إنت كيفك؟", transliteration: "Tamaam, inta kaifak?", meaningId: "Baik, kamu apa kabar?", type: "saudi" },
      { speaker: "Teman Saudi", arabic: "الحمدلله. وش تبغى تأكل؟", transliteration: "Al-hamdulillaah. Wish tabghaa ta’kul?", meaningId: "Alhamdulillah. Kamu mau makan apa?", type: "saudi" },
      { speaker: "Kamu", arabic: "أبغى رز ودجاج.", transliteration: "Abghaa ruzz wa dajaaj.", meaningId: "Saya mau nasi dan ayam.", type: "saudi" },
      { speaker: "Teman Saudi", arabic: "طيب، يلا.", transliteration: "Thayyib, yalla.", meaningId: "Oke, ayo.", type: "saudi" },
    ],
    practicePrompts: [
      "Hafal 7 kata Saudi paling sering: إيش، وش، أبغى، خلاص، يلا، طيب، فين.",
      "Latih percakapan singkat dengan 3 ungkapan Saudi minimal.",
      "Bandingkan: أين (Fusha) vs فين (Saudi), أريد (Fusha) vs أبغى (Saudi).",
    ],
    quiz: [
      {
        id: "L6M17L1Q1",
        lessonId: "L6M17L1",
        questionType: "saudi_expression",
        promptId: "Apa arti إيش dalam dialek Saudi?",
        arabicText: "إيش",
        transliteration: "Eesh",
        options: ["Apa?", "Di mana?", "Berapa?", "Siapa?"],
        correctAnswer: "Apa?",
        explanationId: "إيش (Saudi) = ما (Fusha) = apa.",
        difficulty: "easy",
      },
      {
        id: "L6M17L1Q2",
        lessonId: "L6M17L1",
        questionType: "saudi_expression",
        promptId: "أبغى ماء artinya?",
        arabicText: "أبغى ماء",
        transliteration: "Abghaa maa’",
        options: ["Saya mau air", "Saya tidak mau air", "Saya minum air", "Berapa harga air"],
        correctAnswer: "Saya mau air",
        explanationId: "أبغى (Saudi) = أريد (Fusha) = saya mau.",
        difficulty: "easy",
      },
      {
        id: "L6M17L1Q3",
        lessonId: "L6M17L1",
        questionType: "saudi_expression",
        promptId: "Saat orang Saudi bilang خلاص setelah negosiasi, artinya?",
        arabicText: "خلاص",
        transliteration: "Khalaas",
        options: ["Selesai / setuju", "Tidak setuju", "Tunggu", "Pergi"],
        correctAnswer: "Selesai / setuju",
        explanationId: "خلاص multi-arti: selesai, oke, setuju.",
        difficulty: "medium",
      },
      {
        id: "L6M17L1Q4",
        lessonId: "L6M17L1",
        questionType: "saudi_expression",
        promptId: "يلا artinya?",
        arabicText: "يلا",
        transliteration: "Yalla",
        options: ["Ayo", "Selesai", "Tidak", "Maaf"],
        correctAnswer: "Ayo",
        explanationId: "يلا dipakai untuk ajakan: ayo, cepat.",
        difficulty: "easy",
      },
      {
        id: "L6M17L1Q5",
        lessonId: "L6M17L1",
        questionType: "saudi_expression",
        promptId: "Versi Saudi dari 'di mana' adalah?",
        options: ["فين", "وين", "أين", "إيش"],
        correctAnswer: "فين",
        explanationId: "فين adalah versi Saudi populer untuk 'di mana'.",
        difficulty: "easy",
      },
      {
        id: "L6M17L1Q6",
        lessonId: "L6M17L1",
        questionType: "saudi_expression",
        promptId: "Teman Saudi tanya كيفك؟. Jawaban paling natural?",
        arabicText: "كيفك؟",
        options: ["تمام، الحمدلله", "ما أبغى", "خلاص", "أين البوابة"],
        correctAnswer: "تمام، الحمدلله",
        explanationId: "تمام = baik; الحمدلله = alhamdulillah. Jawaban standar untuk 'apa kabar?'.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "L6M17L2",
    appSlug: "arabic",
    level: "L6_DIALECT",
    levelTitle: "Practical Saudi Dialect",
    moduleId: "M17",
    moduleTitle: "Common Saudi Expressions",
    lessonTitle: "Ungkapan Saudi Lanjutan",
    order: 20,
    scenario: "Setelah dasar Saudi expressions kamu kuasai, level berikut: ungkapan Saudi yang menunjukkan perasaan, persetujuan halus, dan respons sopan.",
    targetSkill: "dialect",
    arabicType: "saudi",
    explanationId:
      "Ungkapan ini bikin kamu terdengar lebih natural di Saudi. Hindari versi Mesir atau Levant — pakai versi Saudi.",
    saudiNote: "Orang Saudi sangat sering memuji dengan ما شاء الله. Saat dipuji, jawab الله يبارك فيك (Allah yubaarik fiik) — semoga Allah memberkahimu.",
    vocabulary: [
      { arabic: "ما شاء الله", transliteration: "Maa syaa Allah", meaningId: "Masya Allah / pujian", type: "fusha" },
      { arabic: "الله يبارك فيك", transliteration: "Allah yubaarik fiik", meaningId: "Semoga Allah berkahi kamu (laki)", type: "fusha" },
      { arabic: "الله يبارك فيك", transliteration: "Allah yubaarik fiiki", meaningId: "Semoga Allah berkahi kamu (perempuan)", type: "fusha" },
      { arabic: "جزاك الله خير", transliteration: "Jazaakallaahu khair", meaningId: "Semoga Allah balas dengan kebaikan", type: "fusha" },
      { arabic: "تمام التمام", transliteration: "Tamaam at-tamaam", meaningId: "Mantap / oke banget", type: "saudi" },
      { arabic: "زين", transliteration: "Zain", meaningId: "Bagus (Saudi)", type: "saudi" },
      { arabic: "مو زين", transliteration: "Muu zain", meaningId: "Tidak bagus", type: "saudi" },
      { arabic: "أكيد", transliteration: "Akiid", meaningId: "Pasti / tentu", type: "saudi" },
      { arabic: "والله", transliteration: "Wallaah", meaningId: "Demi Allah / sumpah", type: "saudi" },
      { arabic: "إن شاء الله", transliteration: "Inshaa Allah", meaningId: "Insya Allah", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Saudi", arabic: "إنت من إندونيسيا؟ ما شاء الله، عربيتك زين.", transliteration: "Inta min Induuniisiyaa? Maa syaa Allah, ‘arabiyyatak zain.", meaningId: "Kamu dari Indonesia? Masya Allah, bahasa Arabmu bagus.", type: "saudi" },
      { speaker: "Kamu", arabic: "الله يبارك فيك. أتعلم كل يوم.", transliteration: "Allah yubaarik fiik. Ata‘allamu kulla yawm.", meaningId: "Semoga Allah memberkahi. Saya belajar setiap hari.", type: "mixed" },
      { speaker: "Saudi", arabic: "أكيد، إن شاء الله تتطور.", transliteration: "Akiid, inshaa Allah tatathawwar.", meaningId: "Pasti, insya Allah kamu berkembang.", type: "saudi" },
      { speaker: "Kamu", arabic: "جزاك الله خير.", transliteration: "Jazaakallaahu khair.", meaningId: "Semoga Allah balas dengan kebaikan.", type: "fusha" },
    ],
    practicePrompts: [
      "Hafal 5 ungkapan baru: ما شاء الله، الله يبارك فيك، جزاك الله خير، زين، أكيد.",
      "Latih respons saat dipuji: الله يبارك فيك.",
      "Coba 3 kalimat 'bagus' (زين) dan 'tidak bagus' (مو زين) untuk barang/situasi.",
    ],
    quiz: [
      {
        id: "L6M17L2Q1",
        lessonId: "L6M17L2",
        questionType: "saudi_expression",
        promptId: "Saat dipuji ما شاء الله, kamu sebaiknya balas dengan?",
        options: ["الله يبارك فيك", "ما أبغى", "خلاص", "كم السعر"],
        correctAnswer: "الله يبارك فيك",
        explanationId: "Balasan sopan untuk pujian: الله يبارك فيك (semoga Allah memberkahimu).",
        difficulty: "medium",
      },
      {
        id: "L6M17L2Q2",
        lessonId: "L6M17L2",
        questionType: "saudi_expression",
        promptId: "زين dalam Saudi artinya?",
        arabicText: "زين",
        transliteration: "Zain",
        options: ["Bagus", "Buruk", "Cepat", "Lambat"],
        correctAnswer: "Bagus",
        explanationId: "زين = bagus (Saudi). Lawan: مو زين.",
        difficulty: "easy",
      },
      {
        id: "L6M17L2Q3",
        lessonId: "L6M17L2",
        questionType: "saudi_expression",
        promptId: "Apa arti أكيد?",
        arabicText: "أكيد",
        transliteration: "Akiid",
        options: ["Pasti / tentu", "Mungkin", "Tidak", "Lambat"],
        correctAnswer: "Pasti / tentu",
        explanationId: "أكيد dipakai untuk meyakinkan: pasti, tentu.",
        difficulty: "easy",
      },
      {
        id: "L6M17L2Q4",
        lessonId: "L6M17L2",
        questionType: "meaning",
        promptId: "جزاك الله خير artinya?",
        arabicText: "جزاك الله خير",
        transliteration: "Jazaakallaahu khair",
        options: ["Semoga Allah balas dengan kebaikan", "Selamat tinggal", "Maaf", "Tolong"],
        correctAnswer: "Semoga Allah balas dengan kebaikan",
        explanationId: "Ungkapan terima kasih Islami yang sering dipakai.",
        difficulty: "medium",
      },
      {
        id: "L6M17L2Q5",
        lessonId: "L6M17L2",
        questionType: "saudi_expression",
        promptId: "Mana yang artinya 'sumpah / demi Allah' (informal)?",
        options: ["والله", "خلاص", "يلا", "أكيد"],
        correctAnswer: "والله",
        explanationId: "والله dipakai untuk menegaskan, mirip 'sumpah/demi Allah'.",
        difficulty: "medium",
      },
      {
        id: "L6M17L2Q6",
        lessonId: "L6M17L2",
        questionType: "saudi_expression",
        promptId: "Mana arti dari مو زين?",
        arabicText: "مو زين",
        transliteration: "Muu zain",
        options: ["Tidak bagus", "Sangat bagus", "Mahal", "Murah"],
        correctAnswer: "Tidak bagus",
        explanationId: "مو (Saudi) = tidak / bukan; زين = bagus. مو زين = tidak bagus.",
        difficulty: "medium",
      },
    ],
  },
];
