import type { ArabicLesson } from "../types";

export const level1Lessons: ArabicLesson[] = [
  {
    id: "L1M1L1",
    appSlug: "arabic",
    level: "L1_FOUNDATION",
    levelTitle: "Survival Arabic Foundation",
    moduleId: "M1",
    moduleTitle: "Arabic Sound & Basic Reading",
    lessonTitle: "Pengenalan Huruf Arab",
    order: 1,
    scenario: "Kamu baru sampai di Saudi dan melihat banyak tulisan Arab di bandara, jalan, dan papan toko. Kenali huruf-huruf paling umum supaya tidak buta huruf.",
    targetSkill: "daily",
    arabicType: "fusha",
    explanationId:
      "Bahasa Arab ditulis dari kanan ke kiri dengan 28 huruf. Kebanyakan huruf berubah bentuk tergantung posisinya. Untuk pemula, fokus dulu mengenali bentuk dasar.",
    saudiNote: "Di Saudi, papan jalan sering ditulis dalam dua versi: Arab dan transliterasi Latin. Ini mempermudah orang asing.",
    vocabulary: [
      { arabic: "ا", transliteration: "alif", meaningId: "huruf pertama; bunyi a panjang", type: "fusha", usageNote: "bentuk garis lurus, mudah dikenali" },
      { arabic: "ب", transliteration: "baa", meaningId: "bunyi b", type: "fusha", usageNote: "satu titik di bawah" },
      { arabic: "ت", transliteration: "taa", meaningId: "bunyi t", type: "fusha", usageNote: "dua titik di atas" },
      { arabic: "م", transliteration: "miim", meaningId: "bunyi m", type: "fusha" },
      { arabic: "ن", transliteration: "nuun", meaningId: "bunyi n", type: "fusha", usageNote: "satu titik di atas" },
      { arabic: "ل", transliteration: "laam", meaningId: "bunyi l", type: "fusha" },
      { arabic: "ك", transliteration: "kaaf", meaningId: "bunyi k", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Guide", arabic: "هذا حرف ألف.", transliteration: "Haadzaa harf alif.", meaningId: "Ini huruf alif.", type: "fusha" },
      { speaker: "Murid", arabic: "وهذا؟", transliteration: "Wa haadzaa?", meaningId: "Dan ini?", type: "fusha" },
      { speaker: "Guide", arabic: "هذا حرف باء.", transliteration: "Haadzaa harf baa.", meaningId: "Ini huruf baa.", type: "fusha" },
    ],
    practicePrompts: [
      "Tulis 5 huruf Arab pertama yang kamu kenali hari ini.",
      "Cari satu papan tulisan Arab di sekitarmu dan coba kenali minimal 2 huruf.",
      "Ucapkan ا، ب، ت dengan jelas sebanyak 3 kali.",
    ],
    quiz: [
      {
        id: "L1M1L1Q1",
        lessonId: "L1M1L1",
        questionType: "vocabulary",
        promptId: "Apa nama huruf Arab ini: ا ?",
        arabicText: "ا",
        options: ["alif", "baa", "miim", "nuun"],
        correctAnswer: "alif",
        explanationId: "ا adalah huruf pertama dalam abjad Arab, berbunyi mirip 'a' panjang.",
        difficulty: "easy",
      },
      {
        id: "L1M1L1Q2",
        lessonId: "L1M1L1",
        questionType: "vocabulary",
        promptId: "Huruf apa yang dibaca 'baa'?",
        options: ["ب", "ت", "ن", "م"],
        correctAnswer: "ب",
        explanationId: "ب memiliki satu titik di bawah dan dibaca 'baa' (bunyi b).",
        difficulty: "easy",
      },
      {
        id: "L1M1L1Q3",
        lessonId: "L1M1L1",
        questionType: "meaning",
        promptId: "Bahasa Arab ditulis dari arah mana?",
        options: ["Kanan ke kiri", "Kiri ke kanan", "Atas ke bawah", "Tidak menentu"],
        correctAnswer: "Kanan ke kiri",
        explanationId: "Tulisan Arab selalu dimulai dari kanan dan berakhir di kiri.",
        difficulty: "easy",
      },
      {
        id: "L1M1L1Q4",
        lessonId: "L1M1L1",
        questionType: "vocabulary",
        promptId: "Mana huruf yang dibaca 'miim'?",
        options: ["م", "ن", "ل", "ك"],
        correctAnswer: "م",
        explanationId: "م adalah huruf miim, berbunyi 'm'.",
        difficulty: "easy",
      },
      {
        id: "L1M1L1Q5",
        lessonId: "L1M1L1",
        questionType: "meaning",
        promptId: "Berapa jumlah huruf dasar dalam abjad Arab?",
        options: ["28", "26", "30", "24"],
        correctAnswer: "28",
        explanationId: "Abjad Arab terdiri dari 28 huruf dasar.",
        difficulty: "medium",
      },
      {
        id: "L1M1L1Q6",
        lessonId: "L1M1L1",
        questionType: "vocabulary",
        promptId: "Huruf ن dibaca apa?",
        arabicText: "ن",
        options: ["nuun", "laam", "taa", "kaaf"],
        correctAnswer: "nuun",
        explanationId: "ن memiliki satu titik di atas dan dibaca 'nuun' (bunyi n).",
        difficulty: "easy",
      },
    ],
  },
  {
    id: "L1M1L2",
    appSlug: "arabic",
    level: "L1_FOUNDATION",
    levelTitle: "Survival Arabic Foundation",
    moduleId: "M1",
    moduleTitle: "Arabic Sound & Basic Reading",
    lessonTitle: "Bunyi Sulit: ع، غ، ح، خ، ق",
    order: 2,
    scenario: "Banyak orang Indonesia kesulitan dengan 5 huruf ini karena tidak ada padanan dalam Bahasa Indonesia. Kamu butuh latihan supaya bisa diucapkan benar saat ngomong di Saudi.",
    targetSkill: "daily",
    arabicType: "fusha",
    explanationId:
      "ع dan غ dari pangkal tenggorokan, ح dan خ dari pertengahan tenggorokan, dan ق dari pangkal lidah. Latihan dengan perlahan, jangan dipaksa.",
    saudiNote: "Orang Saudi sangat memahami pelafalan yang belum sempurna, asal kamu mau mencoba. Tidak perlu malu.",
    vocabulary: [
      { arabic: "ع", transliteration: "‘ain", meaningId: "bunyi 'ain — dari pangkal tenggorokan", type: "fusha", usageNote: "tekan tenggorokan, bukan a biasa" },
      { arabic: "غ", transliteration: "ghain", meaningId: "bunyi 'ghain' mirip kumur ringan", type: "fusha" },
      { arabic: "ح", transliteration: "haa", meaningId: "bunyi h dari tenggorokan, hembusan kuat", type: "fusha" },
      { arabic: "خ", transliteration: "khaa", meaningId: "bunyi 'kh' seperti dengkur", type: "fusha" },
      { arabic: "ق", transliteration: "qaaf", meaningId: "bunyi 'q' dari pangkal lidah", type: "fusha" },
      { arabic: "عَين", transliteration: "‘ain", meaningId: "mata", type: "fusha" },
      { arabic: "قَلْب", transliteration: "qalb", meaningId: "hati", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Pelatih", arabic: "قُلْ: عَيْن.", transliteration: "Qul: ‘ain.", meaningId: "Ucapkan: 'ain.", type: "fusha" },
      { speaker: "Murid", arabic: "عَيْن.", transliteration: "‘ain.", meaningId: "‘ain.", type: "fusha" },
      { speaker: "Pelatih", arabic: "أَحْسَنْت!", transliteration: "Ahsant!", meaningId: "Bagus sekali!", type: "fusha" },
    ],
    practicePrompts: [
      "Ucapkan 5 huruf sulit ini masing-masing 3 kali sambil rekam suaramu.",
      "Coba dengar perbedaan antara ح dan خ pada YouTube atau Quran reciter.",
      "Tulis 3 kata Arab yang punya huruf ع.",
    ],
    quiz: [
      {
        id: "L1M1L2Q1",
        lessonId: "L1M1L2",
        questionType: "vocabulary",
        promptId: "Huruf ع dibaca apa?",
        arabicText: "ع",
        options: ["‘ain", "ghain", "qaaf", "khaa"],
        correctAnswer: "‘ain",
        explanationId: "ع dibaca '‘ain' dari pangkal tenggorokan.",
        difficulty: "easy",
      },
      {
        id: "L1M1L2Q2",
        lessonId: "L1M1L2",
        questionType: "vocabulary",
        promptId: "Mana huruf yang dibaca 'khaa'?",
        options: ["خ", "ح", "ع", "غ"],
        correctAnswer: "خ",
        explanationId: "خ punya satu titik di atas dan dibaca 'khaa' — seperti bunyi dengkur halus.",
        difficulty: "medium",
      },
      {
        id: "L1M1L2Q3",
        lessonId: "L1M1L2",
        questionType: "meaning",
        promptId: "Kata عَيْن artinya apa?",
        arabicText: "عَيْن",
        transliteration: "‘ain",
        options: ["mata", "hati", "tangan", "kaki"],
        correctAnswer: "mata",
        explanationId: "عَيْن berarti mata. Hafalkan bersama bunyi ‘ain yang khas.",
        difficulty: "easy",
      },
      {
        id: "L1M1L2Q4",
        lessonId: "L1M1L2",
        questionType: "meaning",
        promptId: "Kata قَلْب artinya apa?",
        arabicText: "قَلْب",
        transliteration: "qalb",
        options: ["hati", "kepala", "mulut", "kaki"],
        correctAnswer: "hati",
        explanationId: "قَلْب berarti hati. Bunyi awalnya pakai ق (qaaf) dari pangkal lidah.",
        difficulty: "easy",
      },
      {
        id: "L1M1L2Q5",
        lessonId: "L1M1L2",
        questionType: "situation",
        promptId: "Saat seseorang Saudi memujimu setelah kamu mencoba mengucapkan ع dengan benar, dia akan bilang أَحْسَنْت. Apa artinya?",
        arabicText: "أَحْسَنْت",
        transliteration: "Ahsant",
        options: ["Bagus sekali!", "Salah!", "Coba lagi", "Selamat tinggal"],
        correctAnswer: "Bagus sekali!",
        explanationId: "أَحْسَنْت adalah pujian umum yang berarti 'kamu melakukan dengan baik'.",
        difficulty: "medium",
      },
      {
        id: "L1M1L2Q6",
        lessonId: "L1M1L2",
        questionType: "vocabulary",
        promptId: "Huruf ق diucapkan dari bagian mana?",
        options: ["Pangkal lidah", "Bibir", "Ujung lidah", "Gigi"],
        correctAnswer: "Pangkal lidah",
        explanationId: "ق dihasilkan dari pangkal lidah menyentuh langit-langit belakang.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "L1M2L1",
    appSlug: "arabic",
    level: "L1_FOUNDATION",
    levelTitle: "Survival Arabic Foundation",
    moduleId: "M2",
    moduleTitle: "Greeting & Self Introduction",
    lessonTitle: "Salam dan Sapaan Dasar",
    order: 3,
    scenario: "Hari pertama di Saudi. Kamu masuk ke toko, kantor, atau bertemu orang. Salam adalah pembuka semua percakapan.",
    targetSkill: "daily",
    arabicType: "mixed",
    explanationId:
      "السلام عليكم adalah salam universal Muslim, dijawab dengan وعليكم السلام. Untuk situasi non-formal cukup مرحبا (marhaba). Orang Saudi juga sering bilang هلا (halaa).",
    saudiNote: "هلا dan أهلين adalah versi santai Saudi yang sangat sering dipakai sehari-hari, terutama dengan teman atau staf toko.",
    vocabulary: [
      { arabic: "السلام عليكم", transliteration: "Assalamu ‘alaikum", meaningId: "Salam keselamatan atasmu", type: "fusha" },
      { arabic: "وعليكم السلام", transliteration: "Wa ‘alaikumussalam", meaningId: "Dan keselamatan juga untukmu", type: "fusha" },
      { arabic: "مرحبا", transliteration: "Marhaba", meaningId: "Halo", type: "mixed" },
      { arabic: "أهلاً وسهلاً", transliteration: "Ahlan wa sahlan", meaningId: "Selamat datang", type: "fusha" },
      { arabic: "هلا", transliteration: "Halaa", meaningId: "Hai (santai)", type: "saudi", usageNote: "versi santai khas Saudi" },
      { arabic: "أهلين", transliteration: "Ahlain", meaningId: "Hai juga (jawaban santai)", type: "saudi" },
      { arabic: "صباح الخير", transliteration: "Shabaah al-khair", meaningId: "Selamat pagi", type: "fusha" },
      { arabic: "مساء الخير", transliteration: "Masaa al-khair", meaningId: "Selamat sore/malam", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Toko", arabic: "السلام عليكم.", transliteration: "Assalamu ‘alaikum.", meaningId: "Assalamu’alaikum.", type: "fusha" },
      { speaker: "Kamu", arabic: "وعليكم السلام.", transliteration: "Wa ‘alaikumussalam.", meaningId: "Wa’alaikumussalam.", type: "fusha" },
      { speaker: "Toko", arabic: "هلا، تفضل.", transliteration: "Halaa, tafaddhal.", meaningId: "Hai, silakan.", type: "saudi" },
      { speaker: "Kamu", arabic: "شكراً.", transliteration: "Syukran.", meaningId: "Terima kasih.", type: "fusha" },
    ],
    practicePrompts: [
      "Tulis salam yang pas untuk pagi hari dan untuk sore hari.",
      "Latih jawaban dari السلام عليكم — ucapkan 5 kali sampai natural.",
      "Coba sapa orang Saudi (atau temanmu) hari ini dengan هلا dan lihat reaksinya.",
    ],
    quiz: [
      {
        id: "L1M2L1Q1",
        lessonId: "L1M2L1",
        questionType: "meaning",
        promptId: "Apa jawaban yang benar untuk السلام عليكم?",
        arabicText: "السلام عليكم",
        options: ["وعليكم السلام", "صباح الخير", "مرحبا", "شكراً"],
        correctAnswer: "وعليكم السلام",
        explanationId: "Salam Islami dijawab dengan وعليكم السلام (dan keselamatan juga untukmu).",
        difficulty: "easy",
      },
      {
        id: "L1M2L1Q2",
        lessonId: "L1M2L1",
        questionType: "saudi_expression",
        promptId: "Kata هلا adalah versi Saudi dari sapaan apa?",
        arabicText: "هلا",
        transliteration: "Halaa",
        options: ["Hai / halo santai", "Selamat tinggal", "Terima kasih", "Maaf"],
        correctAnswer: "Hai / halo santai",
        explanationId: "هلا adalah sapaan santai khas Saudi yang sangat sering dipakai.",
        difficulty: "easy",
      },
      {
        id: "L1M2L1Q3",
        lessonId: "L1M2L1",
        questionType: "meaning",
        promptId: "Saat seseorang bilang أهلاً وسهلاً padamu, apa arti yang paling tepat?",
        arabicText: "أهلاً وسهلاً",
        transliteration: "Ahlan wa sahlan",
        options: ["Selamat datang", "Selamat tinggal", "Maaf", "Sampai jumpa"],
        correctAnswer: "Selamat datang",
        explanationId: "أهلاً وسهلاً adalah cara umum untuk menyambut tamu.",
        difficulty: "easy",
      },
      {
        id: "L1M2L1Q4",
        lessonId: "L1M2L1",
        questionType: "situation",
        promptId: "Kamu masuk toko jam 9 pagi. Sapaan paling tepat?",
        options: ["صباح الخير", "مساء الخير", "تصبح على خير", "ليلة سعيدة"],
        correctAnswer: "صباح الخير",
        explanationId: "صباح الخير (Shabaah al-khair) dipakai untuk sapaan pagi.",
        difficulty: "easy",
      },
      {
        id: "L1M2L1Q5",
        lessonId: "L1M2L1",
        questionType: "situation",
        promptId: "Sore hari, kamu mau menyapa pelanggan di toko. Mana yang paling tepat?",
        options: ["مساء الخير", "صباح الخير", "تصبح على خير", "إلى اللقاء"],
        correctAnswer: "مساء الخير",
        explanationId: "مساء الخير (Masaa al-khair) berarti 'selamat sore/malam'.",
        difficulty: "easy",
      },
      {
        id: "L1M2L1Q6",
        lessonId: "L1M2L1",
        questionType: "saudi_expression",
        promptId: "Saat dijawab هلا, balasan santai yang paling natural di Saudi adalah?",
        arabicText: "هلا",
        options: ["أهلين", "مع السلامة", "شكراً", "نعم"],
        correctAnswer: "أهلين",
        explanationId: "أهلين adalah jawaban santai khas untuk هلا.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "L1M2L2",
    appSlug: "arabic",
    level: "L1_FOUNDATION",
    levelTitle: "Survival Arabic Foundation",
    moduleId: "M2",
    moduleTitle: "Greeting & Self Introduction",
    lessonTitle: "Perkenalan Nama dan Asal",
    order: 4,
    scenario: "Hari kedua kerja atau ketemu pasangan kerja baru. Kamu perlu memperkenalkan nama, asal negara, dan tujuan di Saudi.",
    targetSkill: "daily",
    arabicType: "fusha",
    explanationId:
      "Gunakan اسمي (ismii) untuk 'nama saya', أنا من (anaa min) untuk 'saya dari', dan جئت (ji'tu) untuk 'saya datang'. Bahasa Fusha cocok untuk konteks pertama kali bertemu.",
    saudiNote: "Untuk pekerja Indonesia, sebut indonesian (إندونيسي) atau dari Indonesia (من إندونيسيا). Orang Saudi umumnya kenal Indonesia, terutama dari musim haji dan umrah.",
    vocabulary: [
      { arabic: "اسمي", transliteration: "Ismii", meaningId: "Nama saya", type: "fusha" },
      { arabic: "أنا من إندونيسيا", transliteration: "Anaa min Induuniisiyaa", meaningId: "Saya dari Indonesia", type: "fusha" },
      { arabic: "أنا إندونيسي", transliteration: "Anaa Induuniisiyy", meaningId: "Saya orang Indonesia (laki-laki)", type: "fusha" },
      { arabic: "أنا إندونيسية", transliteration: "Anaa Induuniisiyyah", meaningId: "Saya orang Indonesia (perempuan)", type: "fusha" },
      { arabic: "تشرفنا", transliteration: "Tasyarrafnaa", meaningId: "Senang berkenalan", type: "fusha" },
      { arabic: "ما اسمك؟", transliteration: "Maa ismuk?", meaningId: "Siapa namamu? (laki-laki)", type: "fusha" },
      { arabic: "ما اسمك؟", transliteration: "Maa ismuki?", meaningId: "Siapa namamu? (perempuan)", type: "fusha", usageNote: "ditandai bunyi i di akhir untuk perempuan" },
      { arabic: "أعمل هنا", transliteration: "A‘malu hunaa", meaningId: "Saya bekerja di sini", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Kolega", arabic: "السلام عليكم، ما اسمك؟", transliteration: "Assalamu ‘alaikum, maa ismuk?", meaningId: "Assalamu’alaikum, siapa namamu?", type: "fusha" },
      { speaker: "Kamu", arabic: "وعليكم السلام، اسمي بُدي.", transliteration: "Wa ‘alaikumussalam, ismii Budi.", meaningId: "Wa’alaikumussalam, nama saya Budi.", type: "fusha" },
      { speaker: "Kolega", arabic: "من أين أنت؟", transliteration: "Min aina anta?", meaningId: "Kamu dari mana?", type: "fusha" },
      { speaker: "Kamu", arabic: "أنا من إندونيسيا، أعمل هنا.", transliteration: "Anaa min Induuniisiyaa, a‘malu hunaa.", meaningId: "Saya dari Indonesia, saya bekerja di sini.", type: "fusha" },
      { speaker: "Kolega", arabic: "تشرفنا.", transliteration: "Tasyarrafnaa.", meaningId: "Senang berkenalan.", type: "fusha" },
    ],
    practicePrompts: [
      "Latih perkenalan diri 3 kalimat: nama, asal, pekerjaan.",
      "Tulis 2 versi: untuk laki-laki dan untuk perempuan.",
      "Coba rekam suaramu memperkenalkan diri lalu dengar ulang.",
    ],
    quiz: [
      {
        id: "L1M2L2Q1",
        lessonId: "L1M2L2",
        questionType: "meaning",
        promptId: "Bagaimana cara mengatakan 'Nama saya Budi' dalam Arab?",
        options: ["اسمي بُدي", "أنا بُدي اسمي", "بُدي اسمي أنا", "اسم أنا بُدي"],
        correctAnswer: "اسمي بُدي",
        explanationId: "Pola: اسمي + nama. اسمي بُدي = nama saya Budi.",
        difficulty: "easy",
      },
      {
        id: "L1M2L2Q2",
        lessonId: "L1M2L2",
        questionType: "situation",
        promptId: "Kolegamu bertanya من أين أنت؟ artinya 'kamu dari mana?'. Jawaban yang benar untuk pekerja Indonesia?",
        arabicText: "من أين أنت؟",
        options: ["أنا من إندونيسيا", "اسمي بُدي", "تشرفنا", "صباح الخير"],
        correctAnswer: "أنا من إندونيسيا",
        explanationId: "أنا من إندونيسيا = saya dari Indonesia.",
        difficulty: "easy",
      },
      {
        id: "L1M2L2Q3",
        lessonId: "L1M2L2",
        questionType: "meaning",
        promptId: "Apa arti تشرفنا dalam konteks perkenalan?",
        arabicText: "تشرفنا",
        transliteration: "Tasyarrafnaa",
        options: ["Senang berkenalan", "Selamat tinggal", "Maaf", "Saya tidak mengerti"],
        correctAnswer: "Senang berkenalan",
        explanationId: "تشرفنا adalah respon sopan saat baru kenalan.",
        difficulty: "medium",
      },
      {
        id: "L1M2L2Q4",
        lessonId: "L1M2L2",
        questionType: "meaning",
        promptId: "أعمل هنا artinya?",
        arabicText: "أعمل هنا",
        transliteration: "A‘malu hunaa",
        options: ["Saya bekerja di sini", "Saya tinggal di sini", "Saya lewat di sini", "Saya pernah di sini"],
        correctAnswer: "Saya bekerja di sini",
        explanationId: "أعمل = saya bekerja; هنا = di sini.",
        difficulty: "medium",
      },
      {
        id: "L1M2L2Q5",
        lessonId: "L1M2L2",
        questionType: "vocabulary",
        promptId: "Untuk perempuan Indonesia, cara mengucapkan 'Saya orang Indonesia' adalah?",
        options: ["أنا إندونيسية", "أنا إندونيسي", "أنا من سعودية", "أنا من إندونيسي"],
        correctAnswer: "أنا إندونيسية",
        explanationId: "Versi perempuan ditandai akhiran ة (ta marbuta): إندونيسية.",
        difficulty: "medium",
      },
      {
        id: "L1M2L2Q6",
        lessonId: "L1M2L2",
        questionType: "situation",
        promptId: "Atasan barumu bilang أهلاً وسهلاً lalu ما اسمك؟. Apa langkah respons yang paling tepat?",
        options: ["Sebut nama dengan اسمي + nama", "Diam saja", "Tanya balik من أين أنت", "Pergi"],
        correctAnswer: "Sebut nama dengan اسمي + nama",
        explanationId: "Setelah disambut dan ditanya nama, sebutkan nama dengan pola اسمي + nama.",
        difficulty: "easy",
      },
    ],
  },
];
