import type { ArabicLesson } from "../types";

export const level5Lessons: ArabicLesson[] = [
  {
    id: "L5M15L1",
    appSlug: "arabic",
    level: "L5_TRAVEL",
    levelTitle: "Travel & Social Conversation",
    moduleId: "M15",
    moduleTitle: "Small Talk with Locals",
    lessonTitle: "Ngobrol Ringan dengan Orang Saudi",
    order: 17,
    scenario: "Di restoran, taksi, atau toko, kamu ingin ngobrol singkat dengan orang Saudi untuk bangun rasa nyaman.",
    targetSkill: "travel",
    arabicType: "mixed",
    explanationId:
      "Small talk pakai pertanyaan ringan: dari mana, sudah berapa lama di Saudi, suka apa di sini. Jawab singkat dan tulus. Orang Saudi suka kalau tamu menunjukkan rasa hormat ke negara mereka.",
    saudiNote: "Pujian ringan ke makanan, masjid, atau cuaca Saudi adalah pembuka percakapan yang aman dan sopan.",
    vocabulary: [
      { arabic: "من أين أنت؟", transliteration: "Min aina anta?", meaningId: "Kamu dari mana?", type: "fusha" },
      { arabic: "أنا من إندونيسيا", transliteration: "Anaa min Induuniisiyaa", meaningId: "Saya dari Indonesia", type: "fusha" },
      { arabic: "كم مدة وجودك هنا؟", transliteration: "Kam muddat wujuudik hunaa?", meaningId: "Sudah berapa lama di sini?", type: "fusha" },
      { arabic: "أحب السعودية", transliteration: "Uhibbu as-Su‘uudiyyah", meaningId: "Saya suka Arab Saudi", type: "fusha" },
      { arabic: "الطعام لذيذ", transliteration: "Ath-tha‘aam ladziidz", meaningId: "Makanannya enak", type: "fusha" },
      { arabic: "الحرم جميل", transliteration: "Al-haram jamiil", meaningId: "Masjid Haram indah", type: "fusha" },
      { arabic: "أول مرة", transliteration: "Awwal marrah", meaningId: "Pertama kali", type: "fusha" },
      { arabic: "إن شاء الله", transliteration: "Inshaa Allah", meaningId: "Insya Allah", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Saudi", arabic: "من أين أنت؟", transliteration: "Min aina anta?", meaningId: "Kamu dari mana?", type: "fusha" },
      { speaker: "Kamu", arabic: "أنا من إندونيسيا.", transliteration: "Anaa min Induuniisiyaa.", meaningId: "Saya dari Indonesia.", type: "fusha" },
      { speaker: "Saudi", arabic: "أهلاً وسهلاً! أول مرة؟", transliteration: "Ahlan wa sahlan! Awwal marrah?", meaningId: "Selamat datang! Pertama kali ke sini?", type: "fusha" },
      { speaker: "Kamu", arabic: "نعم، أول مرة. أحب السعودية والحرم جميل.", transliteration: "Na‘am, awwal marrah. Uhibbu as-Su‘uudiyyah wa al-haram jamiil.", meaningId: "Ya, pertama kali. Saya suka Arab Saudi dan Masjid Haram indah.", type: "fusha" },
      { speaker: "Saudi", arabic: "ما شاء الله، الله يقبل عمرتك.", transliteration: "Maa syaa Allah, Allah yaqbal ‘umratak.", meaningId: "Masya Allah, semoga umrahmu diterima.", type: "fusha" },
    ],
    practicePrompts: [
      "Latih pasang kalimat: 'saya dari Indonesia + pertama kali'.",
      "Tulis 3 pujian sopan untuk Saudi: makanan, masjid, orang.",
      "Praktek respons saat dipuji: شكراً، إن شاء الله.",
    ],
    quiz: [
      {
        id: "L5M15L1Q1",
        lessonId: "L5M15L1",
        questionType: "situation",
        promptId: "Orang Saudi tanya 'kamu dari mana?'. Mana yang paling natural?",
        options: ["أنا من إندونيسيا", "صباح الخير", "تشرفنا", "كم السعر"],
        correctAnswer: "أنا من إندونيسيا",
        explanationId: "Jawaban natural: من + nama negara.",
        difficulty: "easy",
      },
      {
        id: "L5M15L1Q2",
        lessonId: "L5M15L1",
        questionType: "meaning",
        promptId: "أول مرة artinya?",
        arabicText: "أول مرة",
        transliteration: "Awwal marrah",
        options: ["Pertama kali", "Kedua kali", "Sebentar lagi", "Sangat lama"],
        correctAnswer: "Pertama kali",
        explanationId: "أول = pertama; مرة = kali.",
        difficulty: "easy",
      },
      {
        id: "L5M15L1Q3",
        lessonId: "L5M15L1",
        questionType: "situation",
        promptId: "Kamu mau memuji makanan Saudi. Mana yang paling natural?",
        options: ["الطعام لذيذ", "الطعام غالي", "أنا متأخر", "أبغى قهوة"],
        correctAnswer: "الطعام لذيذ",
        explanationId: "الطعام = makanan; لذيذ = enak.",
        difficulty: "easy",
      },
      {
        id: "L5M15L1Q4",
        lessonId: "L5M15L1",
        questionType: "meaning",
        promptId: "Saat dipuji, orang Saudi sering bilang ما شاء الله. Artinya?",
        arabicText: "ما شاء الله",
        transliteration: "Maa syaa Allah",
        options: ["Apa yang Allah kehendaki / pujian", "Aku tidak tahu", "Selamat tinggal", "Maaf"],
        correctAnswer: "Apa yang Allah kehendaki / pujian",
        explanationId: "Ungkapan kagum / pujian yang umum digunakan oleh Muslim.",
        difficulty: "medium",
      },
      {
        id: "L5M15L1Q5",
        lessonId: "L5M15L1",
        questionType: "meaning",
        promptId: "أحب السعودية artinya?",
        arabicText: "أحب السعودية",
        transliteration: "Uhibbu as-Su‘uudiyyah",
        options: ["Saya suka Arab Saudi", "Saya tinggal di Saudi", "Saya kerja di Saudi", "Saya lewat Saudi"],
        correctAnswer: "Saya suka Arab Saudi",
        explanationId: "أحب = saya suka/cinta; السعودية = Arab Saudi.",
        difficulty: "easy",
      },
      {
        id: "L5M15L1Q6",
        lessonId: "L5M15L1",
        questionType: "saudi_expression",
        promptId: "Saat orang Saudi bilang إن شاء الله, kamu sebaiknya?",
        arabicText: "إن شاء الله",
        options: ["Setuju, balas inshaa Allah", "Tolak halus", "Tanya kembali", "Diam saja"],
        correctAnswer: "Setuju, balas inshaa Allah",
        explanationId: "إن شاء الله dipakai sangat sering. Cara natural: balas dengan إن شاء الله juga.",
        difficulty: "medium",
      },
    ],
  },
  {
    id: "L5M16L1",
    appSlug: "arabic",
    level: "L5_TRAVEL",
    levelTitle: "Travel & Social Conversation",
    moduleId: "M16",
    moduleTitle: "Travel Problem Solving",
    lessonTitle: "Masalah Travel: Hilang, Salah Arah, WiFi",
    order: 18,
    scenario: "Kamu kehilangan barang, salah alamat hotel, ketinggalan bus jamaah, atau butuh WiFi cepat untuk hubungi keluarga.",
    targetSkill: "travel",
    arabicType: "mixed",
    explanationId:
      "Pakai pola فقدت + barang untuk 'saya kehilangan'. Untuk alamat salah: العنوان خطأ. Untuk bus ketinggalan: فاتني الباص. Tanya WiFi: واي فاي + موجود؟",
    saudiNote: "Bus jamaah biasanya berangkat tepat waktu. Kalau ketinggalan, segera hubungi tour leader atau cari shuttle gratis di sekitar masjid.",
    vocabulary: [
      { arabic: "فقدت", transliteration: "Faqadtu", meaningId: "Saya kehilangan", type: "fusha" },
      { arabic: "هاتفي", transliteration: "Haatifii", meaningId: "HP saya", type: "fusha" },
      { arabic: "محفظتي", transliteration: "Mihfazhatii", meaningId: "Dompet saya", type: "fusha" },
      { arabic: "العنوان خطأ", transliteration: "Al-‘unwaan khatha’", meaningId: "Alamatnya salah", type: "fusha" },
      { arabic: "فاتني الباص", transliteration: "Faatanii al-baash", meaningId: "Saya ketinggalan bus", type: "mixed" },
      { arabic: "هل يوجد واي فاي؟", transliteration: "Hal yuujadu waay-faay?", meaningId: "Apakah ada WiFi?", type: "mixed" },
      { arabic: "ساعدني من فضلك", transliteration: "Saa‘idnii min fadhlik", meaningId: "Tolong saya", type: "fusha" },
      { arabic: "مكتب المفقودات", transliteration: "Maktab al-mafquudaat", meaningId: "Lost and found", type: "fusha" },
    ],
    dialogue: [
      { speaker: "Kamu", arabic: "ساعدني من فضلك، فقدت محفظتي.", transliteration: "Saa‘idnii min fadhlik, faqadtu mihfazhatii.", meaningId: "Tolong saya, saya kehilangan dompet.", type: "fusha" },
      { speaker: "Petugas", arabic: "أين فقدتها؟", transliteration: "Aina faqadtahaa?", meaningId: "Di mana kamu kehilangannya?", type: "fusha" },
      { speaker: "Kamu", arabic: "قرب الحرم. أين مكتب المفقودات؟", transliteration: "Qurba al-haram. Aina maktab al-mafquudaat?", meaningId: "Dekat Masjid Haram. Di mana lost and found?", type: "fusha" },
      { speaker: "Petugas", arabic: "تعال معي.", transliteration: "Ta‘aal ma‘ii.", meaningId: "Ikut saya.", type: "fusha" },
    ],
    practicePrompts: [
      "Latih kalimat 'saya kehilangan dompet' dan 'saya kehilangan HP'.",
      "Tulis 1 kalimat: 'apakah ada WiFi di sini?'.",
      "Hafal 'lost and found' (مكتب المفقودات).",
    ],
    quiz: [
      {
        id: "L5M16L1Q1",
        lessonId: "L5M16L1",
        questionType: "situation",
        promptId: "Bagaimana mengatakan 'Saya kehilangan dompet'?",
        options: ["فقدت محفظتي", "فقدت هاتفي", "فقدت طريقي", "أبغى محفظة"],
        correctAnswer: "فقدت محفظتي",
        explanationId: "فقدت = saya kehilangan; محفظتي = dompet saya.",
        difficulty: "medium",
      },
      {
        id: "L5M16L1Q2",
        lessonId: "L5M16L1",
        questionType: "situation",
        promptId: "Kamu ketinggalan bus jamaah. Mana yang paling tepat?",
        options: ["فاتني الباص", "أبغى باص", "كم سعر الباص", "أين الباص"],
        correctAnswer: "فاتني الباص",
        explanationId: "فاتني = (sesuatu) terlewat dari saya; الباص = bus.",
        difficulty: "medium",
      },
      {
        id: "L5M16L1Q3",
        lessonId: "L5M16L1",
        questionType: "vocabulary",
        promptId: "مكتب المفقودات artinya?",
        arabicText: "مكتب المفقودات",
        transliteration: "Maktab al-mafquudaat",
        options: ["Lost and found", "Tour office", "Hotel reception", "Bank"],
        correctAnswer: "Lost and found",
        explanationId: "مكتب = kantor; المفقودات = barang hilang.",
        difficulty: "medium",
      },
      {
        id: "L5M16L1Q4",
        lessonId: "L5M16L1",
        questionType: "situation",
        promptId: "Kamu mau tanya 'apakah ada WiFi di sini?'. Mana yang paling natural?",
        options: ["هل يوجد واي فاي؟", "كم السعر؟", "أين البوابة؟", "أنا تعبان"],
        correctAnswer: "هل يوجد واي فاي؟",
        explanationId: "هل يوجد = apakah ada; واي فاي = WiFi.",
        difficulty: "medium",
      },
      {
        id: "L5M16L1Q5",
        lessonId: "L5M16L1",
        questionType: "meaning",
        promptId: "العنوان خطأ artinya?",
        arabicText: "العنوان خطأ",
        transliteration: "Al-‘unwaan khatha’",
        options: ["Alamatnya salah", "Alamatnya benar", "Alamatnya jauh", "Alamatnya dekat"],
        correctAnswer: "Alamatnya salah",
        explanationId: "العنوان = alamat; خطأ = salah.",
        difficulty: "medium",
      },
      {
        id: "L5M16L1Q6",
        lessonId: "L5M16L1",
        questionType: "situation",
        promptId: "Petugas tanya أين فقدتها؟. Kamu sebaiknya jawab apa?",
        arabicText: "أين فقدتها؟",
        options: ["Sebutkan lokasi terakhir kamu lihat barangnya", "Sebut harga barangnya", "Sebut warna barangnya", "Sebutkan namamu"],
        correctAnswer: "Sebutkan lokasi terakhir kamu lihat barangnya",
        explanationId: "Petugas tanya 'di mana kamu kehilangannya?'. Jawab lokasi.",
        difficulty: "medium",
      },
    ],
  },
];
