export const platformApps = [
  {
    id: "nihongo",
    slug: "nihongo",
    name: "Nexus Talenta Indonesia Academy",
    description: "Japanese, language, and career-preparation academy for Indonesian learners",
    href: "/apps/nihongo/dashboard",
    status: "active",
  },
  {
    id: "english",
    slug: "english",
    name: "Nexus AI English",
    description: "AI English interview practice for overseas work applications",
    href: "/apps/english/dashboard",
    status: "active",
  },
  {
    id: "arabic",
    slug: "arabic",
    name: "Nexus AI Arabic",
    description: "Daily Saudi Arabic for work, umrah, and travel — built for Indonesian speakers",
    href: "/apps/arabic/dashboard",
    status: "active",
  },
  {
    id: "lessons",
    slug: "lessons",
    name: "Nexus Lessons",
    description: "Reusable lesson engine for future Nexus learning apps",
    href: "/apps/lessons/dashboard",
    status: "coming_soon",
  },
  {
    id: "pmp",
    slug: "pmp",
    name: "PMP Exam Prep",
    description: "PMP exam prep — lessons, drills, and full-length simulations.",
    href: "/apps/pmp/dashboard",
    status: "active",
  },
];
