/**
 * Curated, comprehensive PMP Knowledge Base content authored for Nexus PMP Academy.
 * Original wording — does not copy from PMI publications or commercial prep providers.
 * The text intentionally explains concepts so Andromeda (the AI Instructor) and the
 * static articles speak with the same depth and structure.
 */

export type CuratedArticle = {
  slug: string;
  title: string;
  category: string;
  domain: "People" | "Process" | "Business Environment";
  approach: "general" | "agile" | "hybrid" | "predictive";
  examVersion: "current" | "2026" | "both";
  summary: string;
  content: string;
  keyTakeaways: string[];
  studyTip: string;
  relatedTerms: string[];
};

export const CURATED_ARTICLES: CuratedArticle[] = [
  // -------------------------------------------------------------------------
  // PROCUREMENT — DEEP TRACK
  // -------------------------------------------------------------------------
  {
    slug: "procurement-overview",
    title: "Procurement Management — End-to-End Overview",
    category: "Procurement",
    domain: "Process",
    approach: "general",
    examVersion: "both",
    summary:
      "Bagaimana project membeli barang/jasa dari pihak luar: dari make-or-buy, plan procurement, conduct procurement, sampai control procurement dan close.",
    content: [
      "## Apa Itu Procurement Dalam Project",
      "Procurement adalah proses formal mendapatkan barang atau jasa dari pihak di luar tim project. Hubungan yang dibentuk adalah hubungan kontraktual yang mengikat secara hukum, bukan sekadar arrangement informal. Karena itu PMP memperlakukan procurement sebagai high-stakes process yang harus didokumentasikan rapi, dieksekusi sesuai agreement, dan diawasi sampai penutupan.",
      "## Tiga Proses Inti Procurement",
      "**1. Plan Procurement Management (Planning).** Menentukan apa yang akan dibeli, kapan, dari siapa, dengan kontrak jenis apa, dan kriteria seleksi seperti apa. Output utamanya adalah Procurement Management Plan, Procurement Strategy, Procurement Statement of Work (SOW), Source Selection Criteria, Bid Documents, dan Make-or-Buy Decisions.",
      "**2. Conduct Procurements (Executing).** Mengeluarkan dokumen solicitation (RFI/RFQ/RFP/IFB), menerima proposal, mengevaluasi seller, lalu menandatangani agreement. Output utamanya adalah Selected Sellers dan Agreements (contracts).",
      "**3. Control Procurements (Monitoring & Controlling).** Memastikan seller dan buyer sama-sama menjalankan kewajiban dalam contract — monitoring performance, mengelola perubahan, menangani claims, dan menutup procurement saat selesai. Output: Closed Procurements, Work Performance Information, Change Requests.",
      "## Make-or-Buy: Pertanyaan Awal",
      "Sebelum menulis RFP, project manager harus tahu jawaban dari analisis make-or-buy: lebih baik dibuat sendiri (internal capability + cost lebih rendah + IP sensitif) atau dibeli (vendor lebih cepat, lebih murah, atau punya keahlian khusus). Faktor yang dipertimbangkan: kapasitas tim, risiko teknis, biaya total kepemilikan, kecepatan time-to-market, dan strategic alignment.",
      "## Procurement Documents Vocabulary",
      "**Bid documents** (the buyer issues these to sellers): RFI, RFQ, RFP, IFB.\n**Procurement Statement of Work (SOW):** dokumen yang menjabarkan ruang lingkup pekerjaan yang akan dibeli — bisa performance (apa yang harus dicapai), functional (kemampuan yang dibutuhkan), atau design (bagaimana harus dibuat).\n**Source Selection Criteria:** kriteria evaluasi seller yang disepakati sebelum proposal datang, supaya keputusan obyektif. Contoh: capability, capacity, technical approach, past performance, price, risk, references.\n**Agreement / Contract:** dokumen legal hasil negosiasi. Bisa berbentuk MSA + SOW, purchase order, NDA, MOU, atau letter of intent.",
      "## Buyer vs Seller — Perspektif Yang Penting di Exam",
      "PMP sering mengambil sudut pandang **buyer** (organisasi project yang membeli). Tapi soal bisa juga menempatkan lo sebagai **seller** (vendor yang menerima kontrak). Hati-hati membaca pertanyaan — strategi response berbeda. Buyer fokus ke value, control, dan compliance. Seller fokus ke margin, scope creep prevention, dan relationship management.",
      "## Andromeda's Takeaway",
      "Procurement bukan sekadar 'beli barang'. Ini risk allocation yang ditulis di kertas. Kalau scope jelas dan ingin seller menanggung risiko → kontrak fixed-price. Kalau scope masih kabur dan buyer harus fleksibel → cost-reimbursable. Selalu mulai dari make-or-buy, lewatin source selection yang adil, dan dokumentasikan semuanya — terutama perubahan dan klaim.",
    ].join("\n\n"),
    keyTakeaways: [
      "3 proses procurement: Plan, Conduct, Control.",
      "Bid documents: RFI (info), RFQ (price), RFP (proposal), IFB (sealed bid).",
      "Source selection criteria harus disepakati SEBELUM proposal datang.",
      "Make-or-buy adalah pertanyaan strategis yang menentukan semua langkah berikut.",
    ],
    studyTip:
      "Bedakan 3 hal yang sering tertukar: SOW (apa yang dibeli), source selection criteria (cara memilih), dan contract type (cara risiko dibagi).",
    relatedTerms: ["RFI", "RFQ", "RFP", "IFB", "Contract Types", "Make-or-Buy Analysis", "Source Selection Criteria"],
  },
  {
    slug: "rfi-rfq-rfp-ifb-explained",
    title: "RFI vs RFQ vs RFP vs IFB — When to Use Which",
    category: "Procurement",
    domain: "Process",
    approach: "general",
    examVersion: "both",
    summary:
      "Empat dokumen solicitation yang sering tertukar — kapan masing-masing dipakai, apa yang diminta, dan jebakan exam yang biasanya muncul.",
    content: [
      "## Empat Dokumen Solicitation Utama",
      "**RFI — Request for Information.** Buyer belum tahu solusinya, belum tahu vendor mana yang capable. RFI dipakai untuk men-survey pasar: 'tolong jelasin kapabilitas kalian, range harga, dan apakah project seperti ini biasa kalian kerjakan'. Tidak menghasilkan kontrak — hanya menginformasikan tahap berikutnya. Bahasa kuncinya: *exploring, learning, market scan*.",
      "**RFQ — Request for Quotation.** Buyer sudah tahu PERSIS apa yang dibutuhkan, hanya butuh price. Cocok untuk barang/jasa standar (laptop, lisensi software dengan SKU jelas, sewa kendaraan). Evaluasi hampir murni harga. Bahasa kuncinya: *price, unit cost, lead time*.",
      "**RFP — Request for Proposal.** Buyer tahu masalahnya tapi mau seller mengusulkan **bagaimana** menyelesaikannya. Cocok untuk pekerjaan kompleks (system integration, consulting engagement, custom development). Evaluasi mempertimbangkan technical approach, methodology, team, past performance, price, risk. Bahasa kuncinya: *approach, methodology, team, value*.",
      "**IFB — Invitation for Bid (a.k.a. Invitation to Tender).** Sealed bid — buyer mengundang banyak seller untuk mengajukan penawaran TERTUTUP, biasanya untuk pekerjaan yang scope-nya sudah sangat jelas dan keputusan didasarkan pada harga terendah yang memenuhi spesifikasi. Sering dipakai di sektor publik / pemerintahan karena auditable dan transparan. Bahasa kuncinya: *sealed bid, lowest qualified bid, public procurement*.",
      "## Tabel Pembanding",
      "| Dokumen | Buyer sudah tahu apa? | Yang diminta dari seller | Basis evaluasi |",
      "|---|---|---|---|",
      "| RFI | Belum tahu solusi | Informasi & kapabilitas | Tidak ada kontrak |",
      "| RFQ | Tahu persis spec, mau harga | Harga + lead time | Mostly price |",
      "| RFP | Tahu masalah, ingin solusi | Proposal teknis + harga | Best value (multi-criteria) |",
      "| IFB | Tahu persis spec, formal | Sealed bid | Lowest qualified bid |",
      "## Exam Trap",
      "Soal sering menjebak antara RFQ dan RFP. Kunci: kalau buyer ingin seller **mengusulkan pendekatan**, itu RFP. Kalau buyer cuma butuh **harga** untuk spec yang sudah lengkap, itu RFQ. Soal juga bisa mencampur urutan — biasanya RFI dipakai dulu, lalu hasilnya digunakan untuk menyusun RFP atau RFQ ke shortlisted vendors.",
      "## Andromeda's Takeaway",
      "Hafalkan satu kalimat: **RFI cari tahu, RFQ cari harga, RFP cari cara, IFB cari sealed bid termurah yang qualified.**",
    ].join("\n\n"),
    keyTakeaways: [
      "RFI = mencari informasi pasar, bukan kontrak.",
      "RFQ = harga untuk spec yang jelas.",
      "RFP = proposal teknis untuk masalah kompleks.",
      "IFB = sealed bid, biasanya sektor publik atau scope sangat jelas.",
    ],
    studyTip:
      "Kalau soal bilang 'buyer ingin tahu pendekatan teknis seller', itu RFP. Kalau 'buyer ingin harga untuk laptop model X', itu RFQ.",
    relatedTerms: ["Procurement", "Bid Documents", "Source Selection", "Contract Types"],
  },
  {
    slug: "contract-types-comprehensive",
    title: "Contract Types — FFP, FPIF, FPEPA, T&M, CPFF, CPIF, CPAF",
    category: "Procurement",
    domain: "Process",
    approach: "general",
    examVersion: "both",
    summary:
      "Semua tipe kontrak PMP, lengkap dengan siapa yang menanggung risiko, kapan dipakai, dan rumus incentive yang sering muncul di soal.",
    content: [
      "## Tiga Kategori Besar Kontrak",
      "**Fixed-Price (FP)** — harga ditetapkan di muka, seller menanggung risiko cost overrun. Buyer-friendly bila scope jelas.",
      "**Cost-Reimbursable (CR)** — buyer mengganti biaya aktual seller plus fee. Buyer menanggung lebih banyak risiko, cocok bila scope belum jelas atau evolving.",
      "**Time & Material (T&M)** — hybrid. Buyer bayar per jam (rate disepakati) plus material at cost. Risiko terbagi. Cocok untuk pekerjaan kecil, augmentasi staf, atau emergency response.",
      "## Fixed-Price Family",
      "**FFP — Firm Fixed Price.** Harga total disepakati di muka dan tidak berubah. Buyer paling enak. Seller punya insentif untuk efisien (semua saving = profit), tapi juga semua loss = kerugian seller. Cocok ketika scope sangat jelas dan stabil.",
      "**FPIF — Fixed Price Incentive Fee.** Harga dasar + insentif berdasarkan performance (biasanya cost atau schedule). Mekanisme klasik: Target Cost + Target Fee, dengan share ratio (mis. 80/20 buyer/seller). Ada price ceiling — di atas itu, semua biaya tambahan ditanggung seller.\n\n**Rumus FPIF yang sering muncul:**\n`Final Fee = Target Fee + ((Target Cost − Actual Cost) × Seller Share)`\n`Final Price = Actual Cost + Final Fee` (capped at Price Ceiling)",
      "**FPEPA — Fixed Price with Economic Price Adjustment.** Harga fixed tapi disesuaikan menurut indeks ekonomi (misalnya inflasi, nilai tukar) untuk kontrak multi-tahun. Melindungi seller dari volatilitas makro tanpa mengubah kontrak inti.",
      "## Cost-Reimbursable Family",
      "**CPFF — Cost Plus Fixed Fee.** Buyer mengganti seluruh allowable cost + fee tetap (fixed dollar amount, bukan persentase). Seller tidak punya insentif untuk efisien karena fee tidak berubah, tapi juga tidak punya alasan untuk inflate cost (fee tidak ikut naik). Risiko buyer paling besar.",
      "**CPIF — Cost Plus Incentive Fee.** Buyer mengganti cost + base fee + insentif berdasarkan performance. Mirip FPIF tapi base-nya cost-reimbursable.\n\n**Rumus CPIF:**\n`Total Fee = Target Fee + ((Target Cost − Actual Cost) × Seller Share)`\n`Total Reimbursement = Actual Cost + Total Fee`",
      "**CPAF — Cost Plus Award Fee.** Buyer mengganti cost + fee dasar + award fee yang ditentukan SECARA SUBYEKTIF oleh buyer berdasarkan kriteria kinerja kualitatif (mis. quality, responsiveness, collaboration). Award fee tidak bisa diappeal. Cocok ketika hasil sulit diukur kuantitatif tapi quality jelas penting.",
      "## Tabel Risiko",
      "| Tipe | Risiko Buyer | Risiko Seller | Cocok Untuk |",
      "|---|---|---|---|",
      "| FFP | Rendah | Tinggi | Scope sangat jelas |",
      "| FPIF | Rendah-Sedang | Sedang | Scope jelas + ingin reward efisiensi |",
      "| FPEPA | Rendah | Sedang | Kontrak panjang, exposure ekonomi |",
      "| T&M | Sedang | Sedang | Pekerjaan kecil / staf augmentation |",
      "| CPIF | Sedang | Rendah-Sedang | Scope evolving + ingin reward efisiensi |",
      "| CPAF | Sedang-Tinggi | Rendah | Kualitas subyektif, kriteria kualitatif |",
      "| CPFF | Tinggi | Rendah | R&D, scope tidak bisa di-fix |",
      "## Selecting the Right Contract Type",
      "Pertanyaan kunci: **Seberapa jelas scope?** Scope sangat jelas → FFP. Scope cukup jelas + ingin incentive efisiensi → FPIF. Scope kabur / R&D → CPFF atau CPIF. Pekerjaan jangka pendek / urgensi tinggi → T&M. Output evaluatif kualitatif → CPAF. Multi-year + risiko ekonomi → FPEPA.",
      "## Andromeda's Takeaway",
      "Kontrak adalah RISK ALLOCATION DOCUMENT. Semakin jelas scope, semakin enak menggeser risiko ke seller (fixed-price). Semakin kabur scope, buyer harus menanggung lebih banyak risiko (cost-reimbursable). T&M adalah jembatan kompromi untuk pekerjaan kecil.",
    ].join("\n\n"),
    keyTakeaways: [
      "FP family: seller menanggung risiko cost overrun.",
      "CR family: buyer menanggung risiko cost; insentif/award menggeser fee.",
      "T&M = rate × hours + material — risiko terbagi.",
      "Rumus incentive: Final Fee = Target Fee + ((Target Cost − Actual Cost) × Seller Share).",
    ],
    studyTip:
      "Latih 3 hitungan FPIF + CPIF dengan target cost & share ratio berbeda. Soal hitungan kontrak hampir selalu muncul dengan pola yang sama.",
    relatedTerms: ["FFP", "FPIF", "CPFF", "CPIF", "CPAF", "Time and Material", "Procurement"],
  },
  {
    slug: "source-selection-and-claims",
    title: "Source Selection, Bidder Conference, dan Claims Administration",
    category: "Procurement",
    domain: "Process",
    approach: "general",
    examVersion: "both",
    summary:
      "Bagaimana memilih seller secara adil, menjalankan bidder conference, mengelola klaim ketika terjadi sengketa, dan menutup procurement.",
    content: [
      "## Source Selection — Memilih Seller",
      "Source selection harus obyektif, dapat diaudit, dan disepakati sebelum proposal datang. Kriteria umum yang dipakai pada weighted scoring model:",
      "- **Capability & Capacity** — apakah seller mampu dan punya kapasitas mengerjakan ini sekarang?",
      "- **Technical Approach** — kualitas pendekatan yang diusulkan.",
      "- **Past Performance & References** — track record di proyek serupa.",
      "- **Management Approach** — tim, governance, communication plan.",
      "- **Risk** — risiko teknis, komersial, dan operasional.",
      "- **Price / Total Cost of Ownership** — bukan cuma price, tapi TCO.",
      "- **Warranty, IP, Confidentiality, Compliance** — terutama untuk regulated industries.",
      "Setiap kriteria diberi bobot (mis. 25% technical, 20% past performance, 30% price, dst), lalu setiap proposal di-score. Ini menghindari bias dan membuat keputusan defensible.",
      "## Bidder Conference (Pre-Bid Meeting)",
      "Pertemuan formal antara buyer dan SEMUA prospective sellers SEBELUM proposal dikirim. Tujuannya:",
      "1. Memastikan semua seller punya pemahaman yang sama tentang SOW.",
      "2. Memberi kesempatan menanyakan klarifikasi — semua pertanyaan dan jawabannya dibagikan ke semua peserta.",
      "3. Mencegah bias atau keuntungan informasi sepihak.",
      "Setelah bidder conference, biasanya buyer mengeluarkan amendments tertulis jika ada klarifikasi penting. Yang TIDAK boleh dilakukan: pertemuan terpisah dengan satu seller saja yang membahas detail SOW (unfair advantage).",
      "## Claims Administration",
      "Claim = perselisihan formal antara buyer dan seller tentang scope, performance, harga, atau penyelesaian. Claim TIDAK langsung berarti litigation. Process-nya bertingkat:",
      "1. **Documentation** — dokumentasi dampak, korespondensi, dan basis klaim.",
      "2. **Negotiation** — kedua pihak mencoba menyelesaikan secara langsung. Sering paling murah dan cepat.",
      "3. **Alternative Dispute Resolution (ADR)** — mediation (mediator netral memfasilitasi) atau arbitration (arbiter memutuskan, biasanya binding). ADR lebih cepat dan murah dari pengadilan.",
      "4. **Litigation** — last resort. Mahal, lama, dan biasanya merusak hubungan.",
      "PMI mindset: selalu coba selesaikan di level paling rendah dulu. Litigation hanya bila pihak lain menolak good-faith negotiation.",
      "## Closing Procurements",
      "Procurement ditutup ketika SEMUA deliverable diterima dan SEMUA klaim diselesaikan. Aktivitas:",
      "- Verifikasi semua deliverable sesuai SOW.",
      "- Penyelesaian klaim outstanding.",
      "- Final payment dan release of liens.",
      "- Update Lessons Learned Register dan OPA dengan apa yang dipelajari dari seller ini.",
      "- Surat penutupan formal (formal acceptance / contract closeout).",
      "## Andromeda's Takeaway",
      "Procurement bersifat formal karena ikatan legal. Jangan pernah lompat ke penalty atau termination tanpa documentation + negotiation + ADR dulu. Soal PMP yang menyebut 'vendor terlambat' hampir selalu diselesaikan dengan **meeting + diagnose + reference the agreement** — bukan dengan langsung melakukan penalty atau replacement.",
    ].join("\n\n"),
    keyTakeaways: [
      "Source selection criteria disepakati DI MUKA, bersifat obyektif dan auditable.",
      "Bidder conference = pertemuan terbuka untuk SEMUA seller, semua Q&A dibagikan.",
      "Claims: Documentation → Negotiation → ADR (mediation/arbitration) → Litigation.",
      "Close procurement hanya ketika deliverable accepted DAN claims settled.",
    ],
    studyTip:
      "Kalau soal mengatakan 'vendor missed deadline / SLA / workshop', jawaban benar hampir selalu mulai dengan 'meet with the vendor to understand the cause and align with the agreement', bukan penalty / replacement / escalation.",
    relatedTerms: ["Source Selection Criteria", "Bidder Conference", "Claims Administration", "ADR"],
  },

  // -------------------------------------------------------------------------
  // RISK
  // -------------------------------------------------------------------------
  {
    slug: "risk-management-deep",
    title: "Risk Management — Identification, Analysis, and Response",
    category: "Risk",
    domain: "Process",
    approach: "general",
    examVersion: "both",
    summary:
      "Pipeline risiko lengkap: identifikasi, kualitatif, kuantitatif (EMV, decision tree, Monte Carlo), strategi response (threat + opportunity), sampai monitoring.",
    content: [
      "## Risk vs Issue vs Change Request",
      "**Risk** — uncertainty yang BELUM terjadi, punya probability dan impact. Bisa positive (opportunity) atau negative (threat).\n**Issue** — sesuatu yang SUDAH terjadi dan butuh action sekarang. Dimasukkan ke Issue Log, bukan Risk Register.\n**Change Request** — usulan formal untuk mengubah baseline. Diproses lewat Integrated Change Control.",
      "## Pipeline Risk Management",
      "1. **Plan Risk Management** — bagaimana risiko akan dikelola, kategori (RBS), threshold.\n2. **Identify Risks** — brainstorming, SWOT, interview, premortem, checklist, prompt list.\n3. **Perform Qualitative Risk Analysis** — Probability/Impact matrix; prioritisasi.\n4. **Perform Quantitative Risk Analysis** — EMV, decision tree, Monte Carlo, sensitivity analysis (tornado chart).\n5. **Plan Risk Responses** — pilih strategi untuk risk teratas.\n6. **Implement Risk Responses** — eksekusi response yang sudah direncanakan.\n7. **Monitor Risks** — track residual risk, secondary risk, dan apakah trigger muncul.",
      "## Probability × Impact Matrix",
      "Setiap risiko di-score: probability (mis. 1–5 atau 10%–90%) dan impact (1–5 atau dollar). Score gabungan menentukan prioritas. Threshold ditetapkan di Risk Management Plan — misalnya 'risk dengan score ≥ 12 harus punya response plan'.",
      "## Quantitative Analysis",
      "**EMV — Expected Monetary Value.** `EMV = Probability × Impact (dalam $)`. Untuk decision tree, jumlahkan EMV semua cabang lalu pilih path dengan EMV tertinggi (kalau opportunity) atau terendah (kalau cost).",
      "**Decision Tree.** Diagram cabang yang membantu memilih di antara opsi yang punya hasil tidak pasti. Setiap cabang punya probability dan payoff.",
      "**Monte Carlo Simulation.** Simulasi ribuan iterasi dengan input random sesuai distribusi yang diasumsikan. Output bukan satu angka tapi distribusi (mis. 'ada 80% chance project selesai sebelum tanggal X').",
      "**Sensitivity Analysis / Tornado Chart.** Mengidentifikasi variable mana yang paling berpengaruh terhadap outcome.",
      "## Risk Response Strategies",
      "**Untuk Threats:**",
      "- **AVOID** — eliminate the risk (mis. ganti teknologi, hapus fitur berisiko).",
      "- **TRANSFER** — pindahkan risiko ke pihak lain (insurance, warranty, fixed-price contract ke vendor).",
      "- **MITIGATE** — kurangi probability atau impact (training, redundancy, prototype).",
      "- **ACCEPT** — terima risikonya (passive = no action, atau active = contingency reserve).",
      "- **ESCALATE** — risiko di luar kendali project, naikkan ke level program/portfolio.",
      "**Untuk Opportunities (positive risks):**",
      "- **EXPLOIT** — pastikan opportunity TERJADI (assign best team, prioritaskan).",
      "- **SHARE** — kerja sama dengan pihak lain untuk merealisasikan opportunity (JV, partnership).",
      "- **ENHANCE** — tingkatkan probability atau impact dari opportunity.",
      "- **ACCEPT** — terima saja kalau opportunity muncul, tanpa investasi.",
      "- **ESCALATE** — opportunity di luar scope project, naikkan ke level lebih tinggi.",
      "## Reserves",
      "**Contingency Reserve** — untuk **known unknowns** (risiko yang sudah teridentifikasi). Dimiliki project manager. Bagian dari cost baseline.",
      "**Management Reserve** — untuk **unknown unknowns** (risiko yang belum teridentifikasi). Dimiliki sponsor/management. TIDAK termasuk cost baseline tapi bagian dari project budget.",
      "## Secondary & Residual Risk",
      "**Secondary risk** — risiko baru yang muncul KARENA implementasi response. Contoh: mitigasi 'pakai vendor backup' menciptakan secondary risk 'vendor backup kualitas lebih rendah'.",
      "**Residual risk** — risiko yang TERSISA setelah response diimplementasikan. Tidak ada response yang menghilangkan risk sepenuhnya; residual harus diterima dan dimonitor.",
      "## Andromeda's Takeaway",
      "Risk management itu BUKAN tentang menghindari semua risiko. Itu tentang membuat keputusan SADAR di mana mau menanggung risiko, di mana mentransfer, dan di mana memitigasi. Soal exam yang menampilkan risiko biasanya menguji: apakah lo identifikasi → analisis → pilih strategy yang tepat → assign owner → set trigger.",
    ].join("\n\n"),
    keyTakeaways: [
      "Threat strategies: Avoid, Transfer, Mitigate, Accept, Escalate.",
      "Opportunity strategies: Exploit, Share, Enhance, Accept, Escalate.",
      "EMV = Probability × Impact. Sum across branches for decision trees.",
      "Contingency = known unknowns (PM). Management reserve = unknown unknowns (sponsor).",
      "Secondary risk = caused by response. Residual risk = leftover after response.",
    ],
    studyTip:
      "Hafal 5+5 strategies. Soal hampir selalu menampilkan satu scenario yang cocok dengan satu strategy spesifik — pilihan jawaban biasanya 4 strategy berbeda.",
    relatedTerms: ["Risk Register", "EMV", "Decision Tree", "Monte Carlo", "Contingency Reserve"],
  },

  // -------------------------------------------------------------------------
  // QUALITY
  // -------------------------------------------------------------------------
  {
    slug: "quality-tools-comprehensive",
    title: "Quality Tools — Pareto, Fishbone, Control Chart, dan 7 Basic Tools",
    category: "Quality",
    domain: "Process",
    approach: "general",
    examVersion: "both",
    summary:
      "Semua alat quality yang sering muncul di soal PMP: kapan dipakai, apa yang ditunjukkan, dan trap-nya.",
    content: [
      "## Konsep Dasar Quality",
      "**Quality** vs **Grade**: Quality = kesesuaian dengan requirement (non-negotiable; semua project harus quality). Grade = kategori atau kelas (low-grade product bisa tetap high quality).",
      "**Prevention** > **Inspection**: lebih murah mencegah cacat daripada menemukan dan memperbaikinya nanti.",
      "**Cost of Quality (COQ):**",
      "- Cost of **Conformance**: prevention (training, process, equipment) + appraisal (testing, audit, inspection).",
      "- Cost of **Non-Conformance**: internal failure (rework before delivery) + external failure (warranty claim, recall, customer churn, reputation).",
      "**Quality Assurance (QA)** = Plan Quality + Manage Quality — fokus PROSES, mencegah cacat.",
      "**Quality Control (QC)** = Control Quality — fokus PRODUK, inspeksi deliverable.",
      "## 7 Basic Quality Tools",
      "**1. Cause-and-Effect Diagram (Ishikawa / Fishbone).** Untuk root cause analysis. Categories umum: 6M — Manpower, Method, Machine, Material, Measurement, Mother Nature. Bercabang seperti tulang ikan dari 'effect' (problem) ke sebelah kanan.",
      "**2. Flowchart (Process Map).** Memvisualisasikan langkah-langkah proses untuk menemukan inefisiensi, redundansi, atau decision points.",
      "**3. Checksheet (Tally Sheet).** Mengumpulkan data sederhana — mencatat berapa kali defect tertentu muncul.",
      "**4. Pareto Chart.** Bar chart yang diurutkan dari terbesar ke terkecil. Menerapkan prinsip 80/20 — 80% masalah biasanya berasal dari 20% causes. Fokuskan effort pada kelompok kiri.",
      "**5. Histogram.** Distribusi frekuensi data — menunjukkan pola distribusi (normal, skewed, bimodal).",
      "**6. Control Chart.** Tracking proses dari waktu ke waktu dengan Upper Control Limit (UCL) dan Lower Control Limit (LCL). **Rule of Seven**: 7 titik berturut-turut di satu sisi mean = proses out of control bahkan kalau masih dalam control limits.",
      "**7. Scatter Diagram.** Hubungan antara dua variable — apakah korelasi positif, negatif, atau tidak ada.",
      "## Memilih Alat untuk Situasi",
      "| Situasi | Tool |",
      "|---|---|",
      "| Recurring defect, cari penyebab | Fishbone diagram |",
      "| Banyak issue, harus prioritas | Pareto chart |",
      "| Proses stabil atau tidak | Control chart |",
      "| Pola distribusi data | Histogram |",
      "| Hubungan dua variable | Scatter diagram |",
      "| Tracking jumlah defect tipe X | Checksheet |",
      "| Menemukan langkah yang lambat / redundant | Flowchart |",
      "## Konsep Lain Yang Sering Muncul",
      "**Plan-Do-Check-Act (PDCA / Deming Cycle)** — iterasi continuous improvement.",
      "**Kaizen** — perbaikan kecil yang terus-menerus.",
      "**Six Sigma** — pendekatan statistik untuk mengurangi defect ke 3.4 per juta (DPMO).",
      "**Total Quality Management (TQM)** — quality adalah tanggung jawab semua orang, bukan hanya QA team.",
      "**Just-in-Time (JIT)** — Lean concept, mengurangi inventory dan waste.",
      "## Andromeda's Takeaway",
      "Quality bukan 'tester di akhir'. Quality dimulai dari planning, dijaga dengan process (QA), dan diverifikasi dengan inspection (QC). Soal yang menyebut **recurring defect** hampir selalu menunjuk ke **root cause analysis (fishbone)** — bukan quick fix. Soal yang menyebut **banyak jenis issue** menunjuk ke **Pareto** — fokus 20% yang paling mengganggu.",
    ].join("\n\n"),
    keyTakeaways: [
      "Quality vs Grade: quality non-negotiable; grade boleh low.",
      "Prevention > Inspection. COQ = Conformance + Non-Conformance.",
      "Fishbone = root cause. Pareto = prioritization. Control chart = process stability.",
      "Rule of Seven: 7 consecutive points one side of mean = out of control.",
    ],
    studyTip:
      "Latih 'choose-the-tool' quiz: 7 scenario, 7 tools. Kalau bingung antara fishbone vs Pareto: fishbone cari PENYEBAB satu masalah, Pareto cari masalah MANA yang paling penting.",
    relatedTerms: ["Pareto", "Fishbone", "Control Chart", "Cost of Quality", "PDCA"],
  },

  // -------------------------------------------------------------------------
  // EVM
  // -------------------------------------------------------------------------
  {
    slug: "earned-value-management",
    title: "Earned Value Management — CV, SV, CPI, SPI, EAC, ETC, VAC",
    category: "Cost",
    domain: "Process",
    approach: "predictive",
    examVersion: "both",
    summary:
      "Math wajib PMP. Semua rumus dengan contoh, plus cara interpret hasilnya untuk decision making.",
    content: [
      "## Tiga Angka Dasar",
      "**PV — Planned Value.** Berapa nilai pekerjaan yang SEHARUSNYA sudah selesai pada tanggal status. Dari schedule.",
      "**EV — Earned Value.** Berapa nilai pekerjaan yang SUDAH benar-benar selesai pada tanggal status.",
      "**AC — Actual Cost.** Berapa biaya AKTUAL yang sudah dihabiskan untuk pekerjaan yang selesai.",
      "## Variance",
      "**CV — Cost Variance** = `EV − AC`. Positif = under budget. Negatif = over budget.",
      "**SV — Schedule Variance** = `EV − PV`. Positif = ahead of schedule. Negatif = behind schedule.",
      "## Performance Indexes",
      "**CPI — Cost Performance Index** = `EV / AC`. > 1.0 = better than planned (cost efficient). < 1.0 = over budget.",
      "**SPI — Schedule Performance Index** = `EV / PV`. > 1.0 = ahead of schedule. < 1.0 = behind.",
      "## Forecasting",
      "**BAC — Budget at Completion**: total budget yang direncanakan untuk seluruh project.",
      "**EAC — Estimate at Completion**: prediksi total cost project saat selesai. Empat rumus tergantung asumsi:",
      "- `EAC = BAC / CPI` — asumsi variance akan berlanjut dengan CPI yang sama (paling sering muncul di soal).",
      "- `EAC = AC + (BAC − EV)` — asumsi sisa pekerjaan akan dikerjakan SESUAI rencana (variance hanya kebetulan).",
      "- `EAC = AC + ((BAC − EV) / (CPI × SPI))` — asumsi cost DAN schedule keduanya berpengaruh.",
      "- `EAC = AC + Bottom-Up ETC` — re-estimate sisa pekerjaan dari nol.",
      "**ETC — Estimate to Complete** = `EAC − AC`. Berapa lagi yang akan dihabiskan dari sekarang.",
      "**VAC — Variance at Completion** = `BAC − EAC`. Positif = project akan selesai under budget. Negatif = over.",
      "**TCPI — To-Complete Performance Index** = efisiensi yang DIBUTUHKAN dari sisa pekerjaan untuk mencapai target. `TCPI = (BAC − EV) / (BAC − AC)` (kalau target = BAC) atau `(BAC − EV) / (EAC − AC)` (kalau target = EAC).",
      "## Contoh Lengkap",
      "Project: install 100 km fiber optik. BAC = $1,000,000. Status 6 bulan:",
      "- PV (rencana 60 km selesai) = $600,000",
      "- EV (aktual 50 km selesai) = $500,000",
      "- AC (uang yang sudah dihabiskan) = $550,000",
      "",
      "Hitungan:",
      "- CV = 500,000 − 550,000 = **−$50,000** (over budget)",
      "- SV = 500,000 − 600,000 = **−$100,000** (behind schedule)",
      "- CPI = 500,000 / 550,000 = **0.91** (cost efficient hanya 91%)",
      "- SPI = 500,000 / 600,000 = **0.83** (schedule running di 83%)",
      "- EAC (CPI continues) = 1,000,000 / 0.91 ≈ **$1,098,901**",
      "- ETC = 1,098,901 − 550,000 = **$548,901**",
      "- VAC = 1,000,000 − 1,098,901 = **−$98,901** (akan over budget)",
      "## Interpretasi",
      "Jangan baca angka tanpa menafsir. CPI < 1 dan SPI < 1 → project butuh corrective action: review estimating assumption, identifikasi root cause variance, evaluasi crashing vs descoping, dan komunikasikan ke stakeholder. Jangan langsung crashing — cek dulu apakah variance dari root cause yang bisa diperbaiki.",
      "## Andromeda's Takeaway",
      "EVM math hampir selalu muncul di exam, biasanya 5–8 soal. Strategi: hafal rumus, latih dengan angka, dan ingat bahwa **soal sering minta interpretasi, bukan cuma angka**. Kalau soal tanya 'apa yang harus PM lakukan dengan SPI 0.83?', jawabannya BUKAN 'crashing immediately' tapi 'analyze the cause, then consult stakeholders'.",
    ].join("\n\n"),
    keyTakeaways: [
      "CV = EV − AC. SV = EV − PV. CPI = EV/AC. SPI = EV/PV.",
      "EAC = BAC / CPI (most-used formula).",
      "ETC = EAC − AC. VAC = BAC − EAC.",
      "Index > 1 = good. Variance positive = good.",
      "Always analyze cause before crashing or descoping.",
    ],
    studyTip:
      "Buat tabel: PV, EV, AC, BAC. Hitung semua 7 indikator. Ulangi 5×. Setelah itu math di exam jadi reflex.",
    relatedTerms: ["EVM", "CV", "SV", "CPI", "SPI", "EAC", "ETC", "VAC"],
  },

  // -------------------------------------------------------------------------
  // SCHEDULE
  // -------------------------------------------------------------------------
  {
    slug: "critical-path-and-compression",
    title: "Critical Path, Float, dan Schedule Compression",
    category: "Schedule",
    domain: "Process",
    approach: "predictive",
    examVersion: "both",
    summary:
      "Cara hitung critical path dan float, dan cara memilih antara fast-tracking dan crashing kalau jadwal terancam.",
    content: [
      "## Network Diagram",
      "Project digambarkan sebagai sequence aktivitas yang saling terhubung. Setiap activity punya 4 angka penting: Early Start (ES), Early Finish (EF), Late Start (LS), Late Finish (LF).",
      "**Forward Pass** (kiri ke kanan): hitung ES dan EF untuk setiap activity. `EF = ES + Duration`. Untuk activity dengan multiple predecessor, ES = MAX(EF dari semua predecessor).",
      "**Backward Pass** (kanan ke kiri): hitung LF dan LS. `LS = LF − Duration`. Untuk activity dengan multiple successor, LF = MIN(LS dari semua successor).",
      "## Float (Slack)",
      "**Total Float** = `LS − ES` atau `LF − EF`. Berapa lama activity bisa terlambat tanpa menggeser project completion date.",
      "**Free Float** = `ES (successor) − EF (this) − 1`. Berapa lama activity bisa terlambat tanpa menggeser successor.",
      "**Critical Path** = path dengan TOTAL FLOAT = 0. Activity di critical path harus selesai tepat waktu atau seluruh project tertunda.",
      "## Schedule Compression",
      "**Fast Tracking** — kerjakan activity yang awalnya sequential SECARA PARALEL. Tidak menambah biaya, tapi MENAMBAH RISIKO (rework, integrasi, koordinasi).",
      "**Crashing** — tambah resource ke activity di critical path untuk mempercepat. MENAMBAH BIAYA, tapi tidak menambah risiko teknis. Caveat: tidak semua activity bisa di-crash (mis. coding tidak bisa di-crash 2× dengan menambah 2× developer karena ada Brooks' Law — adding manpower to a late software project makes it later).",
      "## Memilih Antara Fast Tracking vs Crashing",
      "| Kriteria | Fast Tracking | Crashing |",
      "|---|---|---|",
      "| Cost impact | Tidak naik | Naik |",
      "| Risk impact | Naik | Tidak (biasanya) |",
      "| Kapan dipakai | Budget ketat, risiko bisa ditolerir | Budget ada, risiko harus minimal |",
      "## Leads dan Lags",
      "**Lead** — successor bisa MULAI sebelum predecessor selesai. Mis. 'Painting can start 2 days BEFORE drywall finishes' = lead 2 hari.",
      "**Lag** — successor harus MENUNGGU setelah predecessor. Mis. 'Concrete must cure 7 days before painting' = lag 7 hari.",
      "## Andromeda's Takeaway",
      "Critical path adalah JADWAL TERPANJANG yang menentukan project completion. Kalau schedule terancam, JANGAN langsung crashing. Diagnose dulu: apakah masalahnya estimating (re-estimate), risk yang materialize (response plan), atau scope creep (change control). Crashing dan fast-tracking adalah opsi TERAKHIR setelah penyebab dipahami.",
    ].join("\n\n"),
    keyTakeaways: [
      "Critical path = path dengan total float 0.",
      "Forward pass: ES, EF. Backward pass: LS, LF. Float = LS − ES.",
      "Fast tracking: tidak cost, tapi tambah risk. Crashing: tambah cost, tidak tambah risk teknis.",
      "Diagnose root cause sebelum memilih schedule compression.",
    ],
    studyTip:
      "Latihan: buat network diagram 6-activity, hitung CP dan float secara manual. Lakukan 3× dengan diagram berbeda.",
    relatedTerms: ["Critical Path", "Float", "Fast Tracking", "Crashing", "Network Diagram"],
  },

  // -------------------------------------------------------------------------
  // PEOPLE / MOTIVATION / CONFLICT
  // -------------------------------------------------------------------------
  {
    slug: "motivation-theories",
    title: "Motivation Theories — Maslow, Herzberg, McGregor, McClelland",
    category: "Leadership",
    domain: "People",
    approach: "general",
    examVersion: "both",
    summary:
      "Empat teori motivasi klasik yang sering muncul di soal People domain. Apa intinya, dan bagaimana memilih jawaban berdasarkan teori yang tepat.",
    content: [
      "## Maslow's Hierarchy of Needs",
      "Piramida 5 lapis dari paling dasar ke paling tinggi:",
      "1. **Physiological** — makan, tidur, gaji minimum.",
      "2. **Safety** — keamanan kerja, kontrak, lingkungan aman.",
      "3. **Social / Belonging** — diterima dalam tim, hubungan baik.",
      "4. **Esteem** — pengakuan, status, prestasi.",
      "5. **Self-Actualization** — pertumbuhan, makna, mencapai potensi penuh.",
      "Maslow berargumen kebutuhan bawah harus dipenuhi dulu sebelum kebutuhan atas relevan. Dalam project: kalau tim khawatir layoff (safety), berbicara tentang 'self-actualization opportunity' percuma.",
      "## Herzberg's Two-Factor Theory",
      "Membagi faktor kerja jadi dua kategori berbeda:",
      "**Hygiene Factors** — kalau buruk, menyebabkan dissatisfaction. Tapi kalau bagus, TIDAK menciptakan motivasi — hanya menghilangkan ketidakpuasan. Contoh: gaji, kebijakan perusahaan, kondisi kerja, supervisi, hubungan interpersonal, status.",
      "**Motivators** — kalau ada, menciptakan kepuasan dan motivasi. Contoh: pencapaian, pengakuan, pekerjaan itu sendiri, tanggung jawab, advancement, growth.",
      "Implikasi: menaikkan gaji menghilangkan complaint, tapi tidak membuat orang LEBIH termotivasi. Untuk motivasi sebenarnya: beri ownership, tantangan, dan recognition.",
      "## McGregor's Theory X and Theory Y",
      "Dua mental model tentang pekerja:",
      "**Theory X** — manajer mengasumsikan pekerja malas, harus dipaksa, dikontrol, dihukum. Style: command-and-control.",
      "**Theory Y** — manajer mengasumsikan pekerja punya intrinsic motivation, ingin berkembang, dan bisa bertanggung jawab. Style: empowerment, servant leadership.",
      "PMI mindset jelas Theory Y. Soal yang menampilkan 'PM marah dan memerintah' biasanya mengarah ke jawaban Theory Y (coaching, facilitation).",
      "**Theory Z** (Ouchi) — extension dari Y: long-term employment, collective decision making, slow promotion, holistic concern (sering disebut Japanese management style).",
      "## McClelland's Acquired Needs Theory (Three Needs)",
      "Setiap orang punya kombinasi 3 motivator dominan:",
      "- **Need for Achievement (nAch)** — ingin mencapai, suka challenge yang moderate (tidak terlalu mudah, tidak terlalu sulit). Cocok untuk task-oriented assignment.",
      "- **Need for Affiliation (nAff)** — ingin hubungan baik dan diterima. Cocok untuk customer-facing atau team-cohesion roles.",
      "- **Need for Power (nPow)** — ingin pengaruh dan kontrol. Dua sub-tipe: personal power (egois) atau institutional power (untuk kebaikan organisasi). Yang kedua cocok untuk manager role.",
      "Implikasi: assign pekerjaan berdasarkan motivator dominan tim.",
      "## Tabel Pembanding",
      "| Teori | Idea Inti | Cara Pakai |",
      "|---|---|---|",
      "| Maslow | Hierarki kebutuhan, dari fisiologis ke aktualisasi | Pastikan kebutuhan bawah terpenuhi dulu |",
      "| Herzberg | Hygiene ≠ Motivator | Untuk motivasi, fokus motivators, bukan hygiene |",
      "| McGregor | X (negative) vs Y (positive) | Pilih Y untuk PMI mindset |",
      "| McClelland | Achievement, Affiliation, Power | Assign work sesuai dominant need |",
      "## Andromeda's Takeaway",
      "Kalau soal menyebut 'salary increase tapi team masih tidak engaged' → Herzberg (hygiene fixed but motivators missing). Kalau soal menyebut 'team baru, takut layoff' → Maslow (safety dulu). Kalau soal menyebut 'manager marah dan memberi perintah' → biasanya jawaban benar adalah Theory Y. Kalau soal menyebut 'assign challenging individual task' → McClelland nAch.",
    ].join("\n\n"),
    keyTakeaways: [
      "Maslow: 5 lapis, bawah dulu.",
      "Herzberg: hygiene cegah dissatisfaction; motivators ciptakan satisfaction.",
      "McGregor: PMI = Theory Y.",
      "McClelland: nAch (challenge), nAff (relationship), nPow (influence).",
    ],
    studyTip:
      "Buat satu skenario untuk masing-masing teori, sehingga lo bisa quick-match pertanyaan ke teori.",
    relatedTerms: ["Maslow", "Herzberg", "McGregor", "McClelland", "Servant Leadership"],
  },
  {
    slug: "conflict-resolution-thomas-kilmann",
    title: "Conflict Resolution — Thomas-Kilmann dan Tuckman",
    category: "Leadership",
    domain: "People",
    approach: "general",
    examVersion: "both",
    summary:
      "5 mode konflik Thomas-Kilmann (Collaborate, Compromise, Accommodate, Avoid, Force) dan 5 stage Tuckman (Forming, Storming, Norming, Performing, Adjourning).",
    content: [
      "## Thomas-Kilmann Conflict Modes",
      "Dua sumbu: **Cooperativeness** (concern for OTHERS) vs **Assertiveness** (concern for SELF).",
      "**1. Collaborate / Problem-Solve.** Tinggi di KEDUA sumbu. Cari solusi WIN-WIN dengan menggabungkan ide kedua pihak. Membutuhkan waktu dan trust. **DEFAULT PMI** — jawaban paling sering benar di exam.",
      "**2. Compromise.** Sedang di kedua sumbu. Setiap pihak menyerah sebagian — lose-lose-ish atau win-some-lose-some. Cocok ketika waktu terbatas dan stake seimbang.",
      "**3. Accommodate / Smooth.** Cooperative tinggi, assertive rendah. Mengalah untuk menjaga relationship — emphasizing common ground, downplaying differences. Cocok kalau issue tidak penting bagi diri sendiri tapi penting bagi pihak lain, atau untuk preserve harmony.",
      "**4. Avoid / Withdraw.** Rendah di kedua sumbu. Tidak engage, postpone, withdraw. Cocok hanya kalau issue trivial, atau perlu waktu untuk cool down. JARANG menjadi jawaban PMP — biasanya distractor.",
      "**5. Force / Compete / Direct.** Assertive tinggi, cooperative rendah. Memaksakan posisi diri. Win-lose. Cocok hanya untuk emergency, decisions tidak populer tapi perlu, atau life-safety. JARANG menjadi jawaban PMP yang benar.",
      "## Memilih Mode di Exam",
      "| Konteks | Pilih |",
      "|---|---|",
      "| Ada waktu, kedua sisi punya value | Collaborate |",
      "| Waktu sempit, stake seimbang | Compromise |",
      "| Issue tidak crucial bagi diri sendiri | Accommodate |",
      "| Issue trivial atau perlu cooling | Avoid |",
      "| Emergency / safety / unpopular but necessary | Force |",
      "**Default PMI:** Collaborate. Kalau pilihan jawaban menampilkan 'meet with both parties to understand and find a mutually acceptable solution', itu hampir selalu benar.",
      "## Tuckman's Stages of Team Development",
      "**Forming.** Tim baru, polite, hati-hati, belum saling kenal. Role PM: provide direction, structure.",
      "**Storming.** Konflik muncul saat orang menunjukkan kepribadian dan opini. Paling tense. Role PM: facilitate, mediate, normalize bahwa konflik adalah bagian dari pertumbuhan tim.",
      "**Norming.** Tim menemukan ritme, working agreements, dan trust. Role PM: support, coach.",
      "**Performing.** Tim berfungsi optimal, mandiri, high output. Role PM: enable, delegate, remove obstacles.",
      "**Adjourning.** Tim selesai project — celebrate, lessons learned, transition.",
      "## Tuckman + Conflict Mode",
      "Stage Tuckman menentukan mode konflik mana yang paling sering relevan: Forming/Storming biasanya butuh Collaborate (membangun fondasi); Performing membutuhkan Avoidance lebih sedikit dan Confront lebih banyak.",
      "## Andromeda's Takeaway",
      "Pada People domain, 80% jawaban benar berkisar pada: **listen, diagnose, collaborate, coach, facilitate**. Jangan pilih 'replace team member' atau 'escalate to sponsor' kecuali scenario eksplisit menunjukkan semua step lain sudah dilakukan.",
    ].join("\n\n"),
    keyTakeaways: [
      "5 Thomas-Kilmann modes: Collaborate (PMI default), Compromise, Accommodate, Avoid, Force.",
      "Tuckman: Forming → Storming → Norming → Performing → Adjourning.",
      "Storming requires facilitation, not avoidance.",
      "Default jawaban PMP People domain: collaborate + coach.",
    ],
    studyTip:
      "Untuk setiap dari 5 mode konflik, tulis satu skenario kerja nyata. Akan jadi 5 anchor mental yang kuat.",
    relatedTerms: ["Thomas-Kilmann", "Tuckman", "Servant Leadership", "Conflict Management"],
  },

  // -------------------------------------------------------------------------
  // INTEGRATION / CHANGE
  // -------------------------------------------------------------------------
  {
    slug: "integrated-change-control",
    title: "Integrated Change Control — How Changes Get Approved",
    category: "Integration",
    domain: "Process",
    approach: "predictive",
    examVersion: "both",
    summary:
      "Proses formal untuk mengelola perubahan: dari change request, impact analysis, CCB decision, sampai update baseline.",
    content: [
      "## Apa Itu Integrated Change Control",
      "Setiap perubahan pada baseline (scope, schedule, cost, quality, atau aspek baseline-able lainnya) harus melewati proses formal — ICC. Tujuannya: memastikan setiap perubahan dievaluasi DAMPAKnya secara terintegrasi sebelum diterima atau ditolak.",
      "## Flow Langkah",
      "1. **Change Request** — siapa pun bisa mengajukan (stakeholder, sponsor, tim, customer).",
      "2. **Document** — di Change Log.",
      "3. **Impact Analysis** — analisis dampak pada scope, schedule, cost, quality, risk, resources, communications, procurement. Ini adalah jantung ICC.",
      "4. **CCB Review** — Change Control Board mengevaluasi. Bisa berisi sponsor, PM, key stakeholders, SME.",
      "5. **Decision** — Approve / Reject / Defer.",
      "6. **Implement** — kalau approved, update baseline, kirim Approved Change Request ke pelaksana.",
      "7. **Update Documentation** — project management plan, baseline, register, log.",
      "8. **Communicate** — kepada semua stakeholder relevan.",
      "## Change Types",
      "**Corrective Action** — bring future performance back in line dengan plan.",
      "**Preventive Action** — proactive action untuk mencegah deviasi.",
      "**Defect Repair** — perbaiki cacat produk.",
      "**Updates** — perubahan minor pada dokumen.",
      "## Common Trap",
      "Soal sering menampilkan PM yang langsung approve atau langsung reject. Jawaban hampir selalu: **analyze impact first, then follow change control process**. Hindari opsi yang lompat ke implementasi atau eskalasi tanpa impact analysis.",
      "## Andromeda's Takeaway",
      "Perubahan adalah BIASA. Yang tidak boleh adalah perubahan informal (under-the-table, verbal-only, tidak terdokumentasi). Setiap kali soal menyebut 'client requests a new feature' atau 'team wants to swap technology' — jawaban PMP adalah: dokumentasikan, analisis dampak, lewatkan change control, lalu eksekusi.",
    ].join("\n\n"),
    keyTakeaways: [
      "Setiap perubahan baseline lewat ICC.",
      "Heart of ICC: impact analysis ACROSS scope, schedule, cost, quality, risk.",
      "CCB membuat keputusan: approve / reject / defer.",
      "Update baseline + komunikasikan setelah approved.",
    ],
    studyTip:
      "Hafal urutan: Request → Document → Impact → CCB → Decision → Implement → Update → Communicate.",
    relatedTerms: ["Change Request", "CCB", "Change Log", "Baseline", "Configuration Management"],
  },

  // -------------------------------------------------------------------------
  // AGILE & HYBRID
  // -------------------------------------------------------------------------
  {
    slug: "agile-foundations",
    title: "Agile Foundations — Manifesto, Scrum, Kanban, XP",
    category: "Agile",
    domain: "Process",
    approach: "agile",
    examVersion: "both",
    summary:
      "Foundation agile yang harus dimengerti: Manifesto, Scrum roles & events, Kanban principles, XP practices, dan saat memilih framework.",
    content: [
      "## Agile Manifesto — 4 Values",
      "1. **Individuals and interactions** over processes and tools.",
      "2. **Working software** over comprehensive documentation.",
      "3. **Customer collaboration** over contract negotiation.",
      "4. **Responding to change** over following a plan.",
      "Note: \"over\" bukan \"instead of\". Yang kanan tetap punya value, tapi yang kiri diprioritaskan.",
      "## 12 Principles (Highlights)",
      "Continuous delivery, welcome changing requirements, frequent delivery, business + dev daily, motivated individuals, face-to-face conversation, working software = primary measure, sustainable pace, technical excellence, simplicity, self-organizing teams, regular reflection.",
      "## Scrum — Roles, Events, Artifacts",
      "**Roles:** Product Owner (vision + backlog priority), Scrum Master (servant leader, removes impediments), Developers (the team building it).",
      "**Events:** Sprint (time-boxed iteration, biasanya 1–4 minggu), Sprint Planning, Daily Scrum (15 min), Sprint Review (demo + feedback), Sprint Retrospective (continuous improvement). Plus Backlog Refinement (ongoing).",
      "**Artifacts:** Product Backlog (PO owns), Sprint Backlog (Devs own), Increment (working product).",
      "**Definition of Done (DoD)** — kriteria untuk increment dianggap selesai. **Definition of Ready (DoR)** — kriteria untuk backlog item siap di-sprint.",
      "## Kanban — 6 Practices",
      "1. **Visualize work** — board kolom (To Do, Doing, Done; bisa lebih granular).",
      "2. **Limit WIP** (Work in Progress) — fokus, kurangi context switching.",
      "3. **Manage flow** — optimize cycle time dan throughput.",
      "4. **Make policies explicit** — entry/exit criteria per kolom.",
      "5. **Feedback loops** — daily standup, replenishment meeting, delivery review.",
      "6. **Improve collaboratively** — evolve experimentally.",
      "**Metrik Kanban:** Cycle Time, Lead Time, Throughput, Cumulative Flow Diagram.",
      "## XP — Extreme Programming",
      "Practices teknis: Pair Programming, TDD (Test-Driven Development), Continuous Integration, Refactoring, Simple Design, Collective Code Ownership, Sustainable Pace, Whole Team. XP fokus engineering excellence.",
      "## Memilih Framework",
      "| Konteks | Pilih |",
      "|---|---|",
      "| Iteration-based, role jelas | Scrum |",
      "| Flow-based, ongoing work | Kanban |",
      "| Engineering excellence | XP |",
      "| Scaling banyak tim | SAFe / LeSS / Nexus / Scrum@Scale |",
      "| Predictable compliance + discovery | Hybrid |",
      "## Andromeda's Takeaway",
      "Agile bukan 'tidak ada plan'. Agile adalah 'plan iteratif dengan feedback loop cepat'. Soal People domain agile sering menguji: protect transparency, jangan command-and-control, biarkan tim self-organize, hormati role boundaries (PO owns priority, Devs own how).",
    ].join("\n\n"),
    keyTakeaways: [
      "Manifesto: 4 values, 12 principles.",
      "Scrum roles: PO, SM, Developers. 5 events. 3 artifacts.",
      "Kanban: visualize, limit WIP, manage flow, explicit policies, feedback, improve.",
      "XP: engineering practices (TDD, pair programming, CI).",
    ],
    studyTip:
      "Hafal 5 Scrum events + 3 Kanban metrics. Soal sering menampilkan anti-pattern: spotting violations adalah skill yang teruji.",
    relatedTerms: ["Scrum", "Kanban", "XP", "Sprint", "Product Owner", "Scrum Master"],
  },
  {
    slug: "hybrid-delivery",
    title: "Hybrid Delivery — Mixing Predictive and Adaptive",
    category: "Hybrid Delivery",
    domain: "Process",
    approach: "hybrid",
    examVersion: "both",
    summary:
      "Kapan dan bagaimana mencampur agile dan predictive. Pola umum, decision criteria, dan governance hybrid.",
    content: [
      "## Apa Itu Hybrid",
      "Hybrid = menggabungkan elemen predictive (waterfall) dan adaptive (agile) dalam satu project. BUKAN \"sebagian setengah agile setengah waterfall\" tapi pilihan SADAR mana bagian yang lebih cocok mana style.",
      "## Pola Umum Hybrid",
      "**Pattern 1: Predictive Phase + Agile Phase.** Discovery / requirements + procurement dijalankan predictive. Build + integration dijalankan agile. Cocok untuk project dengan regulasi awal yang ketat.",
      "**Pattern 2: Agile Build + Predictive Release.** Build iteratively, tapi release dijadwalkan formal dengan compliance gate.",
      "**Pattern 3: Parallel.** Beberapa workstream agile, beberapa predictive. Cocok untuk program dengan komponen riset DAN compliance.",
      "**Pattern 4: Selective Practices.** Predictive overall, tapi adopsi practices agile (daily standup, retrospectives, demos) untuk komunikasi dan continuous improvement.",
      "## Decision Criteria",
      "Pilih agile untuk pekerjaan yang:",
      "- Scope kabur, banyak discovery.",
      "- Customer feedback cepat punya value.",
      "- Tim self-organizing dan colocated/well-connected.",
      "- Tolerance untuk experiment.",
      "Pilih predictive untuk pekerjaan yang:",
      "- Scope jelas, regulasi ketat.",
      "- Cost of change tinggi (mis. konstruksi).",
      "- Compliance audit-able.",
      "- Vendor dengan FFP contract.",
      "## Governance Hybrid",
      "Hybrid butuh governance yang menjembatani dua dunia. PM jadi translator: agile metrics (velocity, burndown) ke predictive language (EVM, milestone), dan sebaliknya. Stakeholder dari predictive side perlu visibility tanpa mendisrupt flow agile team.",
      "## Common Trap",
      "Salah satu bagian sering mendominasi yang lain. Mis. governance predictive yang berlebihan membunuh kecepatan agile team; atau agile chaos yang merusak compliance gate. Solusi: clear interface antara dua mode — agreed handoff points, escalation paths, dan reporting cadence.",
      "## Andromeda's Takeaway",
      "Hybrid bukan kompromi malas. Hybrid adalah pilihan dewasa kalau project punya bagian dengan certainty berbeda. Soal hybrid sering menguji: apakah lo memilih style YANG TEPAT untuk bagian YANG TEPAT, bukan memaksakan satu style untuk semuanya.",
    ].join("\n\n"),
    keyTakeaways: [
      "Hybrid = pilihan sadar antara agile dan predictive untuk bagian-bagian project.",
      "4 pola umum: Predictive→Agile, Agile→Predictive Release, Parallel, Selective Practices.",
      "Governance hybrid: translator antara metrik agile dan predictive.",
      "Jangan paksakan satu style untuk seluruh project.",
    ],
    studyTip:
      "Hafal 4 pola hybrid dan satu contoh industri untuk masing-masing.",
    relatedTerms: ["Hybrid", "Agile", "Predictive", "Governance"],
  },

  // -------------------------------------------------------------------------
  // BUSINESS ENVIRONMENT
  // -------------------------------------------------------------------------
  {
    slug: "benefits-realization-and-ocm",
    title: "Benefits Realization, OCM, dan Governance",
    category: "Business Environment",
    domain: "Business Environment",
    approach: "general",
    examVersion: "both",
    summary:
      "Bagaimana project menghasilkan value yang nyata: dari output ke outcome ke benefit, dengan OCM (ADKAR) dan governance yang menjaga akuntabilitas.",
    content: [
      "## Output → Outcome → Benefit → Value",
      "**Output** — deliverable yang dihasilkan project (mis. aplikasi mobile baru).",
      "**Outcome** — perubahan yang terjadi karena output (mis. customer sekarang bisa booking dalam 30 detik).",
      "**Benefit** — nilai yang diukur (mis. booking conversion naik 15%).",
      "**Value** — kontribusi strategis ke bisnis (mis. revenue tumbuh, brand naik, kompetitor tertinggal).",
      "Kebanyakan project gagal di tengah jalan: produce output tapi tidak menghasilkan outcome karena adoption rendah. Karena itu OCM penting.",
      "## Benefits Management Plan",
      "Dokumen yang menjawab:",
      "- Apa benefit yang diharapkan? (specific, measurable)",
      "- Siapa OWNER benefit setelah project selesai? (operations, business unit head)",
      "- Kapan benefit diharapkan muncul? (timeline)",
      "- Bagaimana diukur? (metrik, baseline, target)",
      "- Apa risiko terhadap benefit?",
      "Benefits Management Plan sering bersifat LIVE — terus diupdate sampai benefit terwujud, biasanya BERLANGSUNG SETELAH project closure.",
      "## Organizational Change Management (OCM)",
      "Project mengubah cara organisasi bekerja, dan resistensi alami muncul. OCM adalah disiplin untuk membuat perubahan stick.",
      "**ADKAR Model (Prosci):**",
      "- **Awareness** — sadar perlunya perubahan.",
      "- **Desire** — keinginan untuk berubah.",
      "- **Knowledge** — tahu bagaimana berubah.",
      "- **Ability** — kemampuan untuk berubah.",
      "- **Reinforcement** — supporting perubahan agar tidak mundur.",
      "**Kotter's 8 Steps:** establish urgency → form coalition → vision → communicate → empower → quick wins → build on change → anchor in culture.",
      "## Governance",
      "Struktur tanggung jawab dan decision-making. Komponennya:",
      "- **Sponsor** — accountable for benefit realization, owns business case.",
      "- **Steering Committee** — strategic decisions, escalation point.",
      "- **PMO** — methodology, standards, resource pool, portfolio view.",
      "- **CCB** — change control authority.",
      "## Andromeda's Takeaway",
      "Project selesai BUKAN saat deliverable diterima. Project SUKSES saat benefit terealisasi. Karena itu PM exam-safe selalu memikirkan adoption, ownership benefit, dan reinforcement — bukan cuma 'on time / on budget / on scope'.",
    ].join("\n\n"),
    keyTakeaways: [
      "Output → Outcome → Benefit → Value chain.",
      "Benefits Management Plan: owner, timeline, metric, risk.",
      "ADKAR + Kotter sebagai OCM framework.",
      "Governance: sponsor, steering, PMO, CCB.",
    ],
    studyTip:
      "Saat baca soal, tanyakan: 'apakah benefit-nya punya owner dan adoption plan?' — kalau jawaban yang membahasnya ada di pilihan, itu biasanya benar.",
    relatedTerms: ["Benefits Realization", "OCM", "ADKAR", "Kotter", "Governance"],
  },
  {
    slug: "ai-and-sustainability-in-pm",
    title: "AI in Project Management dan Sustainability — 2026 Readiness",
    category: "AI and Sustainability for 2026 readiness",
    domain: "Business Environment",
    approach: "general",
    examVersion: "2026",
    summary:
      "Bagaimana AI dan sustainability diintegrasikan ke dalam praktik PM 2026 — sebagai stakeholder, risk, dan opportunity, dengan governance yang tepat.",
    content: [
      "## AI sebagai Stakeholder + Tool + Risk",
      "AI dalam project management bukan sekadar fitur — dia berfungsi sebagai THREE THINGS sekaligus:",
      "**1. Tool** — forecasting (project completion, cost), risk identification dari historical data, status reporting automation, decision support, intelligent search di knowledge base.",
      "**2. Stakeholder** — keputusan AI mempengaruhi stakeholder lain (mis. AI recommendation menentukan resource allocation). Karenanya AI perlu di-govern seperti stakeholder.",
      "**3. Risk** — bias, hallucination, data privacy, model drift, accountability gap.",
      "## AI Governance untuk PM",
      "- **Human-in-the-loop** untuk keputusan high-stakes.",
      "- **Explainability** — bisa dijelaskan mengapa AI merekomendasikan X.",
      "- **Bias audit** — terutama untuk people decisions.",
      "- **Data privacy** — PII, confidential data, IP.",
      "- **Accountability** — AI tidak bertanggung jawab; manusia tetap accountable.",
      "## Common AI Use Cases di PM",
      "- Predictive completion estimates (Monte Carlo enhanced dengan ML).",
      "- Risk pattern detection dari historical projects.",
      "- Stakeholder sentiment analysis dari communication logs.",
      "- Document summarization dan question answering.",
      "- Auto-generation status report.",
      "- Coaching assistant (seperti Andromeda di Nexus Academy).",
      "## Sustainability — Triple Bottom Line",
      "Project tidak hanya dinilai dari profit. Sustainable project mempertimbangkan:",
      "**People** — dampak ke karyawan, komunitas, stakeholder.",
      "**Planet** — dampak lingkungan, carbon footprint, sumber daya.",
      "**Profit** — kelayakan finansial yang berkelanjutan.",
      "## ESG di Project Decisions",
      "**E (Environmental)** — carbon, energy, waste, water, biodiversity.",
      "**S (Social)** — labor, community, customer welfare, diversity, human rights.",
      "**G (Governance)** — ethics, transparency, board structure, anti-corruption.",
      "Project decisions yang mempertimbangkan ESG: vendor selection (vendor ESG score), procurement (sustainable materials), benefits (long-term outcomes, not just short-term ROI).",
      "## PMI Code of Ethics",
      "Empat values:",
      "1. **Responsibility** — own decisions and their consequences.",
      "2. **Respect** — treat others with respect; understand cultural differences.",
      "3. **Fairness** — make decisions impartially; no conflict of interest.",
      "4. **Honesty** — truthful in communications and conduct.",
      "Soal Ethics biasanya menampilkan dilemma — pilihan jawaban benar adalah yang paling sesuai dengan keempat nilai ini, bukan yang paling pragmatis.",
      "## Andromeda's Takeaway",
      "PMP 2026 bergeser: People-Process-Business Environment dengan distribusi yang menambah Business Environment ke 26%. Topik yang dulunya jarang muncul — AI ethics, ESG, sustainability — sekarang muncul dalam scenario. Andromeda saran: jangan perlakukan AI dan sustainability sebagai topik terpisah; integrasikan ke risk, stakeholder, dan benefits thinking.",
    ].join("\n\n"),
    keyTakeaways: [
      "AI adalah tool + stakeholder + risk sekaligus.",
      "Human-in-the-loop untuk decisions high-stakes.",
      "Triple bottom line: People, Planet, Profit.",
      "ESG faktorkan ke vendor selection, procurement, benefits.",
      "PMI Code of Ethics: Responsibility, Respect, Fairness, Honesty.",
    ],
    studyTip:
      "Latih scenario ethics dengan 4 nilai PMI. Hampir semua dilemma exam bisa diselesaikan dengan memilih opsi yang paling sesuai dengan keempat nilai.",
    relatedTerms: ["AI in PM", "ESG", "Sustainability", "PMI Code of Ethics", "Triple Bottom Line"],
  },

  // -------------------------------------------------------------------------
  // STAKEHOLDER & COMMS
  // -------------------------------------------------------------------------
  {
    slug: "stakeholder-engagement-deep",
    title: "Stakeholder Engagement — Analysis, Power/Interest, Salience, Engagement Matrix",
    category: "Stakeholder",
    domain: "People",
    approach: "general",
    examVersion: "both",
    summary:
      "Empat alat klasik untuk mengelola stakeholder + formula komunikasi yang sering muncul di soal.",
    content: [
      "## Identify Stakeholders",
      "Stakeholder = siapa saja yang bisa mempengaruhi atau dipengaruhi oleh project. Termasuk sponsor, customer, end user, regulator, supplier, tim internal, dan stakeholder pasif (komunitas).",
      "**Stakeholder Register** mencatat: nama, role, expectation, influence, interest, engagement strategy.",
      "## Classification Models",
      "**1. Power/Interest Grid (atau Power/Influence atau Influence/Impact).** 2x2 matrix:",
      "- High Power, High Interest → **Manage Closely** (sponsor, key client).",
      "- High Power, Low Interest → **Keep Satisfied** (executive di luar project, regulator).",
      "- Low Power, High Interest → **Keep Informed** (end user vocal, support team).",
      "- Low Power, Low Interest → **Monitor** (peripheral stakeholders).",
      "**2. Salience Model.** Tiga sumbu:",
      "- **Power** — kemampuan memaksakan keinginan.",
      "- **Legitimacy** — appropriateness dari klaim.",
      "- **Urgency** — time-sensitivity klaim.",
      "Kombinasi 3 sumbu menghasilkan 7 tipe stakeholder: dormant, discretionary, demanding, dominant, dangerous, dependent, definitive.",
      "**3. Direction of Influence.** Upward (executives), Downward (team), Outward (external), Sideward (peers).",
      "**4. Engagement Assessment Matrix.** Setiap stakeholder diberi label C (current) dan D (desired) pada 5 level:",
      "- **Unaware** — tidak tahu project.",
      "- **Resistant** — tahu, menolak.",
      "- **Neutral** — tahu, tidak preference.",
      "- **Supportive** — tahu, dukung tapi pasif.",
      "- **Leading** — dukung aktif dan promosikan.",
      "Gap antara C dan D = ruang yang perlu engagement strategy.",
      "## Communication Math",
      "**Channels formula:** `n(n−1)/2` di mana n = jumlah stakeholder.",
      "Contoh: 5 stakeholder → 10 channel. Tambah 1 stakeholder (jadi 6) → 15 channel — naik 50% hanya karena satu stakeholder tambahan.",
      "Implication: setiap penambahan stakeholder meningkatkan kompleksitas komunikasi secara eksponensial.",
      "## Communication Methods",
      "**Interactive** — multi-arah, real-time (meeting, call). Paling efektif untuk masalah kompleks.",
      "**Push** — informasi dikirim ke penerima (email, report). Tidak menjamin diterima atau dipahami.",
      "**Pull** — penerima mengambil sendiri (intranet, knowledge base). Cocok untuk audience besar yang ingin akses on-demand.",
      "## Andromeda's Takeaway",
      "Stakeholder gak dipuasin satu-satu kayak janji politisi. Lo PRIORITASKAN dengan power/interest, ENGAGE sesuai gap di engagement matrix, dan COMMUNICATE dengan method yang cocok dengan need-nya. Soal sering menjebak dengan opsi 'generic status report ke semua' — itu biasanya distractor.",
    ].join("\n\n"),
    keyTakeaways: [
      "Power/Interest Grid: 4 quadrants — Manage Closely di high/high.",
      "Salience: power × legitimacy × urgency.",
      "Engagement matrix: Current C vs Desired D, 5 level.",
      "Channels formula: n(n−1)/2.",
      "Communication methods: Interactive, Push, Pull.",
    ],
    studyTip:
      "Latih channels formula dengan 3 angka berbeda (5, 7, 10 stakeholder). Soal hitung channel sering muncul.",
    relatedTerms: ["Stakeholder Register", "Power Interest Grid", "Salience Model", "Engagement Matrix"],
  },

  // -------------------------------------------------------------------------
  // MINDSET
  // -------------------------------------------------------------------------
  {
    slug: "pmp-mindset-how-to-answer",
    title: "PMP Mindset — How to Answer Scenario Questions",
    category: "PMP Mindset",
    domain: "Process",
    approach: "general",
    examVersion: "both",
    summary:
      "Heuristic dan trap-spotting framework untuk memilih jawaban scenario yang khas PMP.",
    content: [
      "## Lima Atribut Mindset PMI",
      "PMP menguji JUDGMENT, bukan hafalan. Jawaban benar hampir selalu memenuhi setidaknya 3 dari 5 atribut:",
      "1. **Proactive** — mencegah lebih baik daripada bereaksi.",
      "2. **Collaborative** — engage orang yang tepat, bukan unilateral.",
      "3. **Ethical** — sesuai PMI Code of Ethics.",
      "4. **Value-driven** — fokus benefit dan outcome.",
      "5. **Adaptive** — sesuaikan dengan context (agile/hybrid/predictive).",
      "## FIRST / NEXT / PREVENT Pattern",
      "**FIRST** — pertanyaan menanyakan tindakan AWAL. Jawaban biasanya: pahami situasi, kumpulkan data, klarifikasi.",
      "**NEXT** — apa yang HARUS dilakukan SEKARANG. Jawaban biasanya: tindakan kecil yang responsible, melibatkan orang yang tepat.",
      "**PREVENT** — bagaimana mencegah situasi ini di masa depan. Jawaban biasanya menunjuk ke perencanaan (risk plan, communication plan, stakeholder plan).",
      "## Common Distractor Patterns",
      "**Escalation Trap.** Pilihan jawaban yang langsung naikkan ke sponsor — jarang benar kecuali authority benar-benar di luar PM.",
      "**Firefighter Trap.** Pilihan yang langsung melompat ke action tanpa analisis. PMP lebih suka diagnose dulu.",
      "**Command-and-Control Trap.** Pilihan di mana PM memerintah, terutama di context agile.",
      "**Scope-Rigidity Trap.** Pilihan yang menolak perubahan tanpa analisis dampak. Baseline harus dihormati TAPI bukan dengan menolak perubahan reflexively.",
      "**Generic Solution Trap.** Pilihan yang mengirim 'status report ke semua' atau 'tambah training' — terlalu umum, hampir selalu salah.",
      "## Read-the-Question Heuristic",
      "1. Identifikasi PROCESS GROUP (Initiating/Planning/Executing/M&C/Closing) dan KNOWLEDGE AREA.",
      "2. Identifikasi DOMAIN (People/Process/Business).",
      "3. Identifikasi APPROACH (Agile/Hybrid/Predictive).",
      "4. Identifikasi STAGE TUCKMAN kalau People domain.",
      "5. Eliminasi 2 distractor obvious (biasanya escalation atau force).",
      "6. Pilih opsi yang paling sesuai dengan 5 atribut mindset.",
      "## Andromeda's Takeaway",
      "PMP exam itu bukan ujian pengetahuan, ini ujian JUDGMENT yang terstruktur. 80% jawaban benar punya pola yang sama: **analyze → involve the right people → choose the smallest responsible action**. Sisa 20% adalah ITTO/calculation yang harus dihafal.",
    ].join("\n\n"),
    keyTakeaways: [
      "5 mindset attributes: Proactive, Collaborative, Ethical, Value-driven, Adaptive.",
      "FIRST = understand. NEXT = act small. PREVENT = look back to planning.",
      "Hindari: escalation, firefighter, command-and-control, scope-rigidity, generic.",
      "Heuristic: identifikasi PG/KA/domain/approach, eliminasi 2 distractor, pilih sesuai mindset.",
    ],
    studyTip:
      "Setiap kali wrong-answer di simulator, label dengan trap type. Pola lo akan kelihatan dalam 60 soal.",
    relatedTerms: ["PMP Mindset", "FIRST NEXT PREVENT", "Servant Leadership", "Value Delivery"],
  },
];

export type CuratedGlossaryTerm = {
  term: string;
  acronym?: string;
  category: string;
  approach: "general" | "agile" | "hybrid" | "predictive";
  examVersion: "current" | "2026" | "both";
  difficulty: "easy" | "medium" | "hard";
  simpleMeaning: string;
  definition: string;
  example: string;
  pmpMindset: string;
  relatedTerms: string[];
};

export const CURATED_GLOSSARY: CuratedGlossaryTerm[] = [
  {
    term: "Examination Content Outline",
    acronym: "ECO",
    category: "Exam Reference",
    approach: "general",
    examVersion: "both",
    difficulty: "easy",
    simpleMeaning:
      "PMI's official blueprint of what the PMP exam covers — three domains, with tasks and enablers under each.",
    definition:
      "The PMP Examination Content Outline (ECO) is the publicly available specification published by PMI that defines every domain, task, and enabler tested on the PMP exam. Every question on the live exam maps back to a task in the ECO. The current ECO uses three domains — People (≈42%), Process (≈50%), Business Environment (≈8%) — while the 2026 readiness update rebalances toward People 33% / Process 41% / Business 26%. The document is free to download from pmi.org and is the single most authoritative source for scope.",
    example:
      "Direct PDF: https://www.pmi.org/-/media/pmi/documents/public/pdf/certifications/new-pmp-examination-content-outline-2026.pdf — use it as a checklist: skim every task and ask 'do I have a concrete answer pattern for this?' If not, that's your next study target.",
    pmpMindset:
      "PMIism: ECO is the contract between you and the exam. Don't study from blogs or summaries first — read the source, then layer prep on top.",
    relatedTerms: ["PMI", "PMBOK", "Domain Weighting", "Process Group", "Knowledge Area"],
  },
];
