export const academySiteUrl = "https://nexustalenta-academy.com";

export const academySeoKeywords = [
  "belajar online",
  "kursus online",
  "kelas online",
  "belajar bahasa online",
  "kursus bahasa online",
  "belajar bahasa Jepang online",
  "kursus bahasa Jepang online",
  "kelas bahasa Jepang online",
  "belajar Jepang pemula",
  "kursus Jepang pemula",
  "belajar hiragana",
  "belajar katakana",
  "belajar kanji",
  "belajar JLPT N5",
  "kursus JLPT N5",
  "belajar JLPT N4",
  "kursus JLPT N4",
  "latihan JLPT online",
  "mock test JLPT",
  "persiapan JFT Basic",
  "kursus JFT Basic",
  "belajar bahasa Jepang untuk kerja",
  "bahasa Jepang SSW",
  "persiapan SSW Jepang",
  "interview kerja Jepang",
  "simulasi interview Jepang",
  "belajar kaiwa",
  "latihan percakapan Jepang",
  "grammar Jepang online",
  "kosakata Jepang",
  "flashcard Jepang",
  "reading Jepang",
  "listening Jepang",
  "AI tutor Jepang",
  "Nexus AI Nihongo",
  "belajar English interview",
  "kursus English interview",
  "latihan interview bahasa Inggris",
  "English conversation online",
  "AI English coach",
  "belajar speaking English",
  "latihan speaking English",
  "CEFR English online",
  "belajar English pemula",
  "kursus bahasa Inggris online",
  "business English online",
  "career English",
  "John AI coach",
  "Nexus AI English",
  "belajar bahasa Arab online",
  "kursus bahasa Arab online",
  "Arabic daily conversation",
  "bahasa Arab harian",
  "bahasa Arab Saudi",
  "Arabic untuk kerja",
  "Arabic untuk travel",
  "Arabic untuk umrah",
  "AI tutor Arabic",
  "Nexus AI Arabic",
  "PMP exam prep",
  "kursus PMP online",
  "persiapan PMP online",
  "PMP simulator",
  "PMP mock test",
  "PMP readiness",
  "AI PMP instructor",
  "Nexus PMP Exam Prep",
  "platform belajar online",
  "academy digital Indonesia",
  "kursus online Indonesia",
  "learning platform Indonesia",
  "AI learning platform",
  "belajar dengan AI",
  "AI tutor online",
  "adaptive learning",
  "progress tracking belajar",
  "sertifikat kursus online",
  "kelas karier global",
  "persiapan kerja luar negeri",
  "talenta Indonesia global",
  "Nexus Talenta Indonesia",
  "Nexus Talenta Academy",
  "NexusTalenta Academy",
  "Nexustalenta Academy",
  "Nexus Platform",
  "Nexus Academy online",
  "belajar online murah",
  "kursus bahasa Jepang murah",
  "kursus Jepang Jakarta",
  "kursus Jepang Indonesia",
  "kelas JLPT Indonesia",
  "belajar mandiri online",
  "latihan bahasa harian",
  "kelas bahasa untuk karier",
  "skill kerja global",
  "webinar karier Jepang",
  "pelatihan digital",
  "online academy Indonesia",
  "Nexus AI learning",
  "belajar online NexusTalenta",
] as const;

export const academyPublicRoutes = [
  { path: "/", priority: 1, changeFrequency: "weekly" },
  { path: "/checkout", priority: 0.9, changeFrequency: "weekly" },
  { path: "/login", priority: 0.55, changeFrequency: "monthly" },
  { path: "/register", priority: 0.6, changeFrequency: "monthly" },
  { path: "/contact", priority: 0.75, changeFrequency: "monthly" },
  { path: "/terms", priority: 0.35, changeFrequency: "yearly" },
  { path: "/refund-policy", priority: 0.35, changeFrequency: "yearly" },
  { path: "/overview/nihongo", priority: 0.88, changeFrequency: "weekly" },
  { path: "/overview/english", priority: 0.82, changeFrequency: "weekly" },
  { path: "/overview/arabic", priority: 0.76, changeFrequency: "weekly" },
  { path: "/overview/pmp", priority: 0.72, changeFrequency: "weekly" },
] as const;

export function getAcademySiteUrl() {
  const configuredUrl = process.env.NEXT_PUBLIC_ACADEMY_URL;

  if (!configuredUrl) {
    return academySiteUrl;
  }

  try {
    return new URL(configuredUrl).origin;
  } catch {
    return academySiteUrl;
  }
}
